--<ScriptOptions statementTerminator="@"/>


ALTER TABLE "EMOCAUX"."DEVIATIONCODETRX" ADD CONSTRAINT "PK_DEVIATIONCODETRX" PRIMARY KEY
	("DEVIATIONCODETRXID") /*Code Fragment was removed >> USING INDEX "EMOCAUX"."PK_DEVIATIONCODETRX"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOCAUX"."GAINLOSSSTATUSUPDATETRX" ADD CONSTRAINT "PK_GAINLOSSSTATUSUPDATETRX" PRIMARY KEY
	("GAINLOSSSTATUSUPDATETRXID") /*Code Fragment was removed >> USING INDEX "EMOCAUX"."PK_GAINLOSSSTATUSUPDATETRX"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOCAUX"."GEOLOCCODETRX" ADD CONSTRAINT "PK_GEOLOCCODETRX" PRIMARY KEY
	("GEOLOCCODETRXID") /*Code Fragment was removed >> USING INDEX "EMOCAUX"."PK_GEOLOCCODETRX"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOCAUX"."INVENTORYSTATUSUPDATETRX" ADD CONSTRAINT "PK_INVENTORYSTATUSUPDATE" PRIMARY KEY
	("INVENTORYSTATUSUPDATETRXID") /*Code Fragment was removed >> USING INDEX "EMOCAUX"."PK_INVENTORYSTATUSUPDATE"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOCAUX"."LOCATIONCODETRX" ADD CONSTRAINT "PK_LOACTIONCODETRX" PRIMARY KEY
	("LOCATIONCODETRXID") /*Code Fragment was removed >> USING INDEX "EMOCAUX"."PK_LOACTIONCODETRX"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOCAUX"."MAJORCOMMANDCODETRX" ADD CONSTRAINT "PK_MAJORCOMMANDCODETRX" PRIMARY KEY
	("MAJORCOMMANDCODETRXID") /*Code Fragment was removed >> USING INDEX "EMOCAUX"."PK_MAJORCOMMANDCODETRX"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOCAUX"."MICAPTRX" ADD CONSTRAINT "PK_MICAPTRXID" PRIMARY KEY
	("MICAPTRXID") /*Code Fragment was removed >> USING INDEX "EMOCAUX"."PK_MICAPTRXID"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOCAUX"."ORGANIZATIONTRX" ADD CONSTRAINT "PK_ORGANIZATIONLOADTRX" PRIMARY KEY
	("ORGANIZATIONLOADTRXID") /*Code Fragment was removed >> USING INDEX "EMOCAUX"."PK_ORGANIZATIONLOADTRX"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOCAUX"."STATUSCORRECTIONTRX" ADD CONSTRAINT "PK_STATUSCORRECTION" PRIMARY KEY
	("STATUSCORRECTIONID") /*Code Fragment was removed >> USING INDEX "EMOCAUX"."PK_STATUSCORRECTION"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOCAUX"."STATUSUPDATETRX" ADD CONSTRAINT "PK_STATUSUPDATETRX" PRIMARY KEY
	("STATUSUPDATETRXID") /*Code Fragment was removed >> USING INDEX "EMOCAUX"."PK_STATUSUPDATETRX"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOCAUX"."TRANSACTIONLOG" ADD CONSTRAINT "TRANSACTIONLOG_1" PRIMARY KEY
	("TRANSACTIONLOGID") /*Code Fragment was removed >> USING INDEX "EMOCAUX"."TRANSACTIONLOG_1"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOCAUX"."UTILIZATIONCODETRX" ADD CONSTRAINT "PK_UTILIZATIONCODETRX" PRIMARY KEY
	("UTILIZATIONCODETRXID") /*Code Fragment was removed >> USING INDEX "EMOCAUX"."PK_UTILIZATIONCODETRX"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOCAUX"."UVRCHANGETRX" ADD CONSTRAINT "PK_UVRCHANGETRX" PRIMARY KEY
	("UVRCHANGETRXID") /*Code Fragment was removed >> USING INDEX "EMOCAUX"."PK_UVRCHANGETRX"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOCAUX"."WHENDISCOVEREDCODETRX" ADD CONSTRAINT "PK_WHENDISCOVEREDCODETRX" PRIMARY KEY
	("WHENDISCOVEREDCODETRXID") /*Code Fragment was removed >> USING INDEX "EMOCAUX"."PK_WHENDISCOVEREDCODETRX"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOCAUX"."WORKCENTERTRX" ADD CONSTRAINT "PK_WORKCENTERTRX" PRIMARY KEY
	("WORKCENTERTRXID") /*Code Fragment was removed >> USING INDEX "EMOCAUX"."PK_WORKCENTERTRX"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOCAUX"."WORKUNITCODETRX" ADD CONSTRAINT "PK_WORKUNITCODETRX" PRIMARY KEY
	("WORKUNITCODETRXID") /*Code Fragment was removed >> USING INDEX "EMOCAUX"."PK_WORKUNITCODETRX"<< Code Fragment was removed - END*/

@
