--<ScriptOptions statementTerminator=";"/>


CREATE TABLESPACE "EMOCMAIN"
	BLOCKSIZE 8192
	LOGGING
	DEFAULT STORAGE (
	INITIAL 65536
	MINEXTENTS 1
	MAXEXTENTS 2147483645
	PCTINCREASE 0)
	SEGMENT SPACE MANAGEMENT AUTO;
