--<ScriptOptions statementTerminator=";"/>


CREATE INDEX "EMOCAUX"."IX_GEOLOCCODETRX_DATEPROCESSED"
	ON "EMOCAUX"."GEOLOCCODETRX"
	("DATEPROCESSED"		ASC)
	INITRANS 2
	LOGGING
	TABLESPACE "EMOCMAIN"
	STORAGE (
	INITIAL 65536
	NEXT 1048576
	MINEXTENTS 1
	PCTINCREASE 0
	BUFFER_POOL DEFAULT);

CREATE INDEX "EMOCAUX"."IX_GEOLOCCODETRX_GEOLOCCODE"
	ON "EMOCAUX"."GEOLOCCODETRX"
	("GEOLOCCODE"		ASC)
	INITRANS 2
	LOGGING
	TABLESPACE "EMOCMAIN"
	STORAGE (
	INITIAL 65536
	NEXT 1048576
	MINEXTENTS 1
	PCTINCREASE 0
	BUFFER_POOL DEFAULT);

CREATE UNIQUE INDEX "EMOCAUX"."PK_DEVIATIONCODETRX"
	ON "EMOCAUX"."DEVIATIONCODETRX"
	("DEVIATIONCODETRXID"		ASC)
	INITRANS 2
	LOGGING
	TABLESPACE "EMOCMAIN"
	STORAGE (
	INITIAL 65536
	NEXT 1048576
	MINEXTENTS 1
	PCTINCREASE 0
	BUFFER_POOL DEFAULT);

CREATE UNIQUE INDEX "EMOCAUX"."PK_GAINLOSSSTATUSUPDATETRX"
	ON "EMOCAUX"."GAINLOSSSTATUSUPDATETRX"
	("GAINLOSSSTATUSUPDATETRXID"		ASC)
	INITRANS 2
	LOGGING
	TABLESPACE "EMOCMAIN"
	STORAGE (
	INITIAL 65536
	NEXT 1048576
	MINEXTENTS 1
	PCTINCREASE 0
	BUFFER_POOL DEFAULT);

CREATE UNIQUE INDEX "EMOCAUX"."PK_GEOLOCCODETRX"
	ON "EMOCAUX"."GEOLOCCODETRX"
	("GEOLOCCODETRXID"		ASC)
	INITRANS 2
	LOGGING
	TABLESPACE "EMOCMAIN"
	STORAGE (
	INITIAL 65536
	NEXT 1048576
	MINEXTENTS 1
	PCTINCREASE 0
	BUFFER_POOL DEFAULT);

CREATE UNIQUE INDEX "EMOCAUX"."PK_INVENTORYSTATUSUPDATE"
	ON "EMOCAUX"."INVENTORYSTATUSUPDATETRX"
	("INVENTORYSTATUSUPDATETRXID"		ASC)
	INITRANS 2
	LOGGING
	TABLESPACE "EMOCMAIN"
	STORAGE (
	INITIAL 65536
	NEXT 1048576
	MINEXTENTS 1
	PCTINCREASE 0
	BUFFER_POOL DEFAULT);

CREATE UNIQUE INDEX "EMOCAUX"."PK_LOACTIONCODETRX"
	ON "EMOCAUX"."LOCATIONCODETRX"
	("LOCATIONCODETRXID"		ASC)
	INITRANS 2
	LOGGING
	TABLESPACE "EMOCMAIN"
	STORAGE (
	INITIAL 65536
	NEXT 1048576
	MINEXTENTS 1
	PCTINCREASE 0
	BUFFER_POOL DEFAULT);

CREATE UNIQUE INDEX "EMOCAUX"."PK_MAJORCOMMANDCODETRX"
	ON "EMOCAUX"."MAJORCOMMANDCODETRX"
	("MAJORCOMMANDCODETRXID"		ASC)
	INITRANS 2
	LOGGING
	TABLESPACE "EMOCMAIN"
	STORAGE (
	INITIAL 65536
	NEXT 1048576
	MINEXTENTS 1
	PCTINCREASE 0
	BUFFER_POOL DEFAULT);

CREATE UNIQUE INDEX "EMOCAUX"."PK_MICAPTRXID"
	ON "EMOCAUX"."MICAPTRX"
	("MICAPTRXID"		ASC)
	INITRANS 2
	LOGGING
	TABLESPACE "EMOCMAIN"
	STORAGE (
	INITIAL 65536
	NEXT 1048576
	MINEXTENTS 1
	PCTINCREASE 0
	BUFFER_POOL DEFAULT);

CREATE UNIQUE INDEX "EMOCAUX"."PK_ORGANIZATIONLOADTRX"
	ON "EMOCAUX"."ORGANIZATIONTRX"
	("ORGANIZATIONLOADTRXID"		ASC)
	INITRANS 2
	LOGGING
	TABLESPACE "EMOCMAIN"
	STORAGE (
	INITIAL 65536
	NEXT 1048576
	MINEXTENTS 1
	PCTINCREASE 0
	BUFFER_POOL DEFAULT);

CREATE UNIQUE INDEX "EMOCAUX"."PK_STATUSCORRECTION"
	ON "EMOCAUX"."STATUSCORRECTIONTRX"
	("STATUSCORRECTIONID"		ASC)
	INITRANS 2
	LOGGING
	TABLESPACE "EMOCMAIN"
	STORAGE (
	INITIAL 65536
	NEXT 1048576
	MINEXTENTS 1
	PCTINCREASE 0
	BUFFER_POOL DEFAULT);

CREATE UNIQUE INDEX "EMOCAUX"."PK_STATUSUPDATETRX"
	ON "EMOCAUX"."STATUSUPDATETRX"
	("STATUSUPDATETRXID"		ASC)
	INITRANS 2
	LOGGING
	TABLESPACE "EMOCMAIN"
	STORAGE (
	INITIAL 65536
	NEXT 1048576
	MINEXTENTS 1
	PCTINCREASE 0
	BUFFER_POOL DEFAULT);

CREATE UNIQUE INDEX "EMOCAUX"."PK_UTILIZATIONCODETRX"
	ON "EMOCAUX"."UTILIZATIONCODETRX"
	("UTILIZATIONCODETRXID"		ASC)
	INITRANS 2
	LOGGING
	TABLESPACE "EMOCMAIN"
	STORAGE (
	INITIAL 65536
	NEXT 1048576
	MINEXTENTS 1
	PCTINCREASE 0
	BUFFER_POOL DEFAULT);

CREATE UNIQUE INDEX "EMOCAUX"."PK_UVRCHANGETRX"
	ON "EMOCAUX"."UVRCHANGETRX"
	("UVRCHANGETRXID"		ASC)
	INITRANS 2
	LOGGING
	TABLESPACE "EMOCMAIN"
	STORAGE (
	INITIAL 65536
	NEXT 1048576
	MINEXTENTS 1
	PCTINCREASE 0
	BUFFER_POOL DEFAULT);

CREATE UNIQUE INDEX "EMOCAUX"."PK_WHENDISCOVEREDCODETRX"
	ON "EMOCAUX"."WHENDISCOVEREDCODETRX"
	("WHENDISCOVEREDCODETRXID"		ASC)
	INITRANS 2
	LOGGING
	TABLESPACE "EMOCMAIN"
	STORAGE (
	INITIAL 65536
	NEXT 1048576
	MINEXTENTS 1
	PCTINCREASE 0
	BUFFER_POOL DEFAULT);

CREATE UNIQUE INDEX "EMOCAUX"."PK_WORKCENTERTRX"
	ON "EMOCAUX"."WORKCENTERTRX"
	("WORKCENTERTRXID"		ASC)
	INITRANS 2
	LOGGING
	TABLESPACE "EMOCMAIN"
	STORAGE (
	INITIAL 65536
	NEXT 1048576
	MINEXTENTS 1
	PCTINCREASE 0
	BUFFER_POOL DEFAULT);

CREATE UNIQUE INDEX "EMOCAUX"."PK_WORKUNITCODETRX"
	ON "EMOCAUX"."WORKUNITCODETRX"
	("WORKUNITCODETRXID"		ASC)
	INITRANS 2
	LOGGING
	TABLESPACE "EMOCMAIN"
	STORAGE (
	INITIAL 65536
	NEXT 1048576
	MINEXTENTS 1
	PCTINCREASE 0
	BUFFER_POOL DEFAULT);

CREATE UNIQUE INDEX "EMOCAUX"."TRANSACTIONLOG_1"
	ON "EMOCAUX"."TRANSACTIONLOG"
	("TRANSACTIONLOGID"		ASC)
	INITRANS 2
	LOGGING
	TABLESPACE "EMOCMAIN"
	STORAGE (
	INITIAL 65536
	NEXT 1048576
	MINEXTENTS 1
	MAXEXTENTS 2147483645
	PCTINCREASE 0
	BUFFER_POOL DEFAULT);
