--<ScriptOptions statementTerminator=";"/>


ALTER TABLE "EMOCAUX"."DEVIATIONCODETRX" ADD CONSTRAINT "PK_DEVIATIONCODETRX" PRIMARY KEY
	("DEVIATIONCODETRXID") USING INDEX "EMOCAUX"."PK_DEVIATIONCODETRX";

ALTER TABLE "EMOCAUX"."GAINLOSSSTATUSUPDATETRX" ADD CONSTRAINT "PK_GAINLOSSSTATUSUPDATETRX" PRIMARY KEY
	("GAINLOSSSTATUSUPDATETRXID") USING INDEX "EMOCAUX"."PK_GAINLOSSSTATUSUPDATETRX";

ALTER TABLE "EMOCAUX"."GEOLOCCODETRX" ADD CONSTRAINT "PK_GEOLOCCODETRX" PRIMARY KEY
	("GEOLOCCODETRXID") USING INDEX "EMOCAUX"."PK_GEOLOCCODETRX";

ALTER TABLE "EMOCAUX"."INVENTORYSTATUSUPDATETRX" ADD CONSTRAINT "PK_INVENTORYSTATUSUPDATE" PRIMARY KEY
	("INVENTORYSTATUSUPDATETRXID") USING INDEX "EMOCAUX"."PK_INVENTORYSTATUSUPDATE";

ALTER TABLE "EMOCAUX"."LOCATIONCODETRX" ADD CONSTRAINT "PK_LOACTIONCODETRX" PRIMARY KEY
	("LOCATIONCODETRXID") USING INDEX "EMOCAUX"."PK_LOACTIONCODETRX";

ALTER TABLE "EMOCAUX"."MAJORCOMMANDCODETRX" ADD CONSTRAINT "PK_MAJORCOMMANDCODETRX" PRIMARY KEY
	("MAJORCOMMANDCODETRXID") USING INDEX "EMOCAUX"."PK_MAJORCOMMANDCODETRX";

ALTER TABLE "EMOCAUX"."MICAPTRX" ADD CONSTRAINT "PK_MICAPTRXID" PRIMARY KEY
	("MICAPTRXID") USING INDEX "EMOCAUX"."PK_MICAPTRXID";

ALTER TABLE "EMOCAUX"."ORGANIZATIONTRX" ADD CONSTRAINT "PK_ORGANIZATIONLOADTRX" PRIMARY KEY
	("ORGANIZATIONLOADTRXID") USING INDEX "EMOCAUX"."PK_ORGANIZATIONLOADTRX";

ALTER TABLE "EMOCAUX"."STATUSCORRECTIONTRX" ADD CONSTRAINT "PK_STATUSCORRECTION" PRIMARY KEY
	("STATUSCORRECTIONID") USING INDEX "EMOCAUX"."PK_STATUSCORRECTION";

ALTER TABLE "EMOCAUX"."STATUSUPDATETRX" ADD CONSTRAINT "PK_STATUSUPDATETRX" PRIMARY KEY
	("STATUSUPDATETRXID") USING INDEX "EMOCAUX"."PK_STATUSUPDATETRX";

ALTER TABLE "EMOCAUX"."TRANSACTIONLOG" ADD CONSTRAINT "TRANSACTIONLOG_1" PRIMARY KEY
	("TRANSACTIONLOGID") USING INDEX "EMOCAUX"."TRANSACTIONLOG_1";

ALTER TABLE "EMOCAUX"."UTILIZATIONCODETRX" ADD CONSTRAINT "PK_UTILIZATIONCODETRX" PRIMARY KEY
	("UTILIZATIONCODETRXID") USING INDEX "EMOCAUX"."PK_UTILIZATIONCODETRX";

ALTER TABLE "EMOCAUX"."UVRCHANGETRX" ADD CONSTRAINT "PK_UVRCHANGETRX" PRIMARY KEY
	("UVRCHANGETRXID") USING INDEX "EMOCAUX"."PK_UVRCHANGETRX";

ALTER TABLE "EMOCAUX"."WHENDISCOVEREDCODETRX" ADD CONSTRAINT "PK_WHENDISCOVEREDCODETRX" PRIMARY KEY
	("WHENDISCOVEREDCODETRXID") USING INDEX "EMOCAUX"."PK_WHENDISCOVEREDCODETRX";

ALTER TABLE "EMOCAUX"."WORKCENTERTRX" ADD CONSTRAINT "PK_WORKCENTERTRX" PRIMARY KEY
	("WORKCENTERTRXID") USING INDEX "EMOCAUX"."PK_WORKCENTERTRX";

ALTER TABLE "EMOCAUX"."WORKUNITCODETRX" ADD CONSTRAINT "PK_WORKUNITCODETRX" PRIMARY KEY
	("WORKUNITCODETRXID") USING INDEX "EMOCAUX"."PK_WORKUNITCODETRX";
