create or replace view EMOC3.AIRCRAFT_ENGINE_DATA_VIEW as
SELECT * from (select 
WINGS.wingname "WING",
WINGS.UNITID "UNITID",
WINGS.ELC "ELC",
SQUADRONS.squadronname,
AIRCRAFT.MOCID,
AIRCRAFT.aircraftyear "AIRCRAFTYEAR",
AIRCRAFT.shorttailnumber "TAILNUMBER",
AIRCRAFT.misequipid "MISEQUIPID",
AIRCRAFT.serialnumber "SERIALNUMBER",
AIRCRAFTMDS.AIRCRAFTMDS "AIRCRAFTMDS",
TO_CHAR(AIRCRAFTENGINEDATA.enginenumber) enginenumber,
TO_NUMBER(TO_CHAR(SUM((SCHEDULE.ACTUALLANDING - SCHEDULE.ACTUALTAKEOFF) * 24), '99999.99')) "ENGHRSFLOWN",
REMARKS.REMARKS "AIRCRAFTREMARKS"
FROM EMOC3.AIRCRAFT AIRCRAFT, EMOC3.WINGS WINGS, EMOC3.SQUADRONS SQUADRONS, EMOC3.AIRCRAFTMDS AIRCRAFTMDS, 
EMOC3.AIRCRAFTENGINEDATA AIRCRAFTENGINEDATA, EMOC3.SCHEDULE SCHEDULE, EMOC3.REMARKS 
WHERE (    (AIRCRAFT.aircraftid = AIRCRAFTENGINEDATA.aircraftid)
AND (AIRCRAFT.squadronid = SQUADRONS.SQUADRONID)
AND (SQUADRONS.wingid = WINGS.wingid)
AND (AIRCRAFT.aircraftmdsid = AIRCRAFTMDS.aircraftmdsid)
AND (SCHEDULE.AIRCRAFTID = AIRCRAFT.AIRCRAFTID(+))
AND (AIRCRAFT.remarksid = REMARKS.REMARKSID(+))
)
GROUP BY
WINGS.wingname,
WINGS.UNITID,
WINGS.ELC,
AIRCRAFT.MOCID,
SQUADRONS.squadronname,
AIRCRAFT.aircraftyear,
AIRCRAFT.shorttailnumber,
AIRCRAFT.misequipid,
AIRCRAFT.serialnumber,
AIRCRAFTMDS.AIRCRAFTMDS,
AIRCRAFTENGINEDATA.enginenumber,
REMARKS.REMARKS
ORDER BY AIRCRAFT.shorttailnumber, AIRCRAFTENGINEDATA.enginenumber)
