--<ScriptOptions statementTerminator="@"/>


CREATE OR REPLACE VIEW "EMOC3"."WRITEUPS_AND_MICAPS_VIEW" ("WING", "UNITID", "ELC", "SQUADRONNAME", "MOCID", "AIRCRAFTYEAR", "TAILNUMBER", "MISEQUIPID", "SERIALNUMBER", "AIRCRAFTMDS", "OTHERMDS", "CONDCODE", "STATUSCODE", "STATUSSTARTDATE", "STATUSWUCLCN", "AIRCRAFTWUC", "AIRCRAFTETIC", "WRITEUPTIME", "WRITEUPJCN", "CORRECTED", "CORRECTEDTIME", "PACER", "WRITEUPETIC", "SYMBOL", "WRITEUPWUC", "DISCREPANCY", "CORRECTIVEACTION", "WRITEUPCAMSINIT", "DOCUMENTNUMBER", "PART", "ETA", "MICAPCAMSINIT", "AIRCRAFTREMARKS") AS
SELECT DISTINCT WINGS.wingname "WING",
    WINGS.UNITID "UNITID",
    WINGS.ELC "ELC",
       SQUADRONS.squadronname,
AIRCRAFT.MOCID,
    AIRCRAFT.aircraftyear "AIRCRAFTYEAR",
       AIRCRAFT.shorttailnumber "TAILNUMBER",
    AIRCRAFT.misequipid "MISEQUIPID",
       AIRCRAFT.serialnumber "SERIALNUMBER",
       AIRCRAFTMDS.AIRCRAFTMDS "AIRCRAFTMDS",
    AIRCRAFT.RELATEDMDS "OTHERMDS",
       CONDITIONCODES.conditioncode "CONDCODE",
    STATUSCODE.STATUSCODE,
     AIRCRAFT.STATUSSTARTDATE || ' ' || AIRCRAFT.STATUSSTARTTIME "STATUSSTARTDATE",
    AIRCRAFT.STATUSWUCLCN ,
    WUC.WUCCODE "AIRCRAFTWUC",
    AIRCRAFT.etic "AIRCRAFTETIC",
       WRITEUPS.writeuptime,
    WRITEUPS.jcn "WRITEUPJCN",
    DECODE(TO_CHAR(WRITEUPS.corrected), '1', 'Y', 'N') CORRECTED,
       WRITEUPS.correctedtime,
    DECODE(TO_CHAR(WRITEUPS.pacer), '1', 'Y', 'N') PACER,
    WRITEUPS.etic "WRITEUPETIC",
    SYMBOLS.symbol,
    wuc2.WUCCODE "WRITEUPWUC",
       WRITEUPS.discrepancy,
    WRITEUPS.correctiveaction,
    WRITEUPS.camsinit "WRITEUPCAMSINIT" ,
    MICAP.documentnumber,
    MICAP.nomenclature AS part,
    MICAP.estimateddeliverydate AS eta,
    MICAP.camsinit "MICAPCAMSINIT",
    REMARKS.REMARKS "AIRCRAFTREMARKS"
 FROM
        AIRCRAFT,
          SQUADRONS,
      WINGS,
          CONDITIONCODES,
    CONDITIONSTATUS,
          AIRCRAFTMDS,
    WUC,
    WUC WUC2,
    SYMBOLS,
    STATUSCODE,
    WRITEUPS,
    MICAP,
    REMARKS
 WHERE (
         (AIRCRAFT.aircraftid = WRITEUPS.aircraftid)
        AND (WRITEUPS.jcn = MICAP.jobcontrolnumber(+))
        AND SYMBOLS.symbolid = WRITEUPS.SYMBOLID
  AND (AIRCRAFT.squadronid = SQUADRONS.squadronid)
        AND (WINGS.wingid = SQUADRONS.wingid)
        AND (AIRCRAFT.conditioncodeid = CONDITIONCODES.condcodeid(+))
  AND (AIRCRAFTMDS.aircraftmdsid = AIRCRAFT.aircraftmdsid(+))
        AND (AIRCRAFT.AIRCRAFTWUCID = WUC.WUCID(+))
        AND (WRITEUPS.WUCID = WUC2.WUCID(+))
        AND (AIRCRAFT.STATUSCODEID = STATUSCODE.STATUSCODEID(+))
  AND (AIRCRAFT.remarksid = REMARKS.REMARKSID(+))
          )
 
 
 
 
 
 
 
 
@

CREATE OR REPLACE VIEW "EMOC3"."WEAPONS_VIEW" ("WING", "UNITID", "ELC", "SQUADRONNAME", "MOCID", "AIRCRAFTYEAR", "TAILNUMBER", "AIRCRAFTMDS", "COMBATSCL", "WEAPONSNUMBER", "WEAPONTYPE", "ORDNANCE", "CONFIGURATION", "HOTGUNS", "ARM_DEARM") AS
SELECT WINGS.wingname WING,
    WINGS.unitid UNITID,
    WINGS.elc,
    squ.squadronname,
AIRCRAFT.MOCID,
    AIRCRAFT.aircraftyear AIRCRAFTYEAR,
       AIRCRAFT.shorttailnumber TAILNUMBER,
    "MDS".AIRCRAFTMDS AIRCRAFTMDS,
    COMBATSCLS.combatscl,
       TO_CHAR(WEAPONSLOAD.weaponsnumber) weaponsnumber,
    WEAPONTYPES.weapontype,
    ORDNANCE.ORDNANCE,
       ORDNANCE.configuration,
    DECODE(TO_CHAR(AIRCRAFT.hotguns), '1', 'Y', 'N') hotguns,
    DECODE(TO_CHAR(AIRCRAFT.arm_dearm), '1', 'Y', 'N') arm_dearm
  FROM EMOC3.AIRCRAFT,
       EMOC3.COMBATSCLS,
       EMOC3.ORDNANCE,
       EMOC3.WEAPONSINFO,
       EMOC3.WEAPONSLOAD,
       EMOC3.WEAPONTYPES,
       EMOC3.SQUADRONS squ,
       EMOC3.WINGS WINGS,
       EMOC3.AIRCRAFTMDS "MDS"
 WHERE (    (COMBATSCLS.combatsclid(+) = AIRCRAFT.combatsclid)
        AND (COMBATSCLS.combatsclid = WEAPONSINFO.combatsclid(+))
        AND (AIRCRAFT.aircraftid = WEAPONSLOAD.aircraftid(+))
        AND (ORDNANCE.ordnanceid(+) = WEAPONSLOAD.ordnanceid)
        AND (WEAPONTYPES.weaponstypeid = ORDNANCE.weaponstypeid)
        AND (squ.squadronid = AIRCRAFT.squadronid)
        AND (WINGS.wingid = squ.wingid)
        AND ("MDS".aircraftmdsid = AIRCRAFT.aircraftmdsid)
       ) ORDER BY TAILNUMBER
/* *** DCW Evaluation Issue "DDL_VIEW_ORDER_BY".Corresponding line no in the source file:10478 *** */
 
 
 
 
 
 
 
 
@

CREATE OR REPLACE VIEW "EMOC3"."STATUSTRANSITIONRULESVIEW" ("STATUSCODEID", "TRANSITION2ID", "MOCID") AS
SELECT   str.statuscodeid, str.transition2id, str.mocid
FROM statustransitionrule str, statuscode sc
WHERE str.statuscodeid = sc.statuscodeid
AND sc.allowsortieupdate = 1
ORDER BY sc.ordernumber
/* *** DCW Evaluation Issue "DDL_VIEW_ORDER_BY".Corresponding line no in the source file:10493 *** */
 
 
 
 
 
 
 
 
@

CREATE OR REPLACE VIEW "EMOC3"."SQUADRONVIEW" ("SQUADRONID", "SQUADRONNAME", "COLORVALUE", "WINGID", "COLORNAME", "SHORTNAME", "FONTCOLOR", "MOCID") AS
SELECT   squadronid, squadronname, colorvalue, wingid,
   colorname, shortname, fontcolor, squadrons.mocid
FROM squadrons LEFT JOIN colors ON squadrons.colorid = colors.colorid
ORDER BY squadronname
/* *** DCW Evaluation Issue "DDL_VIEW_ORDER_BY".Corresponding line no in the source file:10507 *** */
 
 
 
 
 
 
 
 
@

CREATE OR REPLACE VIEW "EMOC3"."SQUADRONSORTORDERVIEW" ("USERID", "SQUADRONID", "SORTORDER", "SQUADRONNAME", "SHORTNAME", "COLORVALUE", "WINGID", "COLORNAME", "FONTCOLOR", "MOCID") AS
SELECT   userid, squadrons.squadronid, sortorder, squadronname,
         shortname, colorvalue, wingid, colorname, fontcolor, squadrons.mocid
FROM emoc3.squadron_sort_order JOIN emoc3.squadrons ON squadron_sort_order.squadronid = squadrons.squadronid
LEFT JOIN emoc3.colors ON squadrons.colorid = colors.colorid
ORDER BY wingid, sortorder
/* *** DCW Evaluation Issue "DDL_VIEW_ORDER_BY".Corresponding line no in the source file:10522 *** */
@

CREATE OR REPLACE VIEW "EMOC3"."SQUADRONMICAPCOUNT" ("SQUADRONID", "SQUADRONNAME", "MISEQUIPID", "AIRCRAFTID", "WINGID", "UNITID", "ELC", "MOCID", "MICAPCOUNT") AS
SELECT squadrons.squadronid, squadrons.squadronname, aircraft.misequipid,
       aircraft.aircraftid, wings.wingid, wings.unitid, wings.elc,
       wings.mocid, (Select count(*) from micap 
            where ( (aircraft.aircraftid = micap.aircraftid) 
                or (micap.enterpriselocationcode = wings.elc 
                    and micap.UNITID = wings.unitid 
                    and micap.EQUIPMENTID = aircraft.misequipid))) as micapcount
  FROM squadrons, aircraft, wings
 WHERE (    (squadrons.squadronid = aircraft.squadronid)
        AND (wings.wingid = squadrons.wingid))
 
 
 
 
 
 
 
 
@

CREATE OR REPLACE VIEW "EMOC3"."SEMEDX_VIEW" ("WING", "UNITID", "ELC", "SQUADRONNAME", "MOCID", "AIRCRAFTYEAR", "TAILNUMBER", "MISEQUIPID", "SERIALNUMBER", "AIRCRAFTMDS", "ENGINENUMBER", "SORTIEDATE", "SORTIENUM", "CODE", "COLORVALUE", "COLORNAME", "COLORRANK", "SAMPLEDATE", "REASON", "NOTIFIEDBY", "MOCCONTROLLER", "SEMEDXLASTUPDATED", "HOURSREQUIRED", "HOURSREMAINING", "EXPEDITED") AS
SELECT
    WINGS.wingname "WING",
    WINGS.UNITID "UNITID",
    WINGS.ELC "ELC",
       SQUADRONS.squadronname,
AIRCRAFT.MOCID,
    AIRCRAFT.aircraftyear "AIRCRAFTYEAR",
       AIRCRAFT.shorttailnumber "TAILNUMBER",
    AIRCRAFT.misequipid "MISEQUIPID",
       AIRCRAFT.serialnumber "SERIALNUMBER",
       AIRCRAFTMDS.AIRCRAFTMDS "AIRCRAFTMDS",
    TO_CHAR(AIRCRAFTENGINEDATA.enginenumber) "ENGINENUMBER",
    SCHEDULE.SORTIEDATE,
    TO_CHAR(SCHEDULE.SORTIENUM) "SORTIENUM",
    SEMEDX.SEMEDX "CODE",
    COLORS.colorvalue "COLORVALUE",
    COLORS.COLORNAME "COLORNAME",
    TO_CHAR(COLORRULES.colorrank) "COLORRANK",
    TO_CHAR(SEMEDXDATA.SAMPLEDATE, 'MM/DD/YYYY HH24:MI:SS') "SAMPLEDATE",
    SEMEDXDATA.REASON "REASON",
    SEMEDXDATA.NOTIFIEDBY "NOTIFIEDBY",
    SEMEDXDATA.MOCCONTROLLER "MOCCONTROLLER",
    TO_CHAR(SEMEDXDATA.SEMEDXLASTUPDATED, 'MM/DD/YYYY HH24:MI:SS') "SEMEDXLASTUPDATED",
    SEMEDXDATA.HOURSREQUIRED "HOURSREQUIRED",
    SEMEDXDATA.HOURSREMAINING "HOURSREMAINING",
    DECODE(TO_CHAR(SEMEDXDATA.EXPEDITERNOTIFIED), '1', 'Y', 'N') "EXPEDITED"
FROM EMOC3.AIRCRAFT, EMOC3.SEMEDX, EMOC3.WINGS, EMOC3.SQUADRONS, EMOC3.AIRCRAFTMDS, EMOC3.COLORS, EMOC3.COLORRULES, EMOC3.AIRCRAFTENGINEDATA, EMOC3.SEMEDXDATA, EMOC3.SCHEDULE
WHERE (    (AIRCRAFT.aircraftid = AIRCRAFTENGINEDATA.aircraftid)
        AND (AIRCRAFT.squadronid = SQUADRONS.SQUADRONID)
        AND (SQUADRONS.wingid = WINGS.wingid)
        AND (AIRCRAFT.aircraftmdsid = AIRCRAFTMDS.aircraftmdsid)
        AND (AIRCRAFTENGINEDATA.enginedataid = SEMEDXDATA.enginedataid)
        AND (SEMEDX.semedxid = SEMEDXDATA.semedxid)
        AND (SEMEDX.colorrulesid = COLORRULES.colorrulesid)
  AND (COLORRULES.CODETYPE = 'SEMEDX')
        AND (COLORRULES.colorid = COLORS.colorid)
  AND (SEMEDXDATA.scheduleid = SCHEDULE.scheduleid)
       )
 
 
 
 
 
 
 
 
@

CREATE OR REPLACE VIEW "EMOC3"."SCHEDULE_STATUS_VIEW" ("WING", "UNITID", "SQUADRONNAME", "SORTIEDATE", "SORTIE", "MOD", "GO", "BLOCKNUMBER", "AIRCRAFTYEAR", "TAILNUMBER", "AIRCRAFTMDS") AS
SELECT
--need to add records from schedulestatus table
			WG.WINGNAME "WING",
			WG.UNITID "UNITID",
			SQ.SQUADRONNAME,
			SC.SORTIEDATE "SORTIEDATE",
			TO_CHAR(SC.SORTIENUM) "SORTIE",
			TO_CHAR(SC.SORTIEMOD) "MOD",
	 		TO_CHAR(SC.GO) "GO",
			TO_CHAR(SC.BLOCKNUMBER) "BLOCKNUMBER",
			AC.AIRCRAFTYEAR "AIRCRAFTYEAR",
			AC.SHORTTAILNUMBER "TAILNUMBER",
			MDS.AIRCRAFTMDS "AIRCRAFTMDS"
		FROM EMOC3.SCHEDULE SC
			LEFT JOIN EMOC3.AIRCRAFT AC ON SC.AIRCRAFTID = AC.AIRCRAFTID
			LEFT JOIN EMOC3.SQUADRONS SQ ON SC.SQUADRONID = SQ.SQUADRONID
			LEFT JOIN EMOC3.SCHEDULEDEVIATIONS DEV ON SC.SCHEDULEID = DEV.SCHEDULEID
			LEFT JOIN EMOC3.AIRCRAFTMDS MDS ON AC.AIRCRAFTMDSID = MDS.AIRCRAFTMDSID
			LEFT JOIN EMOC3.STATUSCODE ST ON AC.STATUSCODEID = ST.STATUSCODEID
			LEFT JOIN EMOC3.REMARKS REM1 ON REM1.REMARKSID = MAINTREMARKS
			LEFT JOIN EMOC3.REMARKS REM2 ON REM2.REMARKSID = SCHEDULEREMARKS
			JOIN EMOC3.WINGS WG ON SQ.WINGID = WG.WINGID

 
 
 
 
 
 
 
 
@

CREATE OR REPLACE VIEW "EMOC3"."PILOTVIEW" ("SQUADRONID", "SQUADRONNAME", "COLORVALUE", "WINGID", "COLORNAME", "SHORTNAME", "FONTCOLOR", "MOCID") AS
SELECT   squadronid, squadronname, colorvalue, wingid,
   colorname, shortname, fontcolor, squadrons.mocid
FROM squadrons LEFT JOIN colors ON squadrons.colorid = colors.colorid
ORDER BY squadronname
/* *** DCW Evaluation Issue "DDL_VIEW_ORDER_BY".Corresponding line no in the source file:10629 *** */
 
 
 
 
 
 
 
 
@

CREATE OR REPLACE VIEW "EMOC3"."JOAP_VIEW" ("WING", "UNITID", "ELC", "SQUADRONNAME", "MOCID", "AIRCRAFTYEAR", "TAILNUMBER", "MISEQUIPID", "SERIALNUMBER", "AIRCRAFTMDS", "ENGINENUMBER", "SORTIEDATE", "SORTIENUM", "JOAPCODE", "REDCAPSTATUS", "COLORVALUE", "COLORNAME", "COLORRANK", "SAMPLEDATE", "REASON", "NOTIFIEDBY", "MOCCONTROLLER", "JOAPLASTUPDATED", "HOURSREQUIRED", "HOURSREMAINING", "EXPEDITED") AS
SELECT
      WINGS.wingname "WING",
    WINGS.UNITID "UNITID",
    WINGS.ELC "ELC",
       SQUADRONS.squadronname,
AIRCRAFT.MOCID,
    AIRCRAFT.aircraftyear "AIRCRAFTYEAR",
       AIRCRAFT.shorttailnumber "TAILNUMBER",
    AIRCRAFT.misequipid "MISEQUIPID",
       AIRCRAFT.serialnumber "SERIALNUMBER",
       AIRCRAFTMDS.AIRCRAFTMDS "AIRCRAFTMDS",
    TO_CHAR(AIRCRAFTENGINEDATA.enginenumber) "ENGINENUMBER",
    SCHEDULE.SORTIEDATE,
    TO_CHAR(SCHEDULE.SORTIENUM) "SORTIENUM",
    JOAP.joapcode "JOAPCODE",
    DECODE(TO_CHAR(JOAP.REDCAPSTATUS), '1', 'Y', 'N') "REDCAPSTATUS",
    COLORS.colorvalue "COLORVALUE",
    COLORS.COLORNAME "COLORNAME",
    TO_CHAR(COLORRULES.colorrank) "COLORRANK",
    TO_CHAR(JOAPDATA.SAMPLEDATE, 'MM/DD/YYYY HH24:MI:SS') "SAMPLEDATE",
    JOAPDATA.REASON "REASON",
    JOAPDATA.NOTIFIEDBY "NOTIFIEDBY",
    JOAPDATA.MOCCONTROLLER "MOCCONTROLLER",
    TO_CHAR(JOAPDATA.JOAPLASTUPDATED, 'MM/DD/YYYY HH24:MI:SS') "JOAPLASTUPDATED",
    JOAPDATA.HOURSREQUIRED "HOURSREQUIRED",
    JOAPDATA.HOURSREMAINING "HOURSREMAINING",
    DECODE(TO_CHAR(JOAPDATA.EXPEDITERNOTIFIED), '1', 'Y', 'N') "EXPEDITED"
FROM EMOC3.AIRCRAFT, EMOC3.AIRCRAFTMDS, EMOC3.WINGS, EMOC3.SQUADRONS, EMOC3.JOAP, EMOC3.COLORS, EMOC3.COLORRULES, EMOC3.AIRCRAFTENGINEDATA, EMOC3.JOAPDATA, EMOC3.SCHEDULE
WHERE (    (AIRCRAFT.aircraftid = AIRCRAFTENGINEDATA.aircraftid)
        AND (AIRCRAFT.squadronid = SQUADRONS.SQUADRONID)
        AND (SQUADRONS.wingid = WINGS.wingid)
        AND (AIRCRAFT.aircraftmdsid = AIRCRAFTMDS.aircraftmdsid)
        AND (AIRCRAFTENGINEDATA.enginedataid = JOAPDATA.enginedataid)
        AND (JOAP.joapid = JOAPDATA.joapid)
        AND (JOAP.colorrulesid = COLORRULES.colorrulesid)
  AND (COLORRULES.CODETYPE = 'JOAP')
        AND (COLORRULES.colorid = COLORS.colorid)
  AND (JOAPDATA.scheduleid(+) = SCHEDULE.scheduleid)
       )
ORDER BY AIRCRAFTENGINEDATA.enginenumber, JOAPDATA.SAMPLEDATE
/* *** DCW Evaluation Issue "DDL_VIEW_ORDER_BY".Corresponding line no in the source file:10679 *** */
 
 
 
 
 
 
 
 
@

CREATE OR REPLACE VIEW "EMOC3"."FLYBOARD_VIEW" ("WING", "UNITID", "MOCID", "SQUADRONNAME", "SORTIEDATE", "SORTIE", "SORTIEMOD", "GO", "BLOCKNUMBER", "AIRCRAFTYEAR", "TAILNUMBER", "AIRCRAFTMDS", "FLYABLE", "SPARE", "SCH_TO", "SCH_LND", "ACT_TO", "ACT_LND", "DURATIONHRS", "ADJ_TO", "ADJ_LND", "AREAARRIVE", "AREALEAVE", "CALLSIGN", "CONFIGCODE", "LANDING", "RANGE", "LINEDEV", "LINEDEVCAUSE", "WEATHER", "MISSION", "AREA", "PILOT", "LOCATIONCODE", "COLORVALUE", "ICONNAME", "STATUSCODE", "ROWCOLOR", "FUELSTATUS", "SCHEDDAY", "MAINTREMARKS", "REMARKS", "PUBLISHED", "LASTFLOWNTIME", "FUELLOAD", "TYPEEVENT", "SCHEDULESOURCE", "CHAFF", "FLARE", "TMEFLWNSINCEPHASE", "PHASEUNITS", "DEVIATION", "DEVCAUSE", "NEWDEVCAUSE", "DEVMOD", "DEVACTION", "CHARGEABLE", "DEVSTART", "DEVSTOP", "MAINTEVENT", "DEVRMKS") AS
SELECT
   WG.WINGNAME "WING",
   WG.UNITID "UNITID",
   MC.MOCID "MOCID",
   SQ.SQUADRONNAME,
   SC.SORTIEDATE "SORTIEDATE",
   SC.SORTIENUM "SORTIE",
   SC.SORTIEMOD "SORTIEMOD",
    SC.GO "GO",
   SC.BLOCKNUMBER "BLOCKNUMBER",
   AC.AIRCRAFTYEAR "AIRCRAFTYEAR",
   AC.SHORTTAILNUMBER "TAILNUMBER",
   MDS.AIRCRAFTMDS "AIRCRAFTMDS",
   DECODE(TO_CHAR(CS.FLYABLE), '1', 'Y', 'N') "FLYABLE",
   DECODE(TO_CHAR(SC.SPARE), '1', 'Y', 'N') "SPARE",
   SC.SCHEDULEDTAKEOFF "SCH_TO",
   SC.SCHEDULEDLANDING "SCH_LND",
   SC.ACTUALTAKEOFF "ACT_TO",
   SC.ACTUALLANDING "ACT_LND",
   TO_CHAR(((SC.ACTUALLANDING - SC.ACTUALTAKEOFF) * 24), '99999.99') "DURATIONHRS",
   SC.ADJTAKEOFF "ADJ_TO",
   SC.ADJLANDING "ADJ_LND",
   SC.AREAARRIVETIME "AREAARRIVE",
   SC.AREALEAVETIME "AREALEAVE",
   SC.CALLSIGN "CALLSIGN",
   SC.CONFIGCODE "CONFIGCODE",
   LC.LANDINGCODE "LANDING",
   RG.RANGE "RANGE",
   DC.DEVIATIONCODE "LINEDEV",
   CC.CAUSECODE "LINEDEVCAUSE",
   TO_CHAR(WX.WEATHERCODE) "WEATHER",
   MI.MISSION "MISSION",
   AR.AREA "AREA",
   PT.PILOTNAME "PILOT",
   LO.LOCATIONCODE "LOCATIONCODE",
   CO.COLORVALUE "COLORVALUE",        --ROW COLOR FOR CONDITIONSTATUS
   ST.ICONNAME "ICONNAME",
   ST.STATUSCODE "STATUSCODE",
   CO2.COLORVALUE "ROWCOLOR", --ROW COLOR FOR DEVIATIONS
   FU.FUELSTATUS "FUELSTATUS",
   SC.SCHEDDAY "SCHEDDAY",
   REM1.REMARKS "MAINTREMARKS",
   REM2.REMARKS "REMARKS",
   DECODE(TO_CHAR(SC.PUBLISHED_FLAG), '1', 'Y', 'N') "PUBLISHED",
   AC.LASTFLOWNTIME "LASTFLOWNTIME",
   AC.FUELLOAD "FUELLOAD",
   SC.TYPE_EVENT "TYPEEVENT",
   SC.SCHEDULESOURCE "SCHEDULESOURCE",
   AC.CHAFF "CHAFF",
   AC.FLARE "FLARE",
   AC.TMEFLOWNSINCEPHASEDATE "TMEFLWNSINCEPHASE",
   AC.PHASEUNITS,
   DCDEV.DEVIATIONCODE "DEVIATION",
   CCDEV.CAUSECODE "DEVCAUSE",
   CCDEV2.CAUSECODE "NEWDEVCAUSE",
   DEV.SORTIEMOD "DEVMOD",
   DEV.ACTIONOPTIONS "DEVACTION",
   DECODE(TO_CHAR(DEV.CHARGEABLE), '1', 'Y', 'N') "CHARGEABLE",
   DEV.STARTDATETIME "DEVSTART",
   DEV.STOPDATETIME "DEVSTOP",
   MAINTENANCEEVENTID "MAINTEVENT",
   REM3.REMARKS "DEVRMKS"
  FROM EMOC3.SCHEDULE SC
   LEFT JOIN EMOC3.AIRCRAFT AC ON SC.AIRCRAFTID = AC.AIRCRAFTID
   LEFT JOIN EMOC3.SQUADRONS SQ ON SC.SQUADRONID = SQ.SQUADRONID
   LEFT JOIN EMOC3.MOC MC ON MC.MOCID = SQ.MOCID
   LEFT JOIN EMOC3.SCHEDULEDEVIATIONS DEV ON SC.SCHEDULEID = DEV.SCHEDULEID
   LEFT JOIN EMOC3.LANDINGCODES LC ON SC.LANDINGCODEID = LC.LANDINGCODEID
   LEFT JOIN EMOC3.RANGES RG ON SC.RANGEID = RG.RANGEID
   LEFT JOIN EMOC3.DEVIATIONCODES DC ON SC.DEVIATIONCODEID = DC.DEVIATIONCODEID
   LEFT JOIN EMOC3.CAUSECODES CC ON SC.CAUSECODEID = CC.CAUSECODEID
   LEFT JOIN EMOC3.DEVIATIONCODES DCDEV ON DEV.DEVIATIONCODEID = DCDEV.DEVIATIONCODEID
   LEFT JOIN EMOC3.CAUSECODES CCDEV ON DEV.CAUSECODEID = CCDEV.CAUSECODEID
   LEFT JOIN EMOC3.CAUSECODES CCDEV2 ON DEV.NEWCAUSECODE = CCDEV2.CAUSECODEID
   LEFT JOIN EMOC3.REMARKS REM3 ON REM3.REMARKSID = DEV.DEVIATIONSREMARKS
   LEFT JOIN EMOC3.WX ON SC.WXCODEID = WX.WXCODEID
   LEFT JOIN EMOC3.MISSIONS MI ON SC.MISSIONID = MI.MISSIONID
   LEFT JOIN EMOC3.AREAS AR ON SC.AREAID = AR.AREAID
   LEFT JOIN EMOC3.PILOT PT ON SC.PILOTID = PT.PILOTID
   LEFT JOIN EMOC3.LOCATIONS LO ON AC.LOCATIONID = LO.LOCATIONID
   LEFT JOIN EMOC3.CONDITIONCODES CD ON AC.CONDITIONCODEID = CD.CONDCODEID
   LEFT JOIN EMOC3.CONDITIONSTATUS CS ON CD.CONDSTATID = CS.CONDSTATID
   LEFT JOIN EMOC3.COLORS CO ON CS.COLORID = CO.COLORID
   LEFT JOIN EMOC3.AIRCRAFTMDS MDS ON AC.AIRCRAFTMDSID = MDS.AIRCRAFTMDSID
   LEFT JOIN EMOC3.STATUSCODE ST ON AC.STATUSCODEID = ST.STATUSCODEID
   LEFT JOIN EMOC3.COLORS CO2 ON DC.COLORID = CO2.COLORID
   LEFT JOIN EMOC3.FUEL FU ON AC.FUELSTATUSID = FU.FUELSTATUSID
   LEFT JOIN EMOC3.REMARKS REM1 ON REM1.REMARKSID = MAINTREMARKS
   LEFT JOIN EMOC3.REMARKS REM2 ON REM2.REMARKSID = SCHEDULEREMARKS
   JOIN EMOC3.WINGS WG ON SQ.WINGID = WG.WINGID
 
 
 
 
 
 
 
 
@

CREATE OR REPLACE VIEW "EMOC3"."FLYBOARD_ARCHIVE_VIEW" ("SQUADRONNAME", "MOCID", "AIRCRAFTYEAR", "TAILNUMBER", "MISEQUIPID", "SERIALNUMBER", "AIRCRAFTMDS", "OTHERMDS", "SCH_GO", "SCH_SCHEDTAKEOFF", "SCH_SCHEDLAND", "SCH_ACTUALTAKEOFF", "SCH_ACTUALLAND", "SCH_SPARE", "SCH_ADJTAKEOFF", "SCH_ADJLANDING", "SCH_AREAARRIVETIME", "SCH_AREALEAVETIME", "SCH_LANDINGCODE", "SCH_RANGE", "SCH_DEVIATIONCODE", "SCH_CAUSECODE", "SCH_WEATHERCODE", "SCH_MISSION", "SCH_AREA", "SCH_PILOTNAME", "SCH_SORTIENUM", "SCH_SORTIEMOD", "SCH_SORTIEDATE", "SCH_BLOCKNUMBER", "SCH_PUBLISHEDFLAG", "SCH_SCHEDDAY", "SCH_CALLSIGN", "SCH_TRANSIENT", "SCH_DURATIONSCHEDULED", "SCH_DURATIONACTUAL", "SCH_CONFIGCODE", "SCH_SCHEDULEREMARKS", "SCH_MAINTREMARKS", "SCH_SORTIEJOAP", "SCH_SORTIESEMEDX", "SCH_SQUADRONNAME", "SCH_UTILIZATIONCODE", "SCH_SCHEDULESOURCE", "SCH_INTERFACELOGID", "SCH_ARCHIVEDATE", "SST_STATUSCODE", "SST_STATUSTIME", "SST_STATUSTYPE", "SST_ARCHIVEDATE", "DEV_DEVIATIONCODE", "DEV_CAUSECODE", "DEV_NEWCAUSECODE", "DEV_SORTIENUM", "DEV_SORTIEDATE", "DEV_SORTIEMOD", "DEV_ACTIONOPTIONS", "DEV_CHARGEABLE", "DEV_STARTDATETIME", "DEV_STOPDATETIME", "DEV_DEVIATIONREMARKS", "DEV_ARCHIVEDATE", "MNT_UNIT", "MNT_PCW", "MNT_EQUIPID", "MNT_CP", "MNT_WUCLCN", "MNT_WD", "MNT_PRIORITY", "MNT_SYMBOL", "MNT_TSSCH", "MNT_JOBDUR", "MNT_DISCREPANCY", "MNT_WCENARRATIVE", "MNT_EMPID", "MNT.ENTRY781", "MNT_DEFER", "MNT_WCESYMBOL", "MNT_JOBFOLLOW", "MNT_PARTSREQUIRED", "MNT_ENTERED", "MNT_ARCHIVEDATE", "JOAP", "JOAP_MOCCONTROLLER", "JOAP_SAMPLEDATE", "JOAP_REASON", "JOAP_HOURSREQUIRED", "JOAP_HOURSREMAINING", "JOAP_NOTIFIEDBY", "JOAP_EXPEDITERNOTIFIED", "JOAPLASTUPDATED", "JOAP_ARCHIVEDATE", "SEMEDX", "SEM_MOCCONTROLLER", "SEM_SAMPLEDATE", "SEM_REASON", "SEM_HOURSREQUIRED", "SEM_HOURSREMAINING", "SEM_NOTIFYBY", "SEM_EXPEDITERNOTIFIED", "SEMEDXLASTUPDATED", "SEM_ARCHIVEDATE") AS
SELECT
       AC.SQUADRONNAME,
     AC1.MOCID,
    AC.AIRCRAFTYEAR "AIRCRAFTYEAR",
       AC.SHORTTAILNUMBER "TAILNUMBER",
    AC.MISEQUIPID "MISEQUIPID",
       AC.SERIALNUMBER "SERIALNUMBER",
       AC.AIRCRAFTMDS "AIRCRAFTMDS",
    AC.RELATEDMDS "OTHERMDS",
    SCHEDULE.GO "SCH_GO",
    SCHEDULE.SCHEDULEDTAKEOFF "SCH_SCHEDTAKEOFF",
    SCHEDULE.SCHEDULEDLANDING "SCH_SCHEDLAND",
    SCHEDULE.ACTUALTAKEOFF "SCH_ACTUALTAKEOFF",
    SCHEDULE.ACTUALLANDING "SCH_ACTUALLAND",
    SCHEDULE.SPARE "SCH_SPARE",
    SCHEDULE.ADJTAKEOFF "SCH_ADJTAKEOFF",
    SCHEDULE.ADJLANDING "SCH_ADJLANDING",
    SCHEDULE.AREAARRIVETIME "SCH_AREAARRIVETIME",
    SCHEDULE.AREALEAVETIME "SCH_AREALEAVETIME",
    SCHEDULE.LANDINGCODE "SCH_LANDINGCODE",
    SCHEDULE.RANGE "SCH_RANGE",
    SCHEDULE.DEVIATIONCODE "SCH_DEVIATIONCODE",
    SCHEDULE.CAUSECODE "SCH_CAUSECODE",
    SCHEDULE.WEATHERCODE "SCH_WEATHERCODE",
    SCHEDULE.MISSION "SCH_MISSION",
    SCHEDULE.AREA "SCH_AREA",
    SCHEDULE.PILOTNAME "SCH_PILOTNAME",
    SCHEDULE.SORTIENUM "SCH_SORTIENUM",
    SCHEDULE.SORTIEMOD "SCH_SORTIEMOD",
    SCHEDULE.SORTIEDATE "SCH_SORTIEDATE",
    SCHEDULE.BLOCKNUMBER "SCH_BLOCKNUMBER",
    SCHEDULE.PUBLISHED_FLAG "SCH_PUBLISHEDFLAG",
    SCHEDULE.SCHEDDAY "SCH_SCHEDDAY",
    SCHEDULE.CALLSIGN "SCH_CALLSIGN",
    SCHEDULE.TRANSIENT "SCH_TRANSIENT",
    SCHEDULE.DURATIONSCHEDULED "SCH_DURATIONSCHEDULED",
    SCHEDULE.DURATIONACTUAL "SCH_DURATIONACTUAL",
    SCHEDULE.CONFIGCODE "SCH_CONFIGCODE",
    SCHEDULE.SCHEDULEREMARKS "SCH_SCHEDULEREMARKS",
    SCHEDULE.MAINTREMARKS "SCH_MAINTREMARKS",
    SCHEDULE.SORTIE_JOAP "SCH_SORTIEJOAP",
    SCHEDULE.SORTIE_SEMEDX "SCH_SORTIESEMEDX",
    SCHEDULE.SQUADRONNAME "SCH_SQUADRONNAME",
    SCHEDULE.UTILIZATIONCODE "SCH_UTILIZATIONCODE",
    SCHEDULE.SCHEDULESOURCE "SCH_SCHEDULESOURCE",
    SCHEDULE.INTERFACELOGID "SCH_INTERFACELOGID",
    SCHEDULE.ARCHIVEDATE "SCH_ARCHIVEDATE",
    SST.STATUSCODE "SST_STATUSCODE",
    SST.STATUSTIME "SST_STATUSTIME",
    SST.STATUSTYPE "SST_STATUSTYPE",
    SST.ARCHIVEDATE "SST_ARCHIVEDATE",
    DEV.DEVIATIONCODE "DEV_DEVIATIONCODE",
    DEV.CAUSECODE "DEV_CAUSECODE",
    DEV.NEWCAUSECODE "DEV_NEWCAUSECODE",
    DEV.SORTIENUM "DEV_SORTIENUM",
    DEV.SORTIEDATE "DEV_SORTIEDATE",
    DEV.SORTIEMOD "DEV_SORTIEMOD",
    DEV.ACTIONOPTIONS "DEV_ACTIONOPTIONS",
    DEV.CHARGEABLE "DEV_CHARGEABLE",
    DEV.STARTDATETIME "DEV_STARTDATETIME",
    DEV.STOPDATETIME "DEV_STOPDATETIME",
    DEV.DEVIATIONSREMARKS "DEV_DEVIATIONREMARKS",
    DEV.ARCHIVEDATE "DEV_ARCHIVEDATE",
    MNT.UNIT "MNT_UNIT",
    MNT.PWC "MNT_PCW",
    MNT.EQUIPID "MNT_EQUIPID",
    MNT.CP "MNT_CP",
    MNT.WUCLCN "MNT_WUCLCN",
    MNT.WD "MNT_WD",
    MNT.PRIORITY "MNT_PRIORITY",
    MNT.SYMBOL "MNT_SYMBOL",
    MNT.TSSCH "MNT_TSSCH",
    MNT.JOBDUR "MNT_JOBDUR",
    MNT.DISCREPANCY "MNT_DISCREPANCY",
    MNT.WCENARRATIVE "MNT_WCENARRATIVE",
    MNT.EMPID "MNT_EMPID",
    MNT.ENTRY781 "MNT.ENTRY781",
    MNT.DEFER "MNT_DEFER",
    MNT.WCESYMBOL "MNT_WCESYMBOL",
    MNT.JOBFOLLOW "MNT_JOBFOLLOW",
    MNT.PARTSREQUIRED "MNT_PARTSREQUIRED",
    MNT.ENTERED "MNT_ENTERED",
    MNT.ARCHIVEDATE "MNT_ARCHIVEDATE",
    JOAP.JOAP "JOAP",
    JOAP.MOCCONTROLLER "JOAP_MOCCONTROLLER",
    JOAP.SAMPLEDATE "JOAP_SAMPLEDATE",
    JOAP.REASON "JOAP_REASON",
    JOAP.HOURSREQUIRED "JOAP_HOURSREQUIRED",
    JOAP.HOURSREMAINING "JOAP_HOURSREMAINING",
    JOAP.NOTIFIEDBY "JOAP_NOTIFIEDBY",
    JOAP.EXPEDITERNOTIFIED "JOAP_EXPEDITERNOTIFIED",
    JOAP.JOAPLASTUPDATED "JOAPLASTUPDATED",
    JOAP.ARCHIVEDATE "JOAP_ARCHIVEDATE",
    SEM.SEMEDX "SEMEDX",
    SEM.MOCCONTROLLER "SEM_MOCCONTROLLER",
    SEM.SAMPLEDATE "SEM_SAMPLEDATE",
    SEM.REASON "SEM_REASON",
    SEM.HOURSREQUIRED "SEM_HOURSREQUIRED",
    SEM.HOURSREMAINING "SEM_HOURSREMAINING",
    SEM.NOTIFIEDBY "SEM_NOTIFYBY",
    SEM.EXPEDITERNOTIFIED "SEM_EXPEDITERNOTIFIED",
    SEM.SEMEDXLASTUPDATED "SEMEDXLASTUPDATED",
    SEM.ARCHIVEDATE "SEM_ARCHIVEDATE"
FROM EMOCAUX.SCHEDULE
LEFT JOIN EMOCAUX.AIRCRAFT AC ON AC.AIRCRAFTID = SCHEDULE.AIRCRAFTID
LEFT JOIN EMOC3.AIRCRAFT AC1 ON AC1.AIRCRAFTID = AC.AIRCRAFTID
LEFT JOIN EMOCAUX.SCHEDULESTATUS SST ON SST.SCHEDULEID = SCHEDULE.SCHEDULEID
LEFT JOIN EMOCAUX.SCHEDULEDEVIATIONS DEV ON DEV.SCHEDULEID = SCHEDULE.SCHEDULEID
LEFT JOIN EMOCAUX.MAINTENANCEEVENTS MNT ON MNT.MAINTENANCEEVENTID = DEV.MAINTENANCEEVENTID
LEFT JOIN EMOCAUX.JOAPDATA JOAP ON JOAP.SCHEDULEID = SCHEDULE.SCHEDULEID
LEFT JOIN EMOCAUX.SEMEDXDATA SEM ON SEM.SCHEDULEID = SCHEDULE.SCHEDULEID
 
 
 
 
 
 
 
 
@

CREATE OR REPLACE VIEW "EMOC3"."FLIGHTSVIEW" ("FLIGHTID", "FLIGHTNAME", "SQUADRONID", "WORKCENTERID", "SHORTNAME", "WORKCENTERCODE", "MOCID") AS
SELECT   flightid, flightname, squadrons.squadronid,
   workcenters.workcenterid, shortname, workcentercode, squadrons.mocid
FROM emoc3.flights JOIN emoc3.squadrons ON flights.squadronid = squadrons.squadronid
JOIN emoc3.workcenters ON flights.workcenterid = workcenters.workcenterid
ORDER BY flightname
/* *** DCW Evaluation Issue "DDL_VIEW_ORDER_BY".Corresponding line no in the source file:10915 *** */
@

CREATE OR REPLACE VIEW "EMOC3"."DEVIATIONCODEVIEW" ("DEVIATIONCODEID", "DEVIATIONCODE", "DEVIATIONDESCRIPTION", "COLORVALUE", "DEVAULTDEVIATIONCODE", "MOCID") AS
SELECT   deviationcodeid, deviationcode, deviationdescription,
         colorvalue, defaultdeviationcode, deviationcodes.mocid
FROM deviationcodes LEFT JOIN colors ON deviationcodes.colorid = colors.colorid
ORDER BY deviationcode
/* *** DCW Evaluation Issue "DDL_VIEW_ORDER_BY".Corresponding line no in the source file:10921 *** */
 
 
 
 
 
 
 
 
@

CREATE OR REPLACE VIEW "EMOC3"."CUSTOM_DATA_VIEW" ("WING", "UNITID", "ELC", "SQUADRONNAME", "MOCID", "AIRCRAFTYEAR", "TAILNUMBER", "MISEQUIPID", "SERIALNUMBER", "AIRCRAFTMDS", "OTHERMDS", "MDSLASTUPDATED", "CONDITION", "CONDSTATUS", "STATUSCODE", "AIRCRAFTWUC", "LABEL", "DESCRIPTION", "VALUE", "NUMBERVALUE", "DATEVALUE", "BOOLEANVALUE", "UPDATED", "UPDATEBY") AS
SELECT WINGS.wingname "WING",
    WINGS.UNITID "UNITID",
    WINGS.ELC "ELC",
       SQUADRONS.squadronname,
Aircraft.mocid,
    AIRCRAFT.aircraftyear "AIRCRAFTYEAR",
       AIRCRAFT.shorttailnumber "TAILNUMBER",
    AIRCRAFT.misequipid "MISEQUIPID",
       AIRCRAFT.serialnumber "SERIALNUMBER",
       AIRCRAFTMDS.AIRCRAFTMDS "AIRCRAFTMDS",
    AIRCRAFT.RELATEDMDS "OTHERMDS",
    AIRCRAFT.MDSLASTUPDATED,
       CONDITIONCODES.conditioncode "CONDITION",
    CONDITIONSTATUS.CONDITIONSTATUS "CONDSTATUS",
    STATUSCODE.STATUSCODE,
    WUC.WUCCODE "AIRCRAFTWUC",
    CUSTOMDATALABEL "LABEL",
    CUSTOMDATADESCRIPTION "DESCRIPTION",
    DATAVALUE "VALUE",
    EMOC3.GET_CUSTOMDATA_NUMBER(DATAVALUE) "NUMBERVALUE",
    EMOC3.GET_CUSTOMDATA_DATE(DATAVALUE) "DATEVALUE",
    EMOC3.GET_CUSTOMDATA_BOOLEAN(DATAVALUE) "BOOLEANVALUE",
    LASTUPDATED "UPDATED",
    USERNAME "UPDATEBY"
FROM EMOC3.AIRCRAFT
JOIN EMOC3.AIRCRAFTMDS ON AIRCRAFTMDS.AIRCRAFTMDSID = AIRCRAFT.AIRCRAFTMDSID
JOIN EMOC3.SQUADRONS ON AIRCRAFT.SQUADRONID = SQUADRONS.SQUADRONID
JOIN EMOC3.WINGS ON SQUADRONS.WINGID = WINGS.WINGID
LEFT JOIN EMOC3.AIRCRAFTCUSTOMDATA ON AIRCRAFT.AIRCRAFTID = AIRCRAFTCUSTOMDATA.AIRCRAFTID
LEFT JOIN EMOC3.CUSTOMDATA ON CUSTOMDATA.CUSTOMDATAID = AIRCRAFTCUSTOMDATA.CUSTOMDATAID
JOIN EMOC3.USERS ON USERS.USERID = AIRCRAFTCUSTOMDATA.LASTUPDATEBY
LEFT JOIN EMOC3.CONDITIONCODES ON AIRCRAFT.CONDITIONCODEID = CONDITIONCODES.CONDCODEID
LEFT JOIN EMOC3.CONDITIONSTATUS ON CONDITIONCODES.CONDSTATID = CONDITIONSTATUS.CONDSTATID
LEFT JOIN EMOC3.WUC ON AIRCRAFT.AIRCRAFTWUCID = WUC.WUCID
LEFT JOIN EMOC3.STATUSCODE ON AIRCRAFT.STATUSCODEID = STATUSCODE.STATUSCODEID
WHERE AIRCRAFT.AIRCRAFTID IN (SELECT DISTINCT aircraftid FROM aircraftcustomdata) AND customdata.customdataid IN (SELECT DISTINCT customdataid FROM aircraftcustomdata)
 
 
 
 
 
 
 
 
@

CREATE OR REPLACE VIEW "EMOC3"."BRIEF_WING_STATUS_VIEW" ("WING", "WINGID", "SQUADRON", "SQUADRONID", "AIRCRAFTID", "TAILNUMBER", "MDS", "STATUSCODE", "POSSESSIONCODE", "MOCID") AS
SELECT WI.wingname AS wing,
    WI.WINGID AS wingid,
    SQ.shortname AS squadron,
    SQ.SQUADRONID AS squadronid,
    AC.AIRCRAFTID AS aircraftid,
    AC.SHORTTAILNUMBER AS tailnumber,
    AM.AIRCRAFTMDS AS mds,
    CC.CONDITIONCODE AS statuscode,
    SUBSTR(PO.POSSESSIONCODE,1,1) AS possessioncode,
 sq.mocid AS mocid
FROM AIRCRAFT AC
LEFT JOIN SQUADRONS SQ ON AC.SQUADRONID = SQ.SQUADRONID
LEFT JOIN WINGS WI ON WI.WINGID = SQ.WINGID
LEFT JOIN CONDITIONCODES CC ON AC.CONDITIONCODEID = CC.CONDCODEID
LEFT JOIN AIRCRAFTMDS AM ON AC.AIRCRAFTMDSID = AM.AIRCRAFTMDSID
LEFT JOIN POSSESSIONS PO ON PO.POSSESSIONID = AC.POSSESSIONID
 
 
 
 
 
 
 
 
@

CREATE OR REPLACE VIEW "EMOC3"."AIRCRAFT_STATUSUPDATE_VIEW" ("WING", "UNITID", "ELC", "SQUADRONNAME", "MOCID", "AIRCRAFTYEAR", "TAILNUMBER", "MISEQUIPID", "SERIALNUMBER", "AIRCRAFTMDS", "OTHERMDS", "MAINTSTATUSCODE", "CONDITIONSTATCODE", "STATUSSTARTDATE", "STATUSSTARTTIME", "WORKUNITCODE", "OPENSTATUSEVENT", "ETIC", "PARTSPLUS", "STATUSNARRATIVE", "LOCATION", "CONFIGURATION", "PRIORITY", "ARM", "MULTIPLECONFIGID", "LOCALOPTION", "ENTERED", "LASTUPDATE", "ENTEREDBY", "UPDATEDBY") AS
SELECT WINGS.wingname "WING",
    WINGS.UNITID "UNITID",
    WINGS.ELC "ELC",
       SQUADRONS.squadronname,
AIRCRAFT.MOCID,
    AIRCRAFT.aircraftyear "AIRCRAFTYEAR",
       AIRCRAFT.shorttailnumber "TAILNUMBER",
    AIRCRAFT.misequipid "MISEQUIPID",
       AIRCRAFT.serialnumber "SERIALNUMBER",
       AIRCRAFTMDS.AIRCRAFTMDS "AIRCRAFTMDS",
    AIRCRAFT.RELATEDMDS "OTHERMDS",
    AIRCRAFTSTATUSUPDATE.maintenancestatuscode "MAINTSTATUSCODE",
    AIRCRAFTSTATUSUPDATE.conditionstatuscode "CONDITIONSTATCODE",
       AIRCRAFTSTATUSUPDATE.statusstartdate,
    AIRCRAFTSTATUSUPDATE.statusstarttime,
    AIRCRAFTSTATUSUPDATE.workunitcode,
       AIRCRAFTSTATUSUPDATE.openstatusevent,
    AIRCRAFTSTATUSUPDATE.estimatedtimeincommission "ETIC",
    AIRCRAFTSTATUSUPDATE.partsplus,
       AIRCRAFTSTATUSUPDATE.statusnarrative,
    AIRCRAFTSTATUSUPDATE.LOCATION,
    AIRCRAFTSTATUSUPDATE.configuration,
    AIRCRAFTSTATUSUPDATE.priority,
       AIRCRAFTSTATUSUPDATE.arm,
    AIRCRAFTSTATUSUPDATE.multipleconfigid,
    AIRCRAFTSTATUSUPDATE.localoption,
    AIRCRAFTSTATUSUPDATE.entered,
       AIRCRAFTSTATUSUPDATE.lastupdate,
    AIRCRAFTSTATUSUPDATE.enteredby,
    AIRCRAFTSTATUSUPDATE.updatedby
       FROM EMOC3.AIRCRAFT,
          EMOC3.SQUADRONS,
          EMOC3.AIRCRAFTMDS,
    EMOC3.WINGS,
    EMOC3.AIRCRAFTSTATUSUPDATE
    WHERE (    (AIRCRAFT.squadronid = SQUADRONS.squadronid)
           AND (WINGS.wingid = SQUADRONS.wingid)
           AND (AIRCRAFTMDS.aircraftmdsid = AIRCRAFT.aircraftmdsid(+))
           AND (AIRCRAFT.aircraftid = AIRCRAFTSTATUSUPDATE.aircraftid)
          )
 
 
 
 
 
 
 
 
@

CREATE OR REPLACE VIEW "EMOC3"."AIRCRAFT_STATUSBOARD_VIEW" ("WING", "UNITID", "ELC", "SQUADRONNAME", "MOCID", "AIRCRAFTYEAR", "TAILNUMBER", "MISEQUIPID", "SERIALNUMBER", "AIRCRAFTMDS", "OTHERMDS", "MDSLASTUPDATED", "CONDCODE", "CONDUPD", "CONDTIME", "CONDSTATUS", "STATUSCODE", "STATUSUPDATED", "STATUSCODETIME", "STATUSNARRATIVE", "STATUSSTARTDATE", "STATUSSTARTTIME", "STATUSWUCLCN", "ETIC", "ETICDATE", "ETICUPDATED", "AIRCRAFTWUC", "WUCLASTUPDATED", "OPENSTATEVENTJCN", "FCF", "OCF", "QVI", "HOTGUNS", "ARM_DEARM", "FIRESYMBOL", "FUELLOAD", "FUELSTATUS", "FUELSTATUSLASTUPD", "FUELSTATUSTIME", "CREWCHIEF", "RANKCODE", "FIRSTOFFICIAL", "SECONDOFFICIAL", "PRIORITY", "HQCODE", "LASTFLOWNTIME", "PICTURE", "PHASEDATE", "PHASEDATELASTUPD", "TMEFLWNSINCEPHASE", "PHASEUNITS", "MULTICONFIGID", "ACFT_CONFIG_ID", "LOCALCONFIGID", "LOCALOPTION", "LOCCODE", "LOCLASTUPDATED", "STATIONLOC", "CONFIGDATE", "CONFIGUPDATED", "CREWCHIEFLASTUPD", "SERIALNUMLASTUPD", "IMPOUNDSLASTUPD", "HQSTATUSLASTUPD", "TESTSTATUSLASTUPD", "REMARKSLASTUPD", "PRIORITYLASTUPD", "ASSIGNCMD", "ASSIGNSTATUS", "ASSIGNDATE", "ASSIGNUPDATED", "POSSESSION", "POSSDATETIME", "POSSCODELASTUPD", "REPDESIGNDATETIME", "REPDESIGNLASTUPD", "REPORTDESIG", "SQPRESELECT", "WEAPONSTATLASTUPD", "WEAPONSSTATUSTIME", "AIRCRAFTREMARKS") AS
SELECT WINGS.wingname "WING",
    WINGS.UNITID "UNITID",
    WINGS.ELC "ELC",
       SQUADRONS.squadronname,
AIRCRAFT.mocid,
    AIRCRAFT.aircraftyear "AIRCRAFTYEAR",
       AIRCRAFT.shorttailnumber "TAILNUMBER",
    AIRCRAFT.misequipid "MISEQUIPID",
       AIRCRAFT.serialnumber "SERIALNUMBER",
       AIRCRAFTMDS.AIRCRAFTMDS "AIRCRAFTMDS",
    AIRCRAFT.RELATEDMDS "OTHERMDS",
    AIRCRAFT.MDSLASTUPDATED,
       CONDITIONCODES.conditioncode "CONDCODE",
    AIRCRAFT.CONDITIONCODELASTUPDATED "CONDUPD",
    AIRCRAFT.CONDITIONCODETIME "CONDTIME",
    CONDITIONSTATUS.CONDITIONSTATUS "CONDSTATUS",
    STATUSCODE.STATUSCODE,
    AIRCRAFT.STATUSCODELASTUPDATED "STATUSUPDATED",
    AIRCRAFT.STATUSCODETIME,
    AIRCRAFT.STATUSNARRATIVE,
    AIRCRAFT.STATUSSTARTDATE,
    AIRCRAFT.STATUSSTARTTIME,
    AIRCRAFT.STATUSWUCLCN,
    AIRCRAFT.etic "ETIC",
    AIRCRAFT.eticdatetime "ETICDATE",
    AIRCRAFT.eticlastupdated "ETICUPDATED",
    WUC.WUCCODE "AIRCRAFTWUC",
    AIRCRAFT.WUCLASTUPDATED,
    AIRCRAFT.OPENSTATUSEVENTJCN "OPENSTATEVENTJCN",
    DECODE(TO_CHAR(FCF), '1', 'Y', 'N') FCF,
    DECODE(TO_CHAR(OCF), '1', 'Y', 'N') OCF,
    DECODE(TO_CHAR(QVI), '1', 'Y', 'N') QVI,
    DECODE(TO_CHAR(AIRCRAFT.hotguns), '1', 'Y', 'N') hotguns,
    DECODE(TO_CHAR(AIRCRAFT.arm_dearm), '1', 'Y', 'N') arm_dearm,
    FIRESYMBOLS.FIRESYMBOL,
    AIRCRAFT.FUELLOAD,
       FUEL.FUELSTATUS,
    AIRCRAFT.FUELSTATUSLASTUPDATED "FUELSTATUSLASTUPD",
       AIRCRAFT.FUELSTATUSTIME,
    CREWCHIEFS.crewchief "CREWCHIEF",
    RANKS.rankcode "RANKCODE",
    AIRCRAFT.firstofficial "FIRSTOFFICIAL",
       AIRCRAFT.secondofficial "SECONDOFFICIAL",
    TO_CHAR(AIRCRAFT.priority) "PRIORITY",
       HANGER_QUEEN_CODE.hqcode "HQCODE",
       AIRCRAFT.lastflowntime "LASTFLOWNTIME",
    CREWCHIEFS.picture "PICTURE",
    AIRCRAFT.phasedate "PHASEDATE",
       AIRCRAFT.phasedatelastupdated "PHASEDATELASTUPD",
    AIRCRAFT.TMEFLOWNSINCEPHASEDATE "TMEFLWNSINCEPHASE",
    AIRCRAFT.PHASEUNITS,
    AIRCRAFT.MULTICONFIGID,
    AIRCRAFT.ACFT_CONFIG_ID,
    AIRCRAFT.LOCALCONFIGID,
    AIRCRAFT.LOCALOPTION,
    LOCATIONS.LOCATIONCODE "LOCCODE",
    AIRCRAFT.LOCATIONLASTUPDATED "LOCLASTUPDATED",
    STATIONLOCCODES.STATIONLOC,
    AIRCRAFT.AIRCONFIGDATETIME "CONFIGDATE",
    AIRCRAFT.AIRCONFIGIDLASTUPDATED "CONFIGUPDATED",
       AIRCRAFT.crewchieflastupdated "CREWCHIEFLASTUPD",
    AIRCRAFT.serialnumberlastupdated "SERIALNUMLASTUPD",
       AIRCRAFT.impoundslastupdated "IMPOUNDSLASTUPD",
       AIRCRAFT.hqstatuslastupdated "HQSTATUSLASTUPD",
    AIRCRAFT.teststatuslastupdated "TESTSTATUSLASTUPD",
    AIRCRAFT.remarkslastupdated "REMARKSLASTUPD",
    AIRCRAFT.prioritylastupdated "PRIORITYLASTUPD",
    AIRCRAFT.ASSIGNMENTCMD "ASSIGNCMD",
    AIRCRAFT.ASSIGNMENTSTATUS "ASSIGNSTATUS",
    AIRCRAFT.ASSIGNSTATDATETIME "ASSIGNDATE",
    AIRCRAFT.ASSIGNSTATUSLASTUPDATED "ASSIGNUPDATED",
       POSSESSIONS.POSSESSIONCODE "POSSESSION",
    AIRCRAFT.POSSDATETIME,
    AIRCRAFT.POSSESSIONCODELASTUPDATED "POSSCODELASTUPD",
    AIRCRAFT.REPDESIGNDATETIME,
    AIRCRAFT.REPDESIGNLASTUPDATED "REPDESIGNLASTUPD",
       AIRCRAFT.REPORTDESIG,
    AIRCRAFT.SQPRESELECT,
    AIRCRAFT.WEAPONSSTATUSLASTUPDATED "WEAPONSTATLASTUPD",
    AIRCRAFT.WEAPONSSTATUSTIME,
    REMARKS.REMARKS "AIRCRAFTREMARKS"
     FROM AIRCRAFT,
          CREWCHIEFS,
          SQUADRONS,
          CONDITIONCODES,
          CONDITIONSTATUS,
          HANGER_QUEEN_CODE,
          POSSESSIONS,
          RANKS,
          AIRCRAFTMDS,
          WUC,
          FIRESYMBOLS,
          FUEL,
          LOCATIONS,
          STATIONLOCCODES,
          STATUSCODE,
          WINGS,
          REMARKS
    WHERE (    (AIRCRAFT.crewchiefid = CREWCHIEFS.crewchiefid(+))
           AND (AIRCRAFT.squadronid = SQUADRONS.squadronid)
           AND (WINGS.wingid = SQUADRONS.wingid)
           AND (AIRCRAFT.conditioncodeid = CONDITIONCODES.condcodeid(+))
     AND (CONDITIONCODES.CONDSTATID = CONDITIONSTATUS.CONDSTATID(+))
           AND (AIRCRAFT.hangerqueenstatus = HANGER_QUEEN_CODE.hqcodeid(+))
           AND (AIRCRAFT.possessionid = POSSESSIONS.possessionid(+))
           AND (RANKS.rankid(+) = CREWCHIEFS.rankid)
           AND (AIRCRAFTMDS.aircraftmdsid = AIRCRAFT.aircraftmdsid(+))
           AND (AIRCRAFT.AIRCRAFTWUCID = WUC.WUCID(+))
     AND (AIRCRAFT.firesymbolid = FIRESYMBOLS.FIRESYMBOLID(+))
     AND (AIRCRAFT.fuelstatusid = FUEL.FUELSTATUSID(+))
     AND (AIRCRAFT.locationid = LOCATIONS.LOCATIONID(+))
     AND (AIRCRAFT.STALOCCODEID = STATIONLOCCODES.STALOCCODEID(+))
     AND (AIRCRAFT.STATUSCODEID = STATUSCODE.STATUSCODEID(+))
     AND (AIRCRAFT.remarksid = REMARKS.REMARKSID(+))
          )
 
 
 
 
 
 
 
 
@

CREATE OR REPLACE VIEW "EMOC3"."AIRCRAFT_ENGINE_DATA_VIEW" ("WING", "UNITID", "ELC", "SQUADRONNAME", "MOCID", "AIRCRAFTYEAR", "TAILNUMBER", "MISEQUIPID", "SERIALNUMBER", "AIRCRAFTMDS", "ENGINENUMBER", "ENGHRSFLOWN", "AIRCRAFTREMARKS") AS
SELECT
       WINGS.wingname "WING",
    WINGS.UNITID "UNITID",
    WINGS.ELC "ELC",
       SQUADRONS.squadronname,
AIRCRAFT.MOCID,
    AIRCRAFT.aircraftyear "AIRCRAFTYEAR",
       AIRCRAFT.shorttailnumber "TAILNUMBER",
    AIRCRAFT.misequipid "MISEQUIPID",
       AIRCRAFT.serialnumber "SERIALNUMBER",
       AIRCRAFTMDS.AIRCRAFTMDS "AIRCRAFTMDS",
    TO_CHAR(AIRCRAFTENGINEDATA.enginenumber) enginenumber,
    TO_NUMBER(TO_CHAR(SUM((SCHEDULE.ACTUALLANDING - SCHEDULE.ACTUALTAKEOFF) * 24), '99999.99')) "ENGHRSFLOWN",
    REMARKS.REMARKS "AIRCRAFTREMARKS"
FROM EMOC3.AIRCRAFT, EMOC3.WINGS, EMOC3.SQUADRONS, EMOC3.AIRCRAFTMDS, EMOC3.AIRCRAFTENGINEDATA, EMOC3.SCHEDULE, EMOC3.REMARKS
WHERE (    (AIRCRAFT.aircraftid = AIRCRAFTENGINEDATA.aircraftid)
        AND (AIRCRAFT.squadronid = SQUADRONS.SQUADRONID)
        AND (SQUADRONS.wingid = WINGS.wingid)
        AND (AIRCRAFT.aircraftmdsid = AIRCRAFTMDS.aircraftmdsid)
  AND (SCHEDULE.AIRCRAFTID = AIRCRAFT.AIRCRAFTID(+))
  AND (AIRCRAFT.remarksid = REMARKS.REMARKSID(+))
   )
GROUP BY
       WINGS.wingname,
    WINGS.UNITID,
    WINGS.ELC,
AIRCRAFT.MOCID,
       SQUADRONS.squadronname,
    AIRCRAFT.aircraftyear,
       AIRCRAFT.shorttailnumber,
    AIRCRAFT.misequipid,
       AIRCRAFT.serialnumber,
       AIRCRAFTMDS.AIRCRAFTMDS,
    AIRCRAFTENGINEDATA.enginenumber,
    REMARKS.REMARKS
ORDER BY AIRCRAFT.shorttailnumber, AIRCRAFTENGINEDATA.enginenumber
/* *** DCW Evaluation Issue "DDL_VIEW_ORDER_BY".Corresponding line no in the source file:11214 *** */
 
 
 
 
 
 
 
 
@

CREATE OR REPLACE VIEW "EMOC3"."ALL_AIRCRAFT_DATA_VIEW" ("WING", "UNITID", "ELC", "MOCID", "SQUADRONNAME", "AIRCRAFTYEAR", "TAILNUMBER", "MISEQUIPID", "SERIALNUMBER", "AIRCRAFTMDS", "OTHERMDS", "MDSLASTUPDATED", "CONDCODE", "CONDUPD", "CONDTIME", "CONDSTATUS", "STATUSCODE", "STATUSUPDATED", "STATUSCODETIME", "CURRENTSTAUSTNARR", "CURRENTSTATSTART", "STATUSWUCLCN", "CURRENTETIC", "ETICDATE", "ETICUPDATED", "AIRCRAFTWUC", "WUCLASTUPDATED", "OPENSTATEVENTJCN", "FCF", "OCF", "QVI", "HOTGUNS", "ARM_DEARM", "FIRESYMBOL", "FUELLOAD", "FUELSTATUS", "FUELSTATUSLASTUPD", "FUELSTATUSTIME", "CREWCHIEF", "RANKCODE", "FIRSTOFFICIAL", "SECONDOFFICIAL", "CURRENTPRIORITY", "HQCODE", "LASTFLOWNTIME", "PICTURE", "PHASEDATE", "PHASEDATELASTUPD", "TMEFLWNSINCEPHASE", "PHASEUNITS", "MULTICONFIGID", "ACFT_CONFIG_ID", "LOCALCONFIGID", "CURRENTLOCOPTION", "LOCCODE", "LOCLASTUPDATED", "STATIONLOC", "CONFIGDATE", "CONFIGUPDATED", "CREWCHIEFLASTUPD", "SERIALNUMLASTUPD", "IMPOUNDSLASTUPD", "HQSTATUSLASTUPD", "TESTSTATUSLASTUPD", "REMARKSLASTUPD", "PRIORITYLASTUPD", "ASSIGNCMD", "ASSIGNSTATUS", "ASSIGNDATE", "ASSIGNUPDATED", "POSSESSION", "POSSDATETIME", "POSSCODELASTUPD", "REPDESIGNDATETIME", "REPDESIGNLASTUPD", "REPORTDESIG", "SQPRESELECT", "WEAPONSTATLASTUPD", "WEAPONSSTATUSTIME", "COMBATSCL", "WEAPONSNUMBER", "WEAPONTYPE", "ORDNANCE", "WEAPONS_CONFIG", "ENGINENUMBER", "ENGHRSFLOWN", "MAINTSTATUSCODE", "CONDITIONSTATCODE", "STATUSSTARTDATE", "STATUSCHANGEWUC", "OPENSTATUSEVENT", "STATUSETIC", "PARTSPLUS", "STATUSNARRATIVE", "LOCATION", "CONFIGURATION", "PRIORITY", "ARM", "MULTIPLECONFIGID", "LOCALOPTION", "ENTERED", "LASTUPDATE", "ENTEREDBY", "UPDATEDBY", "WRITEUPTIME", "WRITEUPJCN", "WRITEUPCORRECTED", "CORRECTEDTIME", "WRITEUPPACER", "WRITEUPETIC", "WRITEUPSYMBOL", "WRITEUPWUC", "WRITEUPDISCREPANCY", "CORRECTIVEACTION", "WRITEUPCAMSINIT", "MICAPDOCNUMBER", "MICAPPART", "MICAPETA", "MICAPCAMSINIT", "JOAP_ENGINENUM", "JOAP_SORTIEDATE", "JOAP_SORTIENUM", "JOAPCODE", "REDCAPSTATUS", "JOAP_COLOR", "JOAP_COLORRANK", "JOAP_SAMPLEDATE", "JOAP_REASON", "JOAP_NOTIFIEDBY", "JOAP_MOCCONTROLLER", "JOAPLASTUPDATED", "JOAP_HRSREQUIRED", "JOAP_HRSREMAINING", "JOAP_EXPEDITED", "SEM_ENGINENUM", "SEM_SORTIEDATE", "SEM_SORTIENUM", "SEMEDXCODE", "SEM_COLOR", "SEM_COLORRANK", "SEM_SAMPLEDATE", "SEM_REASON", "SEM_NOTIFIEDBY", "SEM_MOCCONTROLLER", "SEMEDXLASTUPDATED", "SEM_HRSREQUIRED", "SEM_HRSREMAINING", "SEM_EXPEDITED") AS
SELECT
--STATUS BOARD VIEW--
 STB.WING,
 STB.UNITID,
 STB.ELC,
STB.MOCID,
 STB.SQUADRONNAME,
 STB.AIRCRAFTYEAR,
 STB.TAILNUMBER,
 STB.MISEQUIPID,
 STB.SERIALNUMBER,
 STB.AIRCRAFTMDS,
 STB.OTHERMDS,
 STB.MDSLASTUPDATED,
 STB.CONDCODE,
 STB.CONDUPD,
 STB.CONDTIME,
 STB.CONDSTATUS,
 STB.STATUSCODE,
 STB.STATUSUPDATED,
 STB.STATUSCODETIME,
 STB.STATUSNARRATIVE "CURRENTSTAUSTNARR",
 STB.STATUSSTARTDATE || ' ' || STB.STATUSSTARTTIME "CURRENTSTATSTART",
 STB.STATUSWUCLCN,
 STB.ETIC "CURRENTETIC",
 STB.ETICDATE,
 STB.ETICUPDATED,
 STB.AIRCRAFTWUC,
 STB.WUCLASTUPDATED,
 STB.OPENSTATEVENTJCN,
 STB.FCF, STB.OCF, STB.QVI,
 STB.HOTGUNS, STB.ARM_DEARM, STB.FIRESYMBOL,
 STB.FUELLOAD,
 STB.FUELSTATUS,
 STB.FUELSTATUSLASTUPD,
 STB.FUELSTATUSTIME,
 STB.CREWCHIEF,
 STB.RANKCODE,
 STB.FIRSTOFFICIAL, STB.SECONDOFFICIAL,
 STB.PRIORITY "CURRENTPRIORITY",
 STB.HQCODE,
 STB.LASTFLOWNTIME,
 STB.PICTURE,
 STB.PHASEDATE,
 STB.PHASEDATELASTUPD,
 STB.TMEFLWNSINCEPHASE,
 STB.PHASEUNITS,
 STB.MULTICONFIGID,
 STB.ACFT_CONFIG_ID,
 STB.LOCALCONFIGID,
 STB.LOCALOPTION "CURRENTLOCOPTION",
 STB.LOCCODE,
 STB.LOCLASTUPDATED,
 STB.STATIONLOC,
 STB.CONFIGDATE,
 STB.CONFIGUPDATED,
 STB.CREWCHIEFLASTUPD,
 STB.SERIALNUMLASTUPD,
 STB.IMPOUNDSLASTUPD,
 STB.HQSTATUSLASTUPD,
 STB.TESTSTATUSLASTUPD,
 STB.REMARKSLASTUPD,
 STB.PRIORITYLASTUPD,
 STB.ASSIGNCMD,
 STB.ASSIGNSTATUS,
 STB.ASSIGNDATE,
 STB.ASSIGNUPDATED,
 STB.POSSESSION,
 STB.POSSDATETIME,
 STB.POSSCODELASTUPD,
 STB.REPDESIGNDATETIME,
 STB.REPDESIGNLASTUPD,
 STB.REPORTDESIG,
 STB.SQPRESELECT,
 STB.WEAPONSTATLASTUPD,
 STB.WEAPONSSTATUSTIME,
--WEAPONS VIEW--
 COMBATSCL,
 WEAPONSNUMBER,
 WEAPONTYPE,
 ORDNANCE,
 WPN.CONFIGURATION "WEAPONS_CONFIG",
--ENGINE DATA VIEW--
 ENG.ENGINENUMBER,
 ENG.ENGHRSFLOWN,
--STATUS UPDATE VIEW--
 STU.MAINTSTATUSCODE,
 STU.CONDITIONSTATCODE,
 STU.STATUSSTARTDATE || ' ' || STU.STATUSSTARTTIME "STATUSSTARTDATE",
 WORKUNITCODE "STATUSCHANGEWUC",
 OPENSTATUSEVENT,
 STU.ETIC "STATUSETIC",
 PARTSPLUS,
 STU.STATUSNARRATIVE,
 LOCATION,
 STU.CONFIGURATION,
 STU.PRIORITY, ARM,
 MULTIPLECONFIGID,
 STU.LOCALOPTION,
 ENTERED,
 LASTUPDATE,
 ENTEREDBY,
 UPDATEDBY,
 --WRITEUPS AND MICAPS VIEW
 WRITEUPTIME,
 WRITEUPJCN,
 CORRECTED WRITEUPCORRECTED,
 CORRECTEDTIME,
 PACER WRITEUPPACER,
 WRITEUPETIC,
 SYMBOL WRITEUPSYMBOL,
 WRITEUPWUC,
 DISCREPANCY WRITEUPDISCREPANCY,
 CORRECTIVEACTION,
 WRITEUPCAMSINIT,
 DOCUMENTNUMBER MICAPDOCNUMBER,
 PART MICAPPART,
 ETA MICAPETA,
 MICAPCAMSINIT,
--JOAP VIEW--
 JP.ENGINENUMBER "JOAP_ENGINENUM",
 JP.SORTIEDATE "JOAP_SORTIEDATE",
 JP.SORTIENUM "JOAP_SORTIENUM",
 JP.JOAPCODE, JP.REDCAPSTATUS,
 JP.COLORNAME "JOAP_COLOR",
 JP.COLORRANK "JOAP_COLORRANK",
 JP.SAMPLEDATE "JOAP_SAMPLEDATE",
 JP.REASON "JOAP_REASON",
 JP.NOTIFIEDBY "JOAP_NOTIFIEDBY",
 JP.MOCCONTROLLER "JOAP_MOCCONTROLLER",
 JP.JOAPLASTUPDATED,
 JP.HOURSREQUIRED "JOAP_HRSREQUIRED",
 JP.HOURSREMAINING "JOAP_HRSREMAINING",
 JP.EXPEDITED "JOAP_EXPEDITED",
--SEMEDX VIEW--
 SEM.ENGINENUMBER "SEM_ENGINENUM",
 SEM.SORTIEDATE "SEM_SORTIEDATE",
 SEM.SORTIENUM "SEM_SORTIENUM",
 SEM.CODE "SEMEDXCODE",
 SEM.COLORNAME "SEM_COLOR",
 SEM.COLORRANK "SEM_COLORRANK",
 SEM.SAMPLEDATE "SEM_SAMPLEDATE",
 SEM.REASON "SEM_REASON",
 SEM.NOTIFIEDBY "SEM_NOTIFIEDBY",
 SEM.MOCCONTROLLER "SEM_MOCCONTROLLER",
 SEM.SEMEDXLASTUPDATED,
 SEM.HOURSREQUIRED "SEM_HRSREQUIRED",
 SEM.HOURSREMAINING "SEM_HRSREMAINING",
 SEM.EXPEDITED "SEM_EXPEDITED"
FROM EMOC3.AIRCRAFT_STATUSBOARD_VIEW STB
LEFT JOIN EMOC3.AIRCRAFT_ENGINE_DATA_VIEW ENG ON ENG.SQUADRONNAME = STB.SQUADRONNAME AND ENG.TAILNUMBER = STB.TAILNUMBER AND ENG.AIRCRAFTMDS = STB.AIRCRAFTMDS
LEFT JOIN EMOC3.AIRCRAFT_STATUSUPDATE_VIEW STU ON STB.SQUADRONNAME = STU.SQUADRONNAME AND STB.TAILNUMBER = STU.TAILNUMBER AND STB.AIRCRAFTMDS = STU.AIRCRAFTMDS
LEFT JOIN EMOC3.JOAP_VIEW JP ON STB.SQUADRONNAME = JP.SQUADRONNAME AND STB.TAILNUMBER = JP.TAILNUMBER AND STB.AIRCRAFTMDS = JP.AIRCRAFTMDS
LEFT JOIN EMOC3.SEMEDX_VIEW SEM ON STB.SQUADRONNAME = SEM.SQUADRONNAME AND STB.TAILNUMBER = SEM.TAILNUMBER AND STB.AIRCRAFTMDS = SEM.AIRCRAFTMDS
LEFT JOIN EMOC3.WEAPONS_VIEW WPN ON STB.SQUADRONNAME = WPN.SQUADRONNAME AND STB.TAILNUMBER = WPN.TAILNUMBER AND STB.AIRCRAFTMDS = WPN.AIRCRAFTMDS
LEFT JOIN EMOC3.WRITEUPS_AND_MICAPS_VIEW WMV ON STB.SQUADRONNAME = WMV.SQUADRONNAME AND STB.TAILNUMBER = WMV.TAILNUMBER AND STB.AIRCRAFTMDS = WMV.AIRCRAFTMDS
@

CREATE OR REPLACE VIEW "EMOC3"."AIRCRAFT_HISTORY_VIEW" ("WING", "UNITID", "ELC", "SQUADRONNAME", "MOCID", "AIRCRAFTYEAR", "TAILNUMBER", "MISEQUIPID", "SERIALNUMBER", "AIRCRAFTMDS", "OTHERMDS", "EVENTDATE", "FIELD", "VALUE", "UPDATER") AS
SELECT WINGS.wingname "WING",
    WINGS.UNITID "UNITID",
    WINGS.ELC "ELC",
       SQUADRONS.squadronname,
AIRCRAFT.MOCID,
    AIRCRAFT.aircraftyear "AIRCRAFTYEAR",
       AIRCRAFT.shorttailnumber "TAILNUMBER",
    AIRCRAFT.misequipid "MISEQUIPID",
       AIRCRAFT.serialnumber "SERIALNUMBER",
       AIRCRAFTMDS.AIRCRAFTMDS "AIRCRAFTMDS",
    AIRCRAFT.RELATEDMDS "OTHERMDS",
    HISTORY.EVENTDATE,
    HISTORY.ELEMENT "FIELD",
       HISTORY.elementvalue "VALUE",
    USERS.fullname "UPDATER"
 FROM EMOC3.AIRCRAFT,
          EMOC3.SQUADRONS,
          EMOC3.AIRCRAFTMDS,
    EMOC3.WINGS,
    EMOC3.HISTORY, EMOC3.USERS
    WHERE (    (AIRCRAFT.squadronid = SQUADRONS.squadronid)
           AND (WINGS.wingid = SQUADRONS.wingid)
           AND (AIRCRAFTMDS.aircraftmdsid = AIRCRAFT.aircraftmdsid(+))
           AND (AIRCRAFT.aircraftid = HISTORY.aircraftid)
     AND (USERS.userid = HISTORY.userid)
          )
 
 
 
 
 
 
 
 
@

CREATE OR REPLACE VIEW "EMOC3"."AIRCRAFT_HISTORY_ARCHIVE_VIEW" ("SQUADRONNAME", "AIRCRAFTYEAR", "TAILNUMBER", "MISEQUIPID", "SERIALNUMBER", "AIRCRAFTMDS", "OTHERMDS", "HIS_EVENTDATE", "HIS_ELEMENTVALUE", "HIS_ELEMENT", "HIS_TRANSACTIONID", "HIS_ARCHIVEDATE", "MOCID") AS
SELECT
       AIRCRAFT.SQUADRONNAME,
    AIRCRAFT.AIRCRAFTYEAR "AIRCRAFTYEAR",
       AIRCRAFT.SHORTTAILNUMBER "TAILNUMBER",
    AIRCRAFT.MISEQUIPID "MISEQUIPID",
       AIRCRAFT.SERIALNUMBER "SERIALNUMBER",
       AIRCRAFT.AIRCRAFTMDS "AIRCRAFTMDS",
    AIRCRAFT.RELATEDMDS "OTHERMDS",
    HIS.EVENTDATE "HISTORY_EVENTDATE",
    HIS.ELEMENT "HISTORY_ELEMENT",
    HIS.ELEMENTVALUE "HISTORY_VALUE",
    HIS.TRANSACTIONID "HISTORY_TRANSACTIONID",
    HIS.ARCHIVEDATE "HIS_ARCHIVEDATE",
    AC.MOCID "MOCID"
FROM EMOCAUX.AIRCRAFT
LEFT JOIN EMOCAUX.HISTORY HIS ON HIS.AIRCRAFTID = AIRCRAFT.AIRCRAFTID
LEFT JOIN EMOC3.AIRCRAFT AC ON AC.AIRCRAFTID = AIRCRAFT.AIRCRAFTID
 
 
 
 
 
 
 
 
@

CREATE OR REPLACE VIEW "EMOC3"."AIRCRAFT_ARCHIVE_VIEW" ("SQUADRONNAME", "MOCID", "AIRCRAFTYEAR", "TAILNUMBER", "MISEQUIPID", "SERIALNUMBER", "AIRCRAFTMDS", "OTHERMDS", "CONDCODE", "STATUSCODE", "STATUSNARRATIVE", "FLIGHTNAME", "ETIC", "AIRCRAFTWUC", "FCF", "OCF", "QVI", "HOTGUNS", "ARM_DEARM", "COMMANDCODE", "PRIORITY", "HQCODE", "LASTFLOWNTIME", "PHASEDATE", "TMEFLWNSINCEPHASE", "PHASEUNITS", "MULTICONFIGID", "ACFT_CONFIG_ID", "LOCALCONFIGID", "LOCALOPTION", "LOCCODE", "STALOCCODE", "BLOCKNUMBER", "ASSIGNCMD", "ASSIGNSTATUS", "POSSESSION", "REPORTDESIG", "REMARKS", "ARCHIVEDATE", "AED_ENGINENUMBER", "AED_ARCHIVEDATE", "MNT_UNIT", "MNT_EVENTID", "MNT_PWC", "MNT_EQUIPID", "MNT_CP", "MNT_WUCLCN", "MNT_WD", "MNT_PRIORITY", "MNT_SYMBOL", "MNT_TSSCH", "MNT_JOBDUR", "MNT_DISCREPANCY", "MNT_WCENARRATIVE", "MNT_EMPID", "MNT_ENTRY781", "MNT_DEFER", "MNT_WCESYMBOL", "MNT_JOB_FOLLOW", "MNT_PARTSREQUIRED", "MNT_ENTERED", "MNT_ARCHIVEDATE", "MIC_MICAPID", "MIC_DOCNUMBER", "MIC_PART", "MIC_ETA", "MIC_ARCHIVEDATE", "SD_REQUESTER", "SD_WORKCENTERCODE", "SD_PERSONCONTACTED", "SD_PERSONDISPATCHED", "SD_REQUESTDATE", "SD_DISCREPANCY", "SD_COMPLETIONDATE", "SD_ETICSHOWTIME", "SD_ENTERED", "SD_ENTEREDBY", "SD_SQDISPATCHEDTO", "SD_ARCHIVEDATE", "WL_STATION", "WL_ORDNANCE", "WL_WEAPONSNUMBER", "WL_WEAPONSCLASS", "WL_FIRESYMBOL", "WL_ARCHIVEDATE", "WU_WRITEUPTIME", "WU_JCN", "WU_CORRECTED", "WU_CORRECTEDTIME", "WU_PACER", "WU_ETIC", "WU_SYMBOL", "WU_WUC", "WU_DISCREPANCY", "WU_CORRECTIVEACTION", "WU_ARCHIVEDATE") AS
SELECT
       AIRCRAFT.SQUADRONNAME,
       AC.MOCID,
    AIRCRAFT.AIRCRAFTYEAR "AIRCRAFTYEAR",
       AIRCRAFT.SHORTTAILNUMBER "TAILNUMBER",
    AIRCRAFT.MISEQUIPID "MISEQUIPID",
       AIRCRAFT.SERIALNUMBER "SERIALNUMBER",
       AIRCRAFT.AIRCRAFTMDS "AIRCRAFTMDS",
    AIRCRAFT.RELATEDMDS "OTHERMDS",
       AIRCRAFT.CONDITIONCODE "CONDCODE",
    AIRCRAFT.STATUSCODE,
    AIRCRAFT.STATUSNARRATIVE,
    AIRCRAFT.FLIGHTNAME "FLIGHTNAME",
    AIRCRAFT.ETIC "ETIC",
    AIRCRAFT.AIRCRAFTWUC "AIRCRAFTWUC",
    DECODE(TO_CHAR(AIRCRAFT.FCF), '1', 'Y', 'N') FCF,
    DECODE(TO_CHAR(AIRCRAFT.OCF), '1', 'Y', 'N') OCF,
    NULL AS "QVI", --DECODE(TO_CHAR(AIRCRAFT.QVI), '1', 'Y', 'N') QVI,
    NULL AS "HOTGUNS", --DECODE(TO_CHAR(AIRCRAFT.hotguns), '1', 'Y', 'N') hotguns,
    DECODE(TO_CHAR(AIRCRAFT.ARM_DEARM), '1', 'Y', 'N') arm_dearm,
    AIRCRAFT.COMMANDCODE "COMMANDCODE",
    TO_CHAR(AIRCRAFT.PRIORITY) "PRIORITY",
       AIRCRAFT.HQCODE "HQCODE",
       AIRCRAFT.LASTFLOWNTIME "LASTFLOWNTIME",
    AIRCRAFT.PHASEDATE "PHASEDATE",
    AIRCRAFT.TMEFLOWNSINCEPHASEDATE "TMEFLWNSINCEPHASE",
    AIRCRAFT.PHASEUNITS,
    AIRCRAFT.MULTICONFIGID,
    AIRCRAFT.ACFT_CONFIG_ID,
    AIRCRAFT.LOCALCONFIGID,
    AIRCRAFT.LOCALOPTION,
    AIRCRAFT.LOCATION "LOCCODE",
    AIRCRAFT.STALOCCODE,
    AIRCRAFT.BLOCKNUMBER "BLOCKNUMBER",
    AIRCRAFT.ASSIGNMENTCMD "ASSIGNCMD",
    AIRCRAFT.ASSIGNMENTSTATUS "ASSIGNSTATUS",
       AIRCRAFT.POSSESSIONCODE "POSSESSION",
       AIRCRAFT.REPORTDESIG,
    AIRCRAFT.REMARKS "REMARKS",
    AIRCRAFT.ARCHIVEDATE "ARCHIVEDATE",
    AED.ENGINENUMBER "AED_ENGINENUMBER",
    AED.ARCHIVEDATE "AED_ARCHIVEDATE",
    MNT.UNIT "MNT_UNIT",
    MNT.EVENTID "MNT_EVENTID",
    MNT.PWC "MNT_PWC",
    MNT.EQUIPID "MNT_EQUIPID",
    MNT.CP "MNT_CP",
    MNT.WUCLCN "MNT_WUCLCN",
    MNT.WD "MNT_WD",
    MNT.PRIORITY "MNT_PRIORITY",
    MNT.SYMBOL "MNT_SYMBOL",
    MNT.TSSCH "MNT_TSSCH",
    MNT.JOBDUR "MNT_JOBDUR",
    MNT.DISCREPANCY "MNT_DISCREPANCY",
    MNT.WCENARRATIVE "MNT_WCENARRATIVE",
    MNT.EMPID "MNT_EMPID",
    MNT.ENTRY781 "MNT_ENTRY781",
    MNT.DEFER "MNT_DEFER",
    MNT.WCESYMBOL "MNT_WCESYMBOL",
    MNT.JOBFOLLOW "MNT_JOB_FOLLOW",
    MNT.PARTSREQUIRED "MNT_PARTSREQUIRED",
    MNT.ENTERED "MNT_ENTERED",
    MNT.ARCHIVEDATE "MNT_ARCHIVEDATE",
    MIC.MICAPID "MIC_MICAPID",
    MIC.DOCUMENTNUMBER "MIC_DOCNUMBER",
    MIC.NOMENCLATURE "MIC_PART",
    MIC.ESTIMATEDDELIVERYDATE "MIC_ETA",
    MIC.ARCHIVEDATE "MIC_ARCHIVEDATE",
    SD.REQUESTER "SD_REQUESTER",
    SD.WORKCENTERCODE "SD_WORKCENTERCODE",
    SD.PERSONCONTACTED "SD_PERSONCONTACTED",
    SD.PERSONDISPATCHED "SD_PERSONDISPATCHED",
    SD.REQUESTDATE "SD_REQUESTDATE",
    SD.DISCREPANCY "SD_DISCREPANCY",
    SD.COMPLETIONDATE "SD_COMPLETIONDATE",
    SD.ETICSHOWTIME "SD_ETICSHOWTIME",
    SD.ENTERED "SD_ENTERED",
    SD.ENTEREDBY "SD_ENTEREDBY",
    SD.SQDISPATCHEDTO "SD_SQDISPATCHEDTO",
    SD.ARCHIVEDATE "SD_ARCHIVEDATE",
    WL.STATION "WL_STATION",
    WL.ORDNANCE "WL_ORDNANCE",
    WL.WEAPONSNUMBER "WL_WEAPONSNUMBER",
    WL.WEAPONSCLASS "WL_WEAPONSCLASS",
    WL.FIRESYMBOL "WL_FIRESYMBOL",
    WL.ARCHIVEDATE "WL_ARCHIVEDATE",
    WU.WRITEUPTIME "WU_WRITEUPTIME",
    WU.JCN "WU_JCN",
    WU.CORRECTED "WU_CORRECTED",
    WU.CORRECTEDTIME "WU_CORRECTEDTIME",
    WU.PACER "WU_PACER",
    WU.ETIC "WU_ETIC",
    WU.SYMBOL "WU_SYMBOL",
    WU.WUC "WU_WUC",
    WU.DISCREPANCY "WU_DISCREPANCY",
    WU.CORRECTIVEACTION "WU_CORRECTIVEACTION",
    WU.ARCHIVEDATE "WU_ARCHIVEDATE"
FROM EMOCAUX.AIRCRAFT
LEFT JOIN EMOC3.AIRCRAFT AC ON AC.AIRCRAFTID = AIRCRAFT.AIRCRAFTID
LEFT JOIN EMOCAUX.AIRCRAFTENGINEDATA AED ON AED.AIRCRAFTID = AIRCRAFT.AIRCRAFTID
LEFT JOIN EMOCAUX.MAINTENANCEEVENTS MNT ON MNT.AIRCRAFTID = AIRCRAFT.AIRCRAFTID
LEFT JOIN EMOCAUX.MICAP MIC ON MIC.AIRCRAFTID = AIRCRAFT.AIRCRAFTID
LEFT JOIN EMOCAUX.SHOPDISPATCH SD ON SD.AIRCRAFTID = AIRCRAFT.AIRCRAFTID
LEFT JOIN EMOCAUX.WEAPONSLOAD WL ON WL.AIRCRAFTID = AIRCRAFT.AIRCRAFTID
LEFT JOIN EMOCAUX.WRITEUPS WU ON WU.AIRCRAFTID = AIRCRAFT.AIRCRAFTID
 
 
 
 
 
 
 
 
@

CREATE OR REPLACE VIEW "EMOC3"."AIRCRAFTVIEW" ("AIRCRAFTID", "SHORTTAILNUMBER", "TAILNUMBER", "SQUADRONID", "WINGID", "CONDITIONCODEID", "AIRCRAFTMDSID", "AIRCRAFTYEAR", "AIRCRAFTMDS", "ACFTMDSTYPECD", "MISEQUIPID", "MOCID") AS
SELECT   aircraftid, shorttailnumber, tailnumber, squadrons.squadronid,
         wingid, conditioncodeid, aircraftmds.aircraftmdsid, aircraftyear,
         aircraftmds, acftmdstypecd, misequipid, aircraft.mocid
FROM emoc3.aircraft JOIN emoc3.squadrons ON aircraft.squadronid = squadrons.squadronid
              JOIN emoc3.aircraftmds ON aircraft.aircraftmdsid = aircraftmds.aircraftmdsid
ORDER BY shorttailnumber
/* *** DCW Evaluation Issue "DDL_VIEW_ORDER_BY".Corresponding line no in the source file:11566 *** */
@
