--<ScriptOptions statementTerminator="@"/>


ALTER TABLE "EMOC3"."ACFTMDSTYPES" ADD CONSTRAINT "FK_MDSTYP_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."AIRCRAFT" ADD CONSTRAINT "FK_AIRCRAFT_REFERENCE_CONDITIO" FOREIGN KEY
	("CONDITIONCODEID")
	REFERENCES "EMOC3"."CONDITIONCODES"
	("CONDCODEID")
@

ALTER TABLE "EMOC3"."AIRCRAFT" ADD CONSTRAINT "FK_AIRCRAFT_REFERENCE_FLIGHTS" FOREIGN KEY
	("FLIGHTID")
	REFERENCES "EMOC3"."FLIGHTS"
	("FLIGHTID")
@

ALTER TABLE "EMOC3"."AIRCRAFT" ADD CONSTRAINT "FK_AIRCRAFT_REFERENCE_FUEL" FOREIGN KEY
	("FUELSTATUSID")
	REFERENCES "EMOC3"."FUEL"
	("FUELSTATUSID")
@

ALTER TABLE "EMOC3"."AIRCRAFT" ADD CONSTRAINT "FK_AIRCRAFT_REF_AIRCRAFTMDS" FOREIGN KEY
	("AIRCRAFTMDSID")
	REFERENCES "EMOC3"."AIRCRAFTMDS"
	("AIRCRAFTMDSID")
@

ALTER TABLE "EMOC3"."AIRCRAFT" ADD CONSTRAINT "FK_AIRCRAFT_REF_COMBATSCLS" FOREIGN KEY
	("COMBATSCLID")
	REFERENCES "EMOC3"."COMBATSCLS"
	("COMBATSCLID")
@

ALTER TABLE "EMOC3"."AIRCRAFT" ADD CONSTRAINT "FK_AIRCRAFT_REF_CREWCHIEFS" FOREIGN KEY
	("CREWCHIEFID")
	REFERENCES "EMOC3"."CREWCHIEFS"
	("CREWCHIEFID")
@

ALTER TABLE "EMOC3"."AIRCRAFT" ADD CONSTRAINT "FK_AIRCRAFT_REF_HaNGERQUEEN" FOREIGN KEY
	("HANGERQUEENSTATUS")
	REFERENCES "EMOC3"."HANGER_QUEEN_CODE"
	("HQCODEID")
@

ALTER TABLE "EMOC3"."AIRCRAFT" ADD CONSTRAINT "FK_AIRCRAFT_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."AIRCRAFT" ADD CONSTRAINT "FK_AIRCRAFT_REF_POSSESSIONS" FOREIGN KEY
	("POSSESSIONID")
	REFERENCES "EMOC3"."POSSESSIONS"
	("POSSESSIONID")
@

ALTER TABLE "EMOC3"."AIRCRAFT" ADD CONSTRAINT "FK_AIRCRAFT_REF_REMARKS" FOREIGN KEY
	("REMARKSID")
	REFERENCES "EMOC3"."REMARKS"
	("REMARKSID")
@

ALTER TABLE "EMOC3"."AIRCRAFT" ADD CONSTRAINT "FK_AIRCRAFT_REF_SQ" FOREIGN KEY
	("SQUADRONID")
	REFERENCES "EMOC3"."SQUADRONS"
	("SQUADRONID")
@

ALTER TABLE "EMOC3"."AIRCRAFT" ADD CONSTRAINT "FK_AIRCRAFT_REF_STATUSCODE" FOREIGN KEY
	("STATUSCODEID")
	REFERENCES "EMOC3"."STATUSCODE"
	("STATUSCODEID")
@

ALTER TABLE "EMOC3"."AIRCRAFT" ADD CONSTRAINT "FK_FIRESYMBOLID" FOREIGN KEY
	("FIRESYMBOLID")
	REFERENCES "EMOC3"."FIRESYMBOLS"
	("FIRESYMBOLID")
@

ALTER TABLE "EMOC3"."AIRCRAFTMDS" ADD CONSTRAINT "FK_MDS_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."AREAS" ADD CONSTRAINT "FK_AREA_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."ARMAMENT" ADD CONSTRAINT "FK_ARMAMENT_REFERENCE_ORDNANCE" FOREIGN KEY
	("ORDNANCEID")
	REFERENCES "EMOC3"."ORDNANCE"
	("ORDNANCEID")
@

ALTER TABLE "EMOC3"."ARMAMENT" ADD CONSTRAINT "FK_ARMAMENT_REF_AIRCRAFTMDS" FOREIGN KEY
	("AIRCRAFTMDSID")
	REFERENCES "EMOC3"."AIRCRAFTMDS"
	("AIRCRAFTMDSID")
@

ALTER TABLE "EMOC3"."ARMAMENT" ADD CONSTRAINT "FK_ARMAMNT_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."ASSIGNMENTCODES" ADD CONSTRAINT "FK_ASGNCODE_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."BASEMAPS" ADD CONSTRAINT "FK_BASEMAPS_MOCID" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
	ON DELETE CASCADE
@

ALTER TABLE "EMOC3"."BRIEF_AIRCRAFT_STATUS" ADD CONSTRAINT "FK_MOCID_BRIEF_AC_STATUS" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."BRIEF_AIRCRAFT_STATUS" ADD CONSTRAINT "FK_SQID_BRIEF_AC_STATUS" FOREIGN KEY
	("SQUADRONID")
	REFERENCES "EMOC3"."SQUADRONS"
	("SQUADRONID")
@

ALTER TABLE "EMOC3"."BRIEF_DEVIATIONS" ADD CONSTRAINT "FK_MOCID_BRIEF_DEVIATIONS" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."BRIEF_DEVIATIONS" ADD CONSTRAINT "FK_SQID_BRIEF_DEVIATIONS" FOREIGN KEY
	("SQUADRONID")
	REFERENCES "EMOC3"."SQUADRONS"
	("SQUADRONID")
@

ALTER TABLE "EMOC3"."BRIEF_FLYING_SCHEDULE" ADD CONSTRAINT "FK_MOCID_BRIEF_FLYINGSCH" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."BRIEF_FLYING_SCHEDULE" ADD CONSTRAINT "FK_SQID_BRIEF_FLYINGSCH" FOREIGN KEY
	("SQUADRONID")
	REFERENCES "EMOC3"."SQUADRONS"
	("SQUADRONID")
@

ALTER TABLE "EMOC3"."BRIEF_FLYING_STATUS" ADD CONSTRAINT "FK_MOCID_BRIEF_FLYING_STATUS" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."BRIEF_FLYING_STATUS" ADD CONSTRAINT "FK_SQID_BRIEF_FLYING_STATUS" FOREIGN KEY
	("SQUADRONID")
	REFERENCES "EMOC3"."SQUADRONS"
	("SQUADRONID")
@

ALTER TABLE "EMOC3"."BRIEF_HANGAR_QUEEN" ADD CONSTRAINT "FK_MOCID_BRIEF_HANGAR_QUEEN" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."BRIEF_HANGAR_QUEEN" ADD CONSTRAINT "FK_SQID_BRIEF_HANGAR_QUEEN" FOREIGN KEY
	("SQUADRONID")
	REFERENCES "EMOC3"."SQUADRONS"
	("SQUADRONID")
@

ALTER TABLE "EMOC3"."BRIEF_MICAPS" ADD CONSTRAINT "FK_MOCID_BRIEF_MICAPS" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."BRIEF_MICAPS" ADD CONSTRAINT "FK_SQID_BRIEF_MICAPS" FOREIGN KEY
	("SQUADRONID")
	REFERENCES "EMOC3"."SQUADRONS"
	("SQUADRONID")
@

ALTER TABLE "EMOC3"."BRIEF_NEXT_WEEKS_PLAN" ADD CONSTRAINT "FK_MOCID_BRIEF_NXT_WEEK_PLAN" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."BRIEF_NEXT_WEEKS_PLAN" ADD CONSTRAINT "FK_SQID_BRIEF_NXT_WEEK_PLAN" FOREIGN KEY
	("SQUADRONID")
	REFERENCES "EMOC3"."SQUADRONS"
	("SQUADRONID")
@

ALTER TABLE "EMOC3"."BRIEF_POT_HANGAR_QUEEN" ADD CONSTRAINT "FK_MOCID_POT_HANGAR_QUEEN" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."BRIEF_POT_HANGAR_QUEEN" ADD CONSTRAINT "FK_SQID_POT_HANGAR_QUEEN" FOREIGN KEY
	("SQUADRONID")
	REFERENCES "EMOC3"."SQUADRONS"
	("SQUADRONID")
@

ALTER TABLE "EMOC3"."BRIEF_SCHEDULE_OVERVIEW" ADD CONSTRAINT "FK_MOCID_BRIEF_SCH_OVERVIEW" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."BRIEF_SCHEDULE_OVERVIEW" ADD CONSTRAINT "FK_SQID_BRIEF_SCH_OVERVIEW" FOREIGN KEY
	("SQUADRONID")
	REFERENCES "EMOC3"."SQUADRONS"
	("SQUADRONID")
@

ALTER TABLE "EMOC3"."BRIEF_WING_STATUS" ADD CONSTRAINT "FK_MOCID_BRIEF_WING_STATUS" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."BRIEF_WING_STATUS" ADD CONSTRAINT "FK_SQID_BRIEF_WING_STATUS" FOREIGN KEY
	("SQUADRONID")
	REFERENCES "EMOC3"."SQUADRONS"
	("SQUADRONID")
@

ALTER TABLE "EMOC3"."CAUSECODES" ADD CONSTRAINT "FK_CAUSECD_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."CHANGENOTIFICATION" ADD CONSTRAINT "FK_CHANGENOTIFICATION_MOCID" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."CHECKLIST" ADD CONSTRAINT "FK_MOCID" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."COLORRULES" ADD CONSTRAINT "FK_COLORRULES_REF_COLORS" FOREIGN KEY
	("COLORID")
	REFERENCES "EMOC3"."COLORS"
	("COLORID")
@

ALTER TABLE "EMOC3"."COLORRULES" ADD CONSTRAINT "FK_COLRRULE_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
	ON DELETE CASCADE
@

ALTER TABLE "EMOC3"."COLORS" ADD CONSTRAINT "FK_COLOR_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."COMBATSCLRULES" ADD CONSTRAINT "FK_COMBATSC_REFERENCE_AIRCRAFT" FOREIGN KEY
	("AIRCRAFTMDSID")
	REFERENCES "EMOC3"."AIRCRAFTMDS"
	("AIRCRAFTMDSID")
@

ALTER TABLE "EMOC3"."COMBATSCLRULES" ADD CONSTRAINT "FK_COMBATSC_REFERENCE_COMBATSC" FOREIGN KEY
	("COMBATSCLID")
	REFERENCES "EMOC3"."COMBATSCLS"
	("COMBATSCLID")
@

ALTER TABLE "EMOC3"."COMBATSCLRULES" ADD CONSTRAINT "FK_SCLRULE_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."COMBATSCLS" ADD CONSTRAINT "FK_SCL_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."CONDITIONCODES" ADD CONSTRAINT "FK_CONDCODE_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."CONDITIONSTATUS" ADD CONSTRAINT "FK_CONDSTATUS_REF_COLORS" FOREIGN KEY
	("COLORID")
	REFERENCES "EMOC3"."COLORS"
	("COLORID")
@

ALTER TABLE "EMOC3"."CONDITIONSTATUS" ADD CONSTRAINT "FK_CONDSTAT_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."CREWCHIEFS" ADD CONSTRAINT "FK_CREWCHIE_REFERENCE_RANKS" FOREIGN KEY
	("RANKID")
	REFERENCES "EMOC3"."RANKS"
	("RANKID")
@

ALTER TABLE "EMOC3"."CREWCHIEFS" ADD CONSTRAINT "FK_CREWCH_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."CUSTOMDATA" ADD CONSTRAINT "FK_CUSTOMD_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."DEVIATIONCODES" ADD CONSTRAINT "FK_DEVC_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."DEVIATIONCODES" ADD CONSTRAINT "FK_DEVIATIO_REFERENCE_COLORS" FOREIGN KEY
	("COLORID")
	REFERENCES "EMOC3"."COLORS"
	("COLORID")
@

ALTER TABLE "EMOC3"."EMOCCONFIG" ADD CONSTRAINT "FK_CONFIG_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."EMOCCONFIG" ADD CONSTRAINT "FK_CONFIG_REF_USERS" FOREIGN KEY
	("LASTUPDATEDBY")
	REFERENCES "EMOC3"."USERS"
	("USERID")
@

ALTER TABLE "EMOC3"."ENGINERUNLOG" ADD CONSTRAINT "FK_ENGINERUNLOG_REF_AIRCRAFT" FOREIGN KEY
	("AIRCRAFTID")
	REFERENCES "EMOC3"."AIRCRAFT"
	("AIRCRAFTID")
@

ALTER TABLE "EMOC3"."ENGINERUNLOG" ADD CONSTRAINT "FK_RUNLOG_REF_ENGINEDATA" FOREIGN KEY
	("ENGINEDATAID")
	REFERENCES "EMOC3"."AIRCRAFTENGINEDATA"
	("ENGINEDATAID")
@

ALTER TABLE "EMOC3"."ENGINERUNLOG" ADD CONSTRAINT "FK_RUNLOG_REF_USERS" FOREIGN KEY
	("LASTUPDATEBY")
	REFERENCES "EMOC3"."USERS"
	("USERID")
@

ALTER TABLE "EMOC3"."EVENTLOG" ADD CONSTRAINT "FK_EVENTLOG_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."EVENTLOG" ADD CONSTRAINT "FK_EVENTLOG_REF_USERS" FOREIGN KEY
	("USERID")
	REFERENCES "EMOC3"."USERS"
	("USERID")
@

ALTER TABLE "EMOC3"."FIRESYMBOLS" ADD CONSTRAINT "FK_FIRESYM_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."FLIGHTS" ADD CONSTRAINT "FK_FLIGHTS_REFERENCE_SQUADRON" FOREIGN KEY
	("SQUADRONID")
	REFERENCES "EMOC3"."SQUADRONS"
	("SQUADRONID")
@

ALTER TABLE "EMOC3"."FUEL" ADD CONSTRAINT "FK_FUEL_REFERENCE_COLORS" FOREIGN KEY
	("COLORID")
	REFERENCES "EMOC3"."COLORS"
	("COLORID")
@

ALTER TABLE "EMOC3"."FUEL" ADD CONSTRAINT "FK_FUEL_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."GENERATIONFLOW" ADD CONSTRAINT "FK_GENFLO_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."HANGER_QUEEN_CODE" ADD CONSTRAINT "FK_HQC_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."HISTORY" ADD CONSTRAINT "FK_HISTORY_REFERENCE_AIRCRAFT" FOREIGN KEY
	("AIRCRAFTID")
	REFERENCES "EMOC3"."AIRCRAFT"
	("AIRCRAFTID")
@

ALTER TABLE "EMOC3"."HISTORY" ADD CONSTRAINT "FK_HISTORY_REFERENCE_USERS" FOREIGN KEY
	("USERID")
	REFERENCES "EMOC3"."USERS"
	("USERID")
@

ALTER TABLE "EMOC3"."HOTSPOTS" ADD CONSTRAINT "FK_HOTS_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."IMDSCDBELCUNITOPTION" ADD CONSTRAINT "FK_ELCUNITOPT_REF_IMDSCDBOPT" FOREIGN KEY
	("IMDSCDBINTERFACEOPTIONID")
	REFERENCES "EMOC3"."IMDSCDBINTERFACEOPTION"
	("IMDSCDBINTERFACEOPTIONID")
@

ALTER TABLE "EMOC3"."IMDSLOGINS" ADD CONSTRAINT "FK_IMDSLOGINS_REF_USERS" FOREIGN KEY
	("USERID")
	REFERENCES "EMOC3"."USERS"
	("USERID")
@

ALTER TABLE "EMOC3"."INTERFACECONTROL" ADD CONSTRAINT "FK_ICTRL_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."INTERFACEITEMS" ADD CONSTRAINT "FK_IITEM_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."INTERFACEITEMS" ADD CONSTRAINT "FK_INTITEMS_REF_INTCONTROL" FOREIGN KEY
	("INTERFACECONTROLID")
	REFERENCES "EMOC3"."INTERFACECONTROL"
	("INTERFACECONTROLID")
@

ALTER TABLE "EMOC3"."INTERFACELOG" ADD CONSTRAINT "FK_ILOG_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."INTERFACELOG" ADD CONSTRAINT "FK_INTERFACELOG_REF_AIRCRAFT" FOREIGN KEY
	("AIRCRAFTID")
	REFERENCES "EMOC3"."AIRCRAFT"
	("AIRCRAFTID")
@

ALTER TABLE "EMOC3"."INTERFACELOG" ADD CONSTRAINT "FK_INTERFACELOG_REF_CTRL" FOREIGN KEY
	("INTERFACECONTROLID")
	REFERENCES "EMOC3"."INTERFACECONTROL"
	("INTERFACECONTROLID")
@

ALTER TABLE "EMOC3"."INTERFACELOG" ADD CONSTRAINT "FK_INTERFACELOG_REF_USERS" FOREIGN KEY
	("USERID")
	REFERENCES "EMOC3"."USERS"
	("USERID")
@

ALTER TABLE "EMOC3"."JOAP" ADD CONSTRAINT "FK_JOAP_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."JOAPDATA" ADD CONSTRAINT "FK_JOAPDATA_REFERENCE_JOAP" FOREIGN KEY
	("JOAPID")
	REFERENCES "EMOC3"."JOAP"
	("JOAPID")
@

ALTER TABLE "EMOC3"."JOAPDATA" ADD CONSTRAINT "FK_JOAPDATA_REF_ENGINEDATA" FOREIGN KEY
	("ENGINEDATAID")
	REFERENCES "EMOC3"."AIRCRAFTENGINEDATA"
	("ENGINEDATAID")
@

ALTER TABLE "EMOC3"."JOAPDATA" ADD CONSTRAINT "FK_JOAPDATA_REF_SCHED" FOREIGN KEY
	("SCHEDULEID")
	REFERENCES "EMOC3"."SCHEDULE"
	("SCHEDULEID")
@

ALTER TABLE "EMOC3"."LANDINGCODES" ADD CONSTRAINT "FK_LANDC_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."LINKS" ADD CONSTRAINT "FK_LINK_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."LOCATIONS" ADD CONSTRAINT "FK_LOC_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."MAINTENANCEEVENTS" ADD CONSTRAINT "FK_MAINTEVENTS_REF_AIRCRAFT" FOREIGN KEY
	("AIRCRAFTID")
	REFERENCES "EMOC3"."AIRCRAFT"
	("AIRCRAFTID")
@

ALTER TABLE "EMOC3"."MAJCOMS" ADD CONSTRAINT "FK_MAJCOM_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."MESSAGES" ADD CONSTRAINT "FK_MSG_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."MISSIONS" ADD CONSTRAINT "FK_MISSION_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."MOCADMINS" ADD CONSTRAINT "FK_MOCADMIN_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."MOCADMINS" ADD CONSTRAINT "FK_MOCADMIN_REF_USERS" FOREIGN KEY
	("USERID")
	REFERENCES "EMOC3"."USERS"
	("USERID")
@

ALTER TABLE "EMOC3"."MOCSTATUSICONS" ADD CONSTRAINT "FK_MOCSTATUSICONS_REF_SI" FOREIGN KEY
	("STATUSIMAGEID")
	REFERENCES "EMOC3"."STATUSIMAGE"
	("STATUSIMAGEID")
@

ALTER TABLE "EMOC3"."MOCUSERS" ADD CONSTRAINT "FK_MOCUSER_REF_USERS" FOREIGN KEY
	("USERID")
	REFERENCES "EMOC3"."USERS"
	("USERID")
@

ALTER TABLE "EMOC3"."MOCUSERS" ADD CONSTRAINT "SYS_C0014200" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."OLDPASSWORDS" ADD CONSTRAINT "FK_OLDPASSW_REFERENCE_USERS" FOREIGN KEY
	("USERID")
	REFERENCES "EMOC3"."USERS"
	("USERID")
@

ALTER TABLE "EMOC3"."ORDNANCE" ADD CONSTRAINT "FK_ORDNANCE_REF_WEAPONSTYPE" FOREIGN KEY
	("WEAPONSTYPEID")
	REFERENCES "EMOC3"."WEAPONTYPES"
	("WEAPONSTYPEID")
@

ALTER TABLE "EMOC3"."ORDNANCE" ADD CONSTRAINT "FK_ORD_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."ORGANIZATIONS" ADD CONSTRAINT "FK_ORG_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."PERMISSIONS" ADD CONSTRAINT "FK_PERMISSI_REFERENCE_SQUADRON" FOREIGN KEY
	("SQUADRONID")
	REFERENCES "EMOC3"."SQUADRONS"
	("SQUADRONID")
@

ALTER TABLE "EMOC3"."PERMISSIONS" ADD CONSTRAINT "FK_PERMISSI_REFERENCE_USERS" FOREIGN KEY
	("USERID")
	REFERENCES "EMOC3"."USERS"
	("USERID")
@

ALTER TABLE "EMOC3"."PILOT" ADD CONSTRAINT "FK_PILOT_REFERENCE_RANKS" FOREIGN KEY
	("RANKID")
	REFERENCES "EMOC3"."RANKS"
	("RANKID")
@

ALTER TABLE "EMOC3"."PILOT" ADD CONSTRAINT "FK_PILOT_REFERENCE_SQUADRON" FOREIGN KEY
	("SQUADRONID")
	REFERENCES "EMOC3"."SQUADRONS"
	("SQUADRONID")
@

ALTER TABLE "EMOC3"."PILOT" ADD CONSTRAINT "FK_PILOT_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."POSSESSIONS" ADD CONSTRAINT "FK_POSS_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."RANGES" ADD CONSTRAINT "FK_RANGE_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."RANKS" ADD CONSTRAINT "FK_RANKS_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."REPORTCOLUMNS" ADD CONSTRAINT "FK_REPCOL_REF_REPORTS" FOREIGN KEY
	("REPORTID")
	REFERENCES "EMOC3"."REPORTS"
	("REPORTID")
@

ALTER TABLE "EMOC3"."REPORTCRITERIA" ADD CONSTRAINT "REPORTID_FK" FOREIGN KEY
	("REPORTID")
	REFERENCES "EMOC3"."REPORTS"
	("REPORTID")
@

ALTER TABLE "EMOC3"."REPORTPARAMETERS" ADD CONSTRAINT "FK_REPPARAM_REF_REPORTS" FOREIGN KEY
	("REPORTID")
	REFERENCES "EMOC3"."REPORTS"
	("REPORTID")
@

ALTER TABLE "EMOC3"."REPORTS" ADD CONSTRAINT "FK_RPT_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."REPORTS" ADD CONSTRAINT "USERID_FK" FOREIGN KEY
	("USERID")
	REFERENCES "EMOC3"."USERS"
	("USERID")
@

ALTER TABLE "EMOC3"."SCHEDULE" ADD CONSTRAINT "FK_SCHEDULE_REF_AREAS" FOREIGN KEY
	("AREAID")
	REFERENCES "EMOC3"."AREAS"
	("AREAID")
@

ALTER TABLE "EMOC3"."SCHEDULE" ADD CONSTRAINT "FK_SCHEDULE_REF_CAUSECODE" FOREIGN KEY
	("CAUSECODEID")
	REFERENCES "EMOC3"."CAUSECODES"
	("CAUSECODEID")
@

ALTER TABLE "EMOC3"."SCHEDULE" ADD CONSTRAINT "FK_SCHEDULE_REF_DEVIATION" FOREIGN KEY
	("DEVIATIONCODEID")
	REFERENCES "EMOC3"."DEVIATIONCODES"
	("DEVIATIONCODEID")
@

ALTER TABLE "EMOC3"."SCHEDULE" ADD CONSTRAINT "FK_SCHEDULE_REF_LANDINGCODES" FOREIGN KEY
	("LANDINGCODEID")
	REFERENCES "EMOC3"."LANDINGCODES"
	("LANDINGCODEID")
@

ALTER TABLE "EMOC3"."SCHEDULE" ADD CONSTRAINT "FK_SCHEDULE_REF_MISSIONS" FOREIGN KEY
	("MISSIONID")
	REFERENCES "EMOC3"."MISSIONS"
	("MISSIONID")
@

ALTER TABLE "EMOC3"."SCHEDULE" ADD CONSTRAINT "FK_SCHEDULE_REF_PILOT" FOREIGN KEY
	("PILOTID")
	REFERENCES "EMOC3"."PILOT"
	("PILOTID")
@

ALTER TABLE "EMOC3"."SCHEDULE" ADD CONSTRAINT "FK_SCHEDULE_REF_RANGES" FOREIGN KEY
	("RANGEID")
	REFERENCES "EMOC3"."RANGES"
	("RANGEID")
@

ALTER TABLE "EMOC3"."SCHEDULE" ADD CONSTRAINT "FK_SCHEDULE_REF_SQUADRONS" FOREIGN KEY
	("SQUADRONID")
	REFERENCES "EMOC3"."SQUADRONS"
	("SQUADRONID")
@

ALTER TABLE "EMOC3"."SCHEDULE" ADD CONSTRAINT "FK_SCHED_REF_MAINTREMARKS" FOREIGN KEY
	("MAINTREMARKS")
	REFERENCES "EMOC3"."REMARKS"
	("REMARKSID")
@

ALTER TABLE "EMOC3"."SCHEDULE" ADD CONSTRAINT "FK_SCHED_REF_SCHEDREMARKS" FOREIGN KEY
	("SCHEDULEREMARKS")
	REFERENCES "EMOC3"."REMARKS"
	("REMARKSID")
@

ALTER TABLE "EMOC3"."SCHEDULEDEVIATIONS" ADD CONSTRAINT "FK_AIRCRAFT_REF_DEVREMARKS" FOREIGN KEY
	("DEVIATIONSREMARKS")
	REFERENCES "EMOC3"."REMARKS"
	("REMARKSID")
@

ALTER TABLE "EMOC3"."SCHEDULEDEVIATIONS" ADD CONSTRAINT "FK_SCHEDDEV_REF_INTERFACELOG" FOREIGN KEY
	("INTERFACELOGID")
	REFERENCES "EMOC3"."INTERFACELOG"
	("INTERFACELOGID")
@

ALTER TABLE "EMOC3"."SCHEDULESTATUS" ADD CONSTRAINT "FK_SCHEDULESTAT_REF_FUELSTATUS" FOREIGN KEY
	("FUELSTATUSID")
	REFERENCES "EMOC3"."FUEL"
	("FUELSTATUSID")
@

ALTER TABLE "EMOC3"."SCHEDULESTATUS" ADD CONSTRAINT "FK_SCHEDULESTAT_REF_STATUSCODE" FOREIGN KEY
	("STATUSCODEID")
	REFERENCES "EMOC3"."STATUSCODE"
	("STATUSCODEID")
@

ALTER TABLE "EMOC3"."SEMEDX" ADD CONSTRAINT "FK_EDX_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."SEMEDXDATA" ADD CONSTRAINT "FK_SEMEDXDATA_REF_SCHED" FOREIGN KEY
	("SCHEDULEID")
	REFERENCES "EMOC3"."SCHEDULE"
	("SCHEDULEID")
@

ALTER TABLE "EMOC3"."SEMEDXDATA" ADD CONSTRAINT "FK_SEMEDXDA_REFERENCE_AIRCRAFT" FOREIGN KEY
	("ENGINEDATAID")
	REFERENCES "EMOC3"."AIRCRAFTENGINEDATA"
	("ENGINEDATAID")
@

ALTER TABLE "EMOC3"."SEMEDXDATA" ADD CONSTRAINT "FK_SEMEDXDA_REFERENCE_SEMEDX" FOREIGN KEY
	("SEMEDXID")
	REFERENCES "EMOC3"."SEMEDX"
	("SEMEDXID")
@

ALTER TABLE "EMOC3"."SHOPDISPATCH" ADD CONSTRAINT "FK_SHOPDISP_REFERENCE_AIRCRAFT" FOREIGN KEY
	("AIRCRAFTID")
	REFERENCES "EMOC3"."AIRCRAFT"
	("AIRCRAFTID")
@

ALTER TABLE "EMOC3"."SQUADRONS" ADD CONSTRAINT "FK_SQUADRON_REFERENCE_COLORS" FOREIGN KEY
	("COLORID")
	REFERENCES "EMOC3"."COLORS"
	("COLORID")
@

ALTER TABLE "EMOC3"."SQUADRONS" ADD CONSTRAINT "FK_SQ_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."SQUADRON_SORT_ORDER" ADD CONSTRAINT "FK_SQSORTORDER_REF_SQUADRONS" FOREIGN KEY
	("SQUADRONID")
	REFERENCES "EMOC3"."SQUADRONS"
	("SQUADRONID")
@

ALTER TABLE "EMOC3"."SQUADRON_SORT_ORDER" ADD CONSTRAINT "FK_SQSORTORDER_REF_USERS" FOREIGN KEY
	("USERID")
	REFERENCES "EMOC3"."USERS"
	("USERID")
@

ALTER TABLE "EMOC3"."STATIONLOCCODES" ADD CONSTRAINT "FK_SLC_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."STATUSCODE" ADD CONSTRAINT "FK_STATUS_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."STATUSTRANSITIONRULE" ADD CONSTRAINT "FK_STATUSTR_REFERENCE_STATUSCO" FOREIGN KEY
	("STATUSCODEID")
	REFERENCES "EMOC3"."STATUSCODE"
	("STATUSCODEID")
@

ALTER TABLE "EMOC3"."STATUSTRANSITIONRULE" ADD CONSTRAINT "FK_TRANSITION2_REFERENCE_STATU" FOREIGN KEY
	("TRANSITION2ID")
	REFERENCES "EMOC3"."STATUSCODE"
	("STATUSCODEID")
@

ALTER TABLE "EMOC3"."STATUSTRANSITIONRULE" ADD CONSTRAINT "STR_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."SYMBOLS" ADD CONSTRAINT "FK_SYMBOLS_REFERENCE_CONDITIO" FOREIGN KEY
	("CONDCODEID")
	REFERENCES "EMOC3"."CONDITIONCODES"
	("CONDCODEID")
@

ALTER TABLE "EMOC3"."SYMBOLS" ADD CONSTRAINT "FK_SYMBOL_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."TBMCSINTERFACELOG" ADD CONSTRAINT "FK_TILOG_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."USERIMAGES" ADD CONSTRAINT "FK_USERID" FOREIGN KEY
	("USERID")
	REFERENCES "EMOC3"."USERS"
	("USERID")
@

ALTER TABLE "EMOC3"."UTILIZATIONCODES" ADD CONSTRAINT "FK_UTC_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."WEAPONSCLASS" ADD CONSTRAINT "FK_WEAPC_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."WEAPONSINFO" ADD CONSTRAINT "FK_WEAPI_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."WEAPONSINFO" ADD CONSTRAINT "FK_WEAPONSINFO_REF_SCLS" FOREIGN KEY
	("COMBATSCLID")
	REFERENCES "EMOC3"."COMBATSCLS"
	("COMBATSCLID")
@

ALTER TABLE "EMOC3"."WEAPONSLOAD" ADD CONSTRAINT "FK_WEAPONSLOAD_REF_ORDNANCE" FOREIGN KEY
	("ORDNANCEID")
	REFERENCES "EMOC3"."ORDNANCE"
	("ORDNANCEID")
@

ALTER TABLE "EMOC3"."WEAPONSLOAD" ADD CONSTRAINT "FK_WEAPONS_REF_AIRCRAFT" FOREIGN KEY
	("AIRCRAFTID")
	REFERENCES "EMOC3"."AIRCRAFT"
	("AIRCRAFTID")
@

ALTER TABLE "EMOC3"."WEAPONSLOAD" ADD CONSTRAINT "FK_WEPLOAD_REF_FIRESYMB" FOREIGN KEY
	("FIRESYMBOLID")
	REFERENCES "EMOC3"."FIRESYMBOLS"
	("FIRESYMBOLID")
@

ALTER TABLE "EMOC3"."WEAPONTYPES" ADD CONSTRAINT "FK_WEAPT_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."WHENDISCOVEREDCODES" ADD CONSTRAINT "FK_WDC_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."WINGS" ADD CONSTRAINT "FK_WING_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."WORKCENTERS" ADD CONSTRAINT "FK_WRKC_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@

ALTER TABLE "EMOC3"."WRITEUPS" ADD CONSTRAINT "FK_WRITEUPS_REFERENCE_AIRCRAFT" FOREIGN KEY
	("AIRCRAFTID")
	REFERENCES "EMOC3"."AIRCRAFT"
	("AIRCRAFTID")
@

ALTER TABLE "EMOC3"."WRITEUPS" ADD CONSTRAINT "FK_WRITEUPS_REFERENCE_SYMBOLS" FOREIGN KEY
	("SYMBOLID")
	REFERENCES "EMOC3"."SYMBOLS"
	("SYMBOLID")
@

ALTER TABLE "EMOC3"."WX" ADD CONSTRAINT "FK_WX_REF_MOC" FOREIGN KEY
	("MOCID")
	REFERENCES "EMOC3"."MOC"
	("MOCID")
@
