--<ScriptOptions statementTerminator="@"/>


ALTER TABLE "EMOC3"."ACFTMDSTYPES" ADD CONSTRAINT "SYS_C0010987" CHECK ("ACFTMDSTYPECD" IS NOT NULL)
@

ALTER TABLE "EMOC3"."ACFTMDSTYPES" ADD CONSTRAINT "SYS_C0010988" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."AIRCRAFT" ADD CONSTRAINT "SYS_C0010990" CHECK ("TAILNUMBER" IS NOT NULL)
@

ALTER TABLE "EMOC3"."AIRCRAFT" ADD CONSTRAINT "SYS_C0010991" CHECK ("SHORTTAILNUMBER" IS NOT NULL)
@

ALTER TABLE "EMOC3"."AIRCRAFT" ADD CONSTRAINT "SYS_C0010992" CHECK ("SQUADRONID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."AIRCRAFT" ADD CONSTRAINT "SYS_C0010993" CHECK ("AIRCRAFTMDSID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."AIRCRAFT" ADD CONSTRAINT "SYS_C0010994" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."AIRCRAFT" ADD CONSTRAINT "SYS_C0010995" CHECK ("COUNTRYCODE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."AIRCRAFTCUSTOMDATA" ADD CONSTRAINT "SYS_C0010997" CHECK ("AIRCRAFTID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."AIRCRAFTCUSTOMDATA" ADD CONSTRAINT "SYS_C0010998" CHECK ("CUSTOMDATAID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."AIRCRAFTENGINEDATA" ADD CONSTRAINT "SYS_C0011000" CHECK ("ENGINEDATAID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."AIRCRAFTENGINEDATA" ADD CONSTRAINT "SYS_C0011001" CHECK ("AIRCRAFTID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."AIRCRAFTENGINEDATA" ADD CONSTRAINT "SYS_C0011002" CHECK ("ENGINENUMBER" IS NOT NULL)
@

ALTER TABLE "EMOC3"."AIRCRAFTMDS" ADD CONSTRAINT "SYS_C0011004" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."AIRCRAFTSTATUSUPDATE" ADD CONSTRAINT "SYS_C0011006" CHECK ("STATUSUPDATEID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."AIRCRAFTSTATUSUPDATE" ADD CONSTRAINT "SYS_C0011007" CHECK ("EQUIPMENTID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."AIRCRAFTSTATUSUPDATE" ADD CONSTRAINT "SYS_C0011008" CHECK ("AIRCRAFTID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."AREAS" ADD CONSTRAINT "SYS_C0011009" CHECK ("AREAID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."AREAS" ADD CONSTRAINT "SYS_C0011010" CHECK ("AREA" IS NOT NULL)
@

ALTER TABLE "EMOC3"."AREAS" ADD CONSTRAINT "SYS_C0011011" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."ARMAMENT" ADD CONSTRAINT "SYS_C0011013" CHECK ("STATION" IS NOT NULL)
@

ALTER TABLE "EMOC3"."ARMAMENT" ADD CONSTRAINT "SYS_C0011014" CHECK ("ARMAMENTID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."ARMAMENT" ADD CONSTRAINT "SYS_C0011015" CHECK ("AIRCRAFTMDSID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."ARMAMENT" ADD CONSTRAINT "SYS_C0011016" CHECK ("ORDNANCEID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."ARMAMENT" ADD CONSTRAINT "SYS_C0011017" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."ASSIGNMENTCODES" ADD CONSTRAINT "SYS_C0011019" CHECK ("ASSIGNMENTCODEID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."ASSIGNMENTCODES" ADD CONSTRAINT "SYS_C0011020" CHECK ("ASSIGNMENTCODE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."ASSIGNMENTCODES" ADD CONSTRAINT "SYS_C0011021" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."BASEMAPS" ADD CONSTRAINT "SYS_C0011022" CHECK ("MAPID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."BASEMAPS" ADD CONSTRAINT "SYS_C0011023" CHECK ("MAPOBJECT" IS NOT NULL)
@

ALTER TABLE "EMOC3"."BASEMAPS" ADD CONSTRAINT "SYS_C0011024" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."BASEMAPS" ADD CONSTRAINT "SYS_C0011025" CHECK ("MIMETYPE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."BRIEF_AIRCRAFT_STATUS" ADD CONSTRAINT "SYS_C0011027" CHECK ("ACSTATBRIEFID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."BRIEF_AIRCRAFT_STATUS" ADD CONSTRAINT "SYS_C0011028" CHECK ("BRIEFDATE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."BRIEF_DEVIATIONS" ADD CONSTRAINT "SYS_C0011029" CHECK ("DEVBRIEFID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."BRIEF_DEVIATIONS" ADD CONSTRAINT "SYS_C0011030" CHECK ("BRIEFDATE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."BRIEF_FLYING_SCHEDULE" ADD CONSTRAINT "SYS_C0011031" CHECK ("FLYSCHEDBRIEFID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."BRIEF_FLYING_SCHEDULE" ADD CONSTRAINT "SYS_C0011032" CHECK ("BRIEFDATE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."BRIEF_FLYING_STATUS" ADD CONSTRAINT "SYS_C0011033" CHECK ("FLYINGSTATUSBRIEFID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."BRIEF_FLYING_STATUS" ADD CONSTRAINT "SYS_C0011034" CHECK ("BRIEFDATE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."BRIEF_HANGAR_QUEEN" ADD CONSTRAINT "SYS_C0011035" CHECK ("HQBRIEFID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."BRIEF_HANGAR_QUEEN" ADD CONSTRAINT "SYS_C0011036" CHECK ("SHOW" IS NOT NULL)
@

ALTER TABLE "EMOC3"."BRIEF_HANGAR_QUEEN" ADD CONSTRAINT "SYS_C0011037" CHECK ("AIRCRAFTMDS" IS NOT NULL)
@

ALTER TABLE "EMOC3"."BRIEF_HANGAR_QUEEN" ADD CONSTRAINT "SYS_C0011038" CHECK ("TAILNUMBER" IS NOT NULL)
@

ALTER TABLE "EMOC3"."BRIEF_HANGAR_QUEEN" ADD CONSTRAINT "SYS_C0011039" CHECK ("SQUADRON" IS NOT NULL)
@

ALTER TABLE "EMOC3"."BRIEF_HANGAR_QUEEN" ADD CONSTRAINT "SYS_C0011040" CHECK ("BRIEFDATE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."BRIEF_MICAPS" ADD CONSTRAINT "SYS_C0011041" CHECK ("MICAPBRIEFID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."BRIEF_MICAPS" ADD CONSTRAINT "SYS_C0011042" CHECK ("BRIEFDATE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."BRIEF_NEXT_WEEKS_PLAN" ADD CONSTRAINT "SYS_C0011043" CHECK ("NXTWKSPLANBRIEFID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."BRIEF_NEXT_WEEKS_PLAN" ADD CONSTRAINT "SYS_C0011044" CHECK ("BRIEFDATE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."BRIEF_POT_HANGAR_QUEEN" ADD CONSTRAINT "SYS_C0011045" CHECK ("POTHQBRIEFID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."BRIEF_POT_HANGAR_QUEEN" ADD CONSTRAINT "SYS_C0011046" CHECK ("SHOW" IS NOT NULL)
@

ALTER TABLE "EMOC3"."BRIEF_POT_HANGAR_QUEEN" ADD CONSTRAINT "SYS_C0011047" CHECK ("AIRCRAFTMDS" IS NOT NULL)
@

ALTER TABLE "EMOC3"."BRIEF_POT_HANGAR_QUEEN" ADD CONSTRAINT "SYS_C0011048" CHECK ("TAILNUMBER" IS NOT NULL)
@

ALTER TABLE "EMOC3"."BRIEF_POT_HANGAR_QUEEN" ADD CONSTRAINT "SYS_C0011049" CHECK ("SQUADRON" IS NOT NULL)
@

ALTER TABLE "EMOC3"."BRIEF_POT_HANGAR_QUEEN" ADD CONSTRAINT "SYS_C0011050" CHECK ("BRIEFDATE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."BRIEF_SCHEDULE_OVERVIEW" ADD CONSTRAINT "SYS_C0011051" CHECK ("SCHEDOVERBRIEFID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."BRIEF_SCHEDULE_OVERVIEW" ADD CONSTRAINT "SYS_C0011052" CHECK ("BRIEFDATE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."BRIEF_WING_STATUS" ADD CONSTRAINT "SYS_C0011053" CHECK ("WINGSTATUSBRIEFID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."BRIEF_WING_STATUS" ADD CONSTRAINT "SYS_C0011054" CHECK ("BRIEFDATE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."CAUSECODES" ADD CONSTRAINT "SYS_C0011055" CHECK ("CAUSECODEID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."CAUSECODES" ADD CONSTRAINT "SYS_C0011056" CHECK ("CAUSECODE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."CAUSECODES" ADD CONSTRAINT "SYS_C0011057" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."CHANGENOTIFICATION" ADD CONSTRAINT "SYS_C0011060" CHECK ("CHANGEID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."CHANGENOTIFICATION" ADD CONSTRAINT "SYS_C0011061" CHECK ("CACHEDTABLENAME" IS NOT NULL)
@

ALTER TABLE "EMOC3"."CHANGENOTIFICATION" ADD CONSTRAINT "SYS_C0011062" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."CHECKLIST" ADD CONSTRAINT "SYS_C0011063" CHECK ("CHECKLISTID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."CHECKLIST" ADD CONSTRAINT "SYS_C0011064" CHECK ("CHECKLIST" IS NOT NULL)
@

ALTER TABLE "EMOC3"."CHECKLIST" ADD CONSTRAINT "SYS_C0011065" CHECK ("CHECKLISTTITLE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."CHECKLIST" ADD CONSTRAINT "SYS_C0011066" CHECK ("DATEUPLOADED" IS NOT NULL)
@

ALTER TABLE "EMOC3"."CHECKLIST" ADD CONSTRAINT "SYS_C0011067" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."COLORRULES" ADD CONSTRAINT "SYS_C0011069" CHECK ("COLORID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."COLORRULES" ADD CONSTRAINT "SYS_C0011070" CHECK ("COLORRULESID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."COLORRULES" ADD CONSTRAINT "SYS_C0011071" CHECK ("COLORRANK" IS NOT NULL)
@

ALTER TABLE "EMOC3"."COLORRULES" ADD CONSTRAINT "SYS_C0011072" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."COLORS" ADD CONSTRAINT "SYS_C0011074" CHECK ("COLORID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."COLORS" ADD CONSTRAINT "SYS_C0011075" CHECK ("COLORNAME" IS NOT NULL)
@

ALTER TABLE "EMOC3"."COLORS" ADD CONSTRAINT "SYS_C0011076" CHECK ("COLORVALUE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."COLORS" ADD CONSTRAINT "SYS_C0011077" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."COMBATSCLRULES" ADD CONSTRAINT "SYS_C0011079" CHECK ("SCLRULESID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."COMBATSCLRULES" ADD CONSTRAINT "SYS_C0011080" CHECK ("AIRCRAFTMDSID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."COMBATSCLRULES" ADD CONSTRAINT "SYS_C0011081" CHECK ("COMBATSCLID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."COMBATSCLRULES" ADD CONSTRAINT "SYS_C0011082" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."COMBATSCLS" ADD CONSTRAINT "SYS_C0011083" CHECK ("COMBATSCL" IS NOT NULL)
@

ALTER TABLE "EMOC3"."COMBATSCLS" ADD CONSTRAINT "SYS_C0011084" CHECK ("COMBATSCLID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."COMBATSCLS" ADD CONSTRAINT "SYS_C0011085" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."CONDITIONCODES" ADD CONSTRAINT "SYS_C0011087" CHECK ("CONDCODEID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."CONDITIONCODES" ADD CONSTRAINT "SYS_C0011088" CHECK ("CONDITIONCODE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."CONDITIONCODES" ADD CONSTRAINT "SYS_C0011089" CHECK ("DEFAULTCONDITIONCODE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."CONDITIONCODES" ADD CONSTRAINT "SYS_C0011090" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."CONDITIONSTATUS" ADD CONSTRAINT "SYS_C0011092" CHECK ("CONDSTATID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."CONDITIONSTATUS" ADD CONSTRAINT "SYS_C0011093" CHECK ("CONDITIONSTATUS" IS NOT NULL)
@

ALTER TABLE "EMOC3"."CONDITIONSTATUS" ADD CONSTRAINT "SYS_C0011094" CHECK ("FLYABLE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."CONDITIONSTATUS" ADD CONSTRAINT "SYS_C0011095" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."COUNTRYCODES" ADD CONSTRAINT "SYS_C0011097" CHECK ("COUNTRYCODE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."COUNTRYCODES" ADD CONSTRAINT "SYS_C0011098" CHECK ("COUNTRYNAME" IS NOT NULL)
@

ALTER TABLE "EMOC3"."COUNTRYCODES" ADD CONSTRAINT "SYS_C0011099" CHECK ("DEFAULTCOUNTRY" IS NOT NULL)
@

ALTER TABLE "EMOC3"."CREWCHIEFS" ADD CONSTRAINT "SYS_C0011101" CHECK ("CREWCHIEFID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."CREWCHIEFS" ADD CONSTRAINT "SYS_C0011102" CHECK ("CREWCHIEF" IS NOT NULL)
@

ALTER TABLE "EMOC3"."CREWCHIEFS" ADD CONSTRAINT "SYS_C0011103" CHECK ("DEFAULTCREWCHIEF" IS NOT NULL)
@

ALTER TABLE "EMOC3"."CREWCHIEFS" ADD CONSTRAINT "SYS_C0011104" CHECK ("RANKID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."CREWCHIEFS" ADD CONSTRAINT "SYS_C0011105" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."CUSTOMDATA" ADD CONSTRAINT "SYS_C0011107" CHECK ("CUSTOMDATAID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."CUSTOMDATA" ADD CONSTRAINT "SYS_C0011108" CHECK ("CUSTOMDATALABEL" IS NOT NULL)
@

ALTER TABLE "EMOC3"."CUSTOMDATA" ADD CONSTRAINT "SYS_C0011109" CHECK ("CUSTOMDATATYPE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."CUSTOMDATA" ADD CONSTRAINT "SYS_C0011110" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."CUSTOMDATALISTITEM" ADD CONSTRAINT "SYS_C0011112" CHECK ("CUSTOMDATAITEMID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."CUSTOMDATALISTITEM" ADD CONSTRAINT "SYS_C0011113" CHECK ("CUSTOMDATAID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."CUSTOMDATAMDS" ADD CONSTRAINT "SYS_C0011115" CHECK ("CUSTOMDATAID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."CUSTOMDATAMDS" ADD CONSTRAINT "SYS_C0011116" CHECK ("AIRCRAFTMDSID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."DEVIATIONABORTTRX" ADD CONSTRAINT "SYS_C0011118" CHECK ("DEVIATIONABORTTRXID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."DEVIATIONCODES" ADD CONSTRAINT "SYS_C0011119" CHECK ("DEVIATIONCODEID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."DEVIATIONCODES" ADD CONSTRAINT "SYS_C0011120" CHECK ("DEVIATIONCODE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."DEVIATIONCODES" ADD CONSTRAINT "SYS_C0011121" CHECK ("DEFAULTDEVIATIONCODE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."DEVIATIONCODES" ADD CONSTRAINT "SYS_C0011122" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."DEVIATIONCORRECTIONTRX" ADD CONSTRAINT "SYS_C0011125" CHECK ("DEVIATIONCORRECTTRXID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."DEVIATIONDELETETRX" ADD CONSTRAINT "SYS_C0011126" CHECK ("DEVIATIONDELETETRXID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."DEVIATIONSTARTSTOPTRX" ADD CONSTRAINT "SYS_C0011127" CHECK ("DEVIATIONSTARTSTOPTRXID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."EMOCAPPCONFIGURATION" ADD CONSTRAINT "SYS_C0011128" CHECK ("CONFIGID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."EMOCCONFIG" ADD CONSTRAINT "SYS_C0011130" CHECK ("EMOCCONFIGID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."EMOCCONFIG" ADD CONSTRAINT "SYS_C0011131" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."EMOCHELP" ADD CONSTRAINT "SYS_C0011133" CHECK ("HELPID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."EMOCHELP" ADD CONSTRAINT "SYS_C0011134" CHECK ("TOPIC" IS NOT NULL)
@

ALTER TABLE "EMOC3"."ENGINERUNLOG" ADD CONSTRAINT "SYS_C0011136" CHECK ("ENGINELOGID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."ENGINERUNLOG" ADD CONSTRAINT "SYS_C0011137" CHECK ("MOCCONTROLLER" IS NOT NULL)
@

ALTER TABLE "EMOC3"."ENGINERUNLOG" ADD CONSTRAINT "SYS_C0011138" CHECK ("RUNPERSON" IS NOT NULL)
@

ALTER TABLE "EMOC3"."ENGINERUNLOG" ADD CONSTRAINT "SYS_C0011139" CHECK ("EMPLOYEENUMBER" IS NOT NULL)
@

ALTER TABLE "EMOC3"."ENGINERUNLOG" ADD CONSTRAINT "SYS_C0011140" CHECK ("RUNDATE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."ENGINERUNLOG" ADD CONSTRAINT "SYS_C0011141" CHECK ("ENGINEDATAID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."ENGINERUNLOG" ADD CONSTRAINT "SYS_C0011142" CHECK ("AIRCRAFTID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."EVENTLOG" ADD CONSTRAINT "SYS_C0011144" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."FIELDNAMES" ADD CONSTRAINT "SYS_C0011145" CHECK ("FIELDNAMESID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."FIELDNAMES" ADD CONSTRAINT "SYS_C0011146" CHECK ("SHOW" IS NOT NULL)
@

ALTER TABLE "EMOC3"."FIRESYMBOLS" ADD CONSTRAINT "SYS_C0011148" CHECK ("FIRESYMBOLID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."FIRESYMBOLS" ADD CONSTRAINT "SYS_C0011149" CHECK ("FIRESYMBOL" IS NOT NULL)
@

ALTER TABLE "EMOC3"."FIRESYMBOLS" ADD CONSTRAINT "SYS_C0011150" CHECK ("RANKING" IS NOT NULL)
@

ALTER TABLE "EMOC3"."FIRESYMBOLS" ADD CONSTRAINT "SYS_C0011151" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."FLIGHTS" ADD CONSTRAINT "SYS_C0011153" CHECK ("FLIGHTID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."FLIGHTS" ADD CONSTRAINT "SYS_C0011154" CHECK ("SQUADRONID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."FLIGHTS" ADD CONSTRAINT "SYS_C0011155" CHECK ("FLIGHTNAME" IS NOT NULL)
@

ALTER TABLE "EMOC3"."FUEL" ADD CONSTRAINT "SYS_C0011157" CHECK ("FUELSTATUSID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."FUEL" ADD CONSTRAINT "SYS_C0011158" CHECK ("COLORID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."FUEL" ADD CONSTRAINT "SYS_C0011159" CHECK ("FUELSTATUS" IS NOT NULL)
@

ALTER TABLE "EMOC3"."FUEL" ADD CONSTRAINT "SYS_C0011160" CHECK ("LANDING" IS NOT NULL)
@

ALTER TABLE "EMOC3"."FUEL" ADD CONSTRAINT "SYS_C0011161" CHECK ("DEFAULTFUEL" IS NOT NULL)
@

ALTER TABLE "EMOC3"."FUEL" ADD CONSTRAINT "SYS_C0011162" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."GENERATIONFLOW" ADD CONSTRAINT "SYS_C0011165" CHECK ("GENERATIONFLOWNAME" IS NOT NULL)
@

ALTER TABLE "EMOC3"."GENERATIONFLOW" ADD CONSTRAINT "SYS_C0011166" CHECK ("GENERATIONFLOWSTARTTIME" IS NOT NULL)
@

ALTER TABLE "EMOC3"."GENERATIONFLOW" ADD CONSTRAINT "SYS_C0011167" CHECK ("GENERATIONFLOWITEMOFFSET" IS NOT NULL)
@

ALTER TABLE "EMOC3"."GENERATIONFLOW" ADD CONSTRAINT "SYS_C0011168" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."GENERATIONFLOWITEMS" ADD CONSTRAINT "SYS_C0011170" CHECK ("ITEMNUMBER" IS NOT NULL)
@

ALTER TABLE "EMOC3"."GENERATIONFLOWITEMS" ADD CONSTRAINT "SYS_C0011171" CHECK ("ITEM" IS NOT NULL)
@

ALTER TABLE "EMOC3"."GENERATIONFLOWITEMS" ADD CONSTRAINT "SYS_C0011172" CHECK ("GENERATIONFLOWNAME" IS NOT NULL)
@

ALTER TABLE "EMOC3"."GENERATIONFLOWPROGRESS" ADD CONSTRAINT "SYS_C0011174" CHECK ("GENERATIONFLOWNAME" IS NOT NULL)
@

ALTER TABLE "EMOC3"."GENERATIONFLOWPROGRESS" ADD CONSTRAINT "SYS_C0011175" CHECK ("STEPNUMBER" IS NOT NULL)
@

ALTER TABLE "EMOC3"."GENERATIONFLOWPROGRESS" ADD CONSTRAINT "SYS_C0011176" CHECK ("ITEMNUMBER" IS NOT NULL)
@

ALTER TABLE "EMOC3"."GENERATIONFLOWSTEPS" ADD CONSTRAINT "SYS_C0011178" CHECK ("STEPNUMBER" IS NOT NULL)
@

ALTER TABLE "EMOC3"."GENERATIONFLOWSTEPS" ADD CONSTRAINT "SYS_C0011179" CHECK ("STEPNAME" IS NOT NULL)
@

ALTER TABLE "EMOC3"."GENERATIONFLOWSTEPS" ADD CONSTRAINT "SYS_C0011180" CHECK ("STEPLENGTH" IS NOT NULL)
@

ALTER TABLE "EMOC3"."GENERATIONFLOWSTEPS" ADD CONSTRAINT "SYS_C0011181" CHECK ("GENERATIONFLOWNAME" IS NOT NULL)
@

ALTER TABLE "EMOC3"."GLOBALCHANGENOTIFICATION" ADD CONSTRAINT "SYS_C0011184" CHECK ("CHANGEID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."GLOBALCHANGENOTIFICATION" ADD CONSTRAINT "SYS_C0011185" CHECK ("CACHEDTABLENAME" IS NOT NULL)
@

ALTER TABLE "EMOC3"."GRADECODES" ADD CONSTRAINT "SYS_C0011186" CHECK ("RANKDESCRIPTION" IS NOT NULL)
@

ALTER TABLE "EMOC3"."GRADECODES" ADD CONSTRAINT "SYS_C0011187" CHECK ("RANKCODE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."HANGER_QUEEN_CODE" ADD CONSTRAINT "SYS_C0011188" CHECK ("HQCODEID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."HANGER_QUEEN_CODE" ADD CONSTRAINT "SYS_C0011189" CHECK ("HQCODE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."HANGER_QUEEN_CODE" ADD CONSTRAINT "SYS_C0011190" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."HISTORY" ADD CONSTRAINT "SYS_C0011192" CHECK ("HISTORYID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."HISTORY" ADD CONSTRAINT "SYS_C0011193" CHECK ("EVENTDATE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."HISTORY" ADD CONSTRAINT "SYS_C0011194" CHECK ("USERID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."HISTORY" ADD CONSTRAINT "SYS_C0011195" CHECK ("AIRCRAFTID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."HOTSPOTS" ADD CONSTRAINT "SYS_C0011197" CHECK ("FIELDNAME" IS NOT NULL)
@

ALTER TABLE "EMOC3"."HOTSPOTS" ADD CONSTRAINT "SYS_C0011198" CHECK ("LOCATIONID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."HOTSPOTS" ADD CONSTRAINT "SYS_C0011199" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."IMDSCDBELCUNITOPTION" ADD CONSTRAINT "SYS_C0011201" CHECK ("IMDSCDBINTERFACEOPTIONID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."IMDSCDBELCUNITOPTION" ADD CONSTRAINT "SYS_C0011202" CHECK ("ENTERPRISELOCATIONCODE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."IMDSCDBELCUNITOPTION" ADD CONSTRAINT "SYS_C0011203" CHECK ("UNITID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."IMDSCDBELCUNITOPTION" ADD CONSTRAINT "SYS_C0011204" CHECK ("OPTIONENABLED" IS NOT NULL)
@

ALTER TABLE "EMOC3"."IMDSCDBINTERFACEOPTION" ADD CONSTRAINT "SYS_C0011206" CHECK ("IMDSCDBINTERFACEOPTIONID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."IMDSCDBINTERFACEOPTION" ADD CONSTRAINT "SYS_C0011207" CHECK ("OPTIONNAME" IS NOT NULL)
@

ALTER TABLE "EMOC3"."IMDSCDBINTERFACEOPTION" ADD CONSTRAINT "SYS_C0011208" CHECK ("OPTIONENABLED" IS NOT NULL)
@

ALTER TABLE "EMOC3"."IMDSCDBINTERFACEOPTION" ADD CONSTRAINT "SYS_C0011209" CHECK ("INTERFACEDIRECTION" IS NOT NULL)
@

ALTER TABLE "EMOC3"."IMDSLOGINS" ADD CONSTRAINT "SYS_C0011211" CHECK ("IMDSLOGINID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."IMDSLOGINS" ADD CONSTRAINT "SYS_C0011212" CHECK ("USERID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."IMDSLOGINS" ADD CONSTRAINT "SYS_C0011213" CHECK ("IMDSLOGIN" IS NOT NULL)
@

ALTER TABLE "EMOC3"."IMDSLOGINS" ADD CONSTRAINT "SYS_C0011214" CHECK ("IMDSPASSWORD" IS NOT NULL)
@

ALTER TABLE "EMOC3"."INTERFACECONTROL" ADD CONSTRAINT "SYS_C0011216" CHECK ("INTERFACECONTROLID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."INTERFACECONTROL" ADD CONSTRAINT "SYS_C0011217" CHECK ("INTERFACENAME" IS NOT NULL)
@

ALTER TABLE "EMOC3"."INTERFACECONTROL" ADD CONSTRAINT "SYS_C0011218" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."INTERFACEHISTORY" ADD CONSTRAINT "SYS_C0011220" CHECK ("STATUSCHANGETIME" IS NOT NULL)
@

ALTER TABLE "EMOC3"."INTERFACEHISTORY" ADD CONSTRAINT "SYS_C0011221" CHECK ("STATUSCHANGEBY" IS NOT NULL)
@

ALTER TABLE "EMOC3"."INTERFACEHISTORY" ADD CONSTRAINT "SYS_C0011222" CHECK ("CURRENTSTATUS" IS NOT NULL)
@

ALTER TABLE "EMOC3"."INTERFACEHISTORY" ADD CONSTRAINT "SYS_C0011223" CHECK ("INTERFACECONTROLID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."INTERFACEHISTORY" ADD CONSTRAINT "SYS_C0011224" CHECK ("CURRENTENABLED" IS NOT NULL)
@

ALTER TABLE "EMOC3"."INTERFACEITEMS" ADD CONSTRAINT "SYS_C0011225" CHECK ("INTERFACEITEMID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."INTERFACEITEMS" ADD CONSTRAINT "SYS_C0011226" CHECK ("INTERFACECONTROLID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."INTERFACEITEMS" ADD CONSTRAINT "SYS_C0011227" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."INTERFACEITEMSHISTORY" ADD CONSTRAINT "SYS_C0011229" CHECK ("STATUSCHANGETIME" IS NOT NULL)
@

ALTER TABLE "EMOC3"."INTERFACEITEMSHISTORY" ADD CONSTRAINT "SYS_C0011230" CHECK ("STATUSCHANGEBY" IS NOT NULL)
@

ALTER TABLE "EMOC3"."INTERFACEITEMSHISTORY" ADD CONSTRAINT "SYS_C0011231" CHECK ("INTERFACECONTROLID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."INTERFACEITEMSHISTORY" ADD CONSTRAINT "SYS_C0011232" CHECK ("INTERFACEITEMID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."INTERFACELOG" ADD CONSTRAINT "SYS_C0011233" CHECK ("INTERFACELOGID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."INTERFACELOG" ADD CONSTRAINT "SYS_C0011234" CHECK ("INTERFACECONTROLID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."INTERFACELOG" ADD CONSTRAINT "SYS_C0011235" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."JOAP" ADD CONSTRAINT "SYS_C0011239" CHECK ("JOAPID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."JOAP" ADD CONSTRAINT "SYS_C0011240" CHECK ("JOAPCODE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."JOAP" ADD CONSTRAINT "SYS_C0011241" CHECK ("LANDING" IS NOT NULL)
@

ALTER TABLE "EMOC3"."JOAP" ADD CONSTRAINT "SYS_C0011242" CHECK ("REDCAPSTATUS" IS NOT NULL)
@

ALTER TABLE "EMOC3"."JOAP" ADD CONSTRAINT "SYS_C0011243" CHECK ("DEFAULTJOAP" IS NOT NULL)
@

ALTER TABLE "EMOC3"."JOAP" ADD CONSTRAINT "SYS_C0011244" CHECK ("COLORRULESID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."JOAP" ADD CONSTRAINT "SYS_C0011245" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."JOAPDATA" ADD CONSTRAINT "SYS_C0011247" CHECK ("JOAPDATAID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."JOAPDATA" ADD CONSTRAINT "SYS_C0011248" CHECK ("JOAPID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."JOAPDATA" ADD CONSTRAINT "SYS_C0011249" CHECK ("ENGINEDATAID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."JOAPDATA" ADD CONSTRAINT "SYS_C0011250" CHECK ("MOCCONTROLLER" IS NOT NULL)
@

ALTER TABLE "EMOC3"."JOAPDATA" ADD CONSTRAINT "SYS_C0011251" CHECK ("SAMPLEDATE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."LANDINGCODES" ADD CONSTRAINT "SYS_C0011253" CHECK ("LANDINGCODEID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."LANDINGCODES" ADD CONSTRAINT "SYS_C0011254" CHECK ("LANDINGCODE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."LANDINGCODES" ADD CONSTRAINT "SYS_C0011255" CHECK ("WRITEUPNEEDED" IS NOT NULL)
@

ALTER TABLE "EMOC3"."LANDINGCODES" ADD CONSTRAINT "SYS_C0011256" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."LINKS" ADD CONSTRAINT "SYS_C0011258" CHECK ("LINKID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."LINKS" ADD CONSTRAINT "SYS_C0011259" CHECK ("LINKURL" IS NOT NULL)
@

ALTER TABLE "EMOC3"."LINKS" ADD CONSTRAINT "SYS_C0011260" CHECK ("LINKTITLE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."LINKS" ADD CONSTRAINT "SYS_C0011261" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."LOCATIONS" ADD CONSTRAINT "SYS_C0011263" CHECK ("LOCATIONID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."LOCATIONS" ADD CONSTRAINT "SYS_C0011264" CHECK ("LOCATIONCODE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."LOCATIONS" ADD CONSTRAINT "SYS_C0011265" CHECK ("MAXIMUMOCCUPANCY" IS NOT NULL)
@

ALTER TABLE "EMOC3"."LOCATIONS" ADD CONSTRAINT "SYS_C0011266" CHECK ("DEFAULTLOCATION" IS NOT NULL)
@

ALTER TABLE "EMOC3"."LOCATIONS" ADD CONSTRAINT "SYS_C0011267" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."MAINTENANCEEVENTS" ADD CONSTRAINT "SYS_C0011269" CHECK ("MAINTENANCEEVENTID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."MAINTENANCEEVENTS" ADD CONSTRAINT "SYS_C0011270" CHECK ("UNIT" IS NOT NULL)
@

ALTER TABLE "EMOC3"."MAINTENANCEEVENTS" ADD CONSTRAINT "SYS_C0011271" CHECK ("PWC" IS NOT NULL)
@

ALTER TABLE "EMOC3"."MAINTENANCEEVENTS" ADD CONSTRAINT "SYS_C0011272" CHECK ("EQUIPID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."MAINTENANCEEVENTS" ADD CONSTRAINT "SYS_C0011273" CHECK ("WUCLCN" IS NOT NULL)
@

ALTER TABLE "EMOC3"."MAINTENANCEEVENTS" ADD CONSTRAINT "SYS_C0011274" CHECK ("TSSCH" IS NOT NULL)
@

ALTER TABLE "EMOC3"."MAJCOMS" ADD CONSTRAINT "SYS_C0011275" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."MESSAGES" ADD CONSTRAINT "SYS_C0011277" CHECK ("MESSAGEID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."MESSAGES" ADD CONSTRAINT "SYS_C0011278" CHECK ("MESSAGETITLE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."MESSAGES" ADD CONSTRAINT "SYS_C0011279" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."MICAP" ADD CONSTRAINT "SYS_C0011281" CHECK ("MICAPID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."MICAP" ADD CONSTRAINT "SYS_C0011282" CHECK ("DOCUMENTNUMBER" IS NOT NULL)
@

ALTER TABLE "EMOC3"."MICROSOFTDTPROPERTIES" ADD CONSTRAINT "MICROSOFT_NN_ID" CHECK ("ID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."MICROSOFTDTPROPERTIES" ADD CONSTRAINT "MICROSOFT_NN_PROPERTY" CHECK ("PROPERTY" IS NOT NULL)
@

ALTER TABLE "EMOC3"."MICROSOFTDTPROPERTIES" ADD CONSTRAINT "MICROSOFT_NN_VERSION" CHECK ("VERSION" IS NOT NULL)
@

ALTER TABLE "EMOC3"."MISSIONS" ADD CONSTRAINT "SYS_C0011289" CHECK ("MISSIONID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."MISSIONS" ADD CONSTRAINT "SYS_C0011290" CHECK ("MISSION" IS NOT NULL)
@

ALTER TABLE "EMOC3"."MISSIONS" ADD CONSTRAINT "SYS_C0011291" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."MOC" ADD CONSTRAINT "SYS_C0011293" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."MOC" ADD CONSTRAINT "SYS_C0011294" CHECK ("MOCTITLE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."MOC" ADD CONSTRAINT "SYS_C0011295" UNIQUE
	("MOCTITLE") /*Code Fragment was removed >> USING INDEX "EMOC3"."SYS_C0011295"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."MOCADMINS" ADD CONSTRAINT "SYS_C0011297" CHECK ("MOCADMINID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."MOCADMINS" ADD CONSTRAINT "SYS_C0011298" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."MOCADMINS" ADD CONSTRAINT "SYS_C0011299" CHECK ("USERID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."MOCSTATUSICONS" ADD CONSTRAINT "SYS_C0011301" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."MOCSTATUSICONS" ADD CONSTRAINT "SYS_C0011302" CHECK ("STATUSIMAGEID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."MOCSTATUSICONS" ADD CONSTRAINT "SYS_C0011303" CHECK ("MISSIONDESIGNSERIES" IS NOT NULL)
@

ALTER TABLE "EMOC3"."MOCSTATUSICONS" ADD CONSTRAINT "SYS_C0011304" CHECK ("STATUSCODE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."MOCSTATUSICONS" ADD CONSTRAINT "SYS_C0011305" CHECK ("ICON_TYPE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."MOCSTATUSICONS" ADD CONSTRAINT "UK_MOCSTATUSICONS" UNIQUE
	("ICON_TYPE",
	 "MISSIONDESIGNSERIES",
	 "MOCID",
	 "STATUSCODE") /*Code Fragment was removed >> USING INDEX "EMOC3"."UK_MOCSTATUSICONS_IDX"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."MOCUSERS" ADD CONSTRAINT "SYS_C0011308" CHECK ("MOCUSERID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."MOCUSERS" ADD CONSTRAINT "SYS_C0011309" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."MOCUSERS" ADD CONSTRAINT "SYS_C0011310" CHECK ("USERID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."OPERATIONALEVENTDELETETRX" ADD CONSTRAINT "SYS_C0011312" CHECK ("OPERATIONALEVENTDELETETRXID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."OPERATIONALEVENTLOADTRX" ADD CONSTRAINT "SYS_C0011313" CHECK ("OPERATIONALEVENTLOADTRXID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."OPERATIONALEVENTUPDATETRX" ADD CONSTRAINT "SYS_C0011314" CHECK ("OPERATIONALEVENTUPDATETRXID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."ORDNANCE" ADD CONSTRAINT "SYS_C0011315" CHECK ("ORDNANCEID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."ORDNANCE" ADD CONSTRAINT "SYS_C0011316" CHECK ("WEAPONSTYPEID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."ORDNANCE" ADD CONSTRAINT "SYS_C0011317" CHECK ("ORDNANCE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."ORGANIZATIONS" ADD CONSTRAINT "SYS_C0011319" CHECK ("UNIT_ID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."ORGANIZATIONS" ADD CONSTRAINT "SYS_C0011320" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."PERMISSIONS" ADD CONSTRAINT "SYS_C0011323" CHECK ("PERMISSIONID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."PERMISSIONS" ADD CONSTRAINT "SYS_C0011324" CHECK ("SQUADRONID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."PERMISSIONS" ADD CONSTRAINT "SYS_C0011325" CHECK ("USERID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."PILOT" ADD CONSTRAINT "SYS_C0011327" CHECK ("PILOTID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."PILOT" ADD CONSTRAINT "SYS_C0011328" CHECK ("PILOTNAME" IS NOT NULL)
@

ALTER TABLE "EMOC3"."PILOT" ADD CONSTRAINT "SYS_C0011329" CHECK ("RANKID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."PILOT" ADD CONSTRAINT "SYS_C0011330" CHECK ("SQUADRONID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."PILOT" ADD CONSTRAINT "SYS_C0011331" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."POSSESSIONS" ADD CONSTRAINT "SYS_C0011333" CHECK ("POSSESSIONID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."POSSESSIONS" ADD CONSTRAINT "SYS_C0011334" CHECK ("POSSESSIONCODE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."POSSESSIONS" ADD CONSTRAINT "SYS_C0011335" CHECK ("DEFAULTPOSSESSION" IS NOT NULL)
@

ALTER TABLE "EMOC3"."POSSESSIONS" ADD CONSTRAINT "SYS_C0011336" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."RANGES" ADD CONSTRAINT "SYS_C0011338" CHECK ("RANGEID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."RANGES" ADD CONSTRAINT "SYS_C0011339" CHECK ("RANGE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."RANKS" ADD CONSTRAINT "SYS_C0011341" CHECK ("RANKID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."RANKS" ADD CONSTRAINT "SYS_C0011342" CHECK ("RANKCODE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."RANKS" ADD CONSTRAINT "SYS_C0011343" CHECK ("DEFAULTRANK" IS NOT NULL)
@

ALTER TABLE "EMOC3"."RANKS" ADD CONSTRAINT "SYS_C0011344" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."REMARKS" ADD CONSTRAINT "SYS_C0011346" CHECK ("REMARKSID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."REMARKS" ADD CONSTRAINT "SYS_C0011347" CHECK ("REMARKS" IS NOT NULL)
@

ALTER TABLE "EMOC3"."REPORTCOLUMNS" ADD CONSTRAINT "SYS_C0011349" CHECK ("COLUMNNUMBER" IS NOT NULL)
@

ALTER TABLE "EMOC3"."REPORTCOLUMNS" ADD CONSTRAINT "SYS_C0011350" CHECK ("COLUMNNAME" IS NOT NULL)
@

ALTER TABLE "EMOC3"."REPORTCRITERIA" ADD CONSTRAINT "SYS_C0011351" CHECK ("CRITERIAID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."REPORTCRITERIA" ADD CONSTRAINT "SYS_C0011352" CHECK ("REPORTID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."REPORTCRITERIA" ADD CONSTRAINT "SYS_C0011353" CHECK ("REPORTNAME" IS NOT NULL)
@

ALTER TABLE "EMOC3"."REPORTCRITERIA" ADD CONSTRAINT "SYS_C0011354" CHECK ("REPORTVIEW" IS NOT NULL)
@

ALTER TABLE "EMOC3"."REPORTCRITERIA" ADD CONSTRAINT "SYS_C0011355" CHECK ("FIELDS" IS NOT NULL)
@

ALTER TABLE "EMOC3"."REPORTCRITERIA" ADD CONSTRAINT "SYS_C0011356" CHECK ("QUERYTYPE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."REPORTPARAMETERS" ADD CONSTRAINT "SYS_C0011358" CHECK ("PARAMETERNUMBER" IS NOT NULL)
@

ALTER TABLE "EMOC3"."REPORTPARAMETERS" ADD CONSTRAINT "SYS_C0011359" CHECK ("PARAMETERNAME" IS NOT NULL)
@

ALTER TABLE "EMOC3"."REPORTPARAMETERS" ADD CONSTRAINT "SYS_C0011360" CHECK ("PARAMETERTYPE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."REPORTS" ADD CONSTRAINT "SYS_C0011361" CHECK ("REPORTNAME" IS NOT NULL)
@

ALTER TABLE "EMOC3"."REPORTS" ADD CONSTRAINT "SYS_C0011362" CHECK ("SQLSTATEMENT" IS NOT NULL)
@

ALTER TABLE "EMOC3"."REPORTS" ADD CONSTRAINT "SYS_C0011363" CHECK ("LIMITBYSQUADRON" IS NOT NULL)
@

ALTER TABLE "EMOC3"."REPORTS" ADD CONSTRAINT "SYS_C0011364" CHECK ("REPORTID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."REPORTS" ADD CONSTRAINT "SYS_C0011365" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."SCHEDULE" ADD CONSTRAINT "SYS_C0011367" CHECK ("SCHEDULEID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."SCHEDULE" ADD CONSTRAINT "SYS_C0011368" CHECK ("SPARE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."SCHEDULEDEVIATIONS" ADD CONSTRAINT "SYS_C0011370" CHECK ("SCHEDULEDEVIATIONID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."SCHEDULESCSV" ADD CONSTRAINT "SYS_C0011371" CHECK ("SCHEDULECSVID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."SCHEDULESCSV" ADD CONSTRAINT "SYS_C0011372" CHECK ("SCHEDULE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."SCHEDULESCSV" ADD CONSTRAINT "SYS_C0011373" CHECK ("SCHEDULENAME" IS NOT NULL)
@

ALTER TABLE "EMOC3"."SCHEDULESCSV" ADD CONSTRAINT "SYS_C0011374" CHECK ("DATEUPLOADED" IS NOT NULL)
@

ALTER TABLE "EMOC3"."SCHEDULESCSV" ADD CONSTRAINT "SYS_C0011375" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."SEMEDX" ADD CONSTRAINT "SYS_C0011376" CHECK ("SEMEDXID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."SEMEDX" ADD CONSTRAINT "SYS_C0011377" CHECK ("SEMEDX" IS NOT NULL)
@

ALTER TABLE "EMOC3"."SEMEDX" ADD CONSTRAINT "SYS_C0011378" CHECK ("COLORRULESID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."SEMEDXDATA" ADD CONSTRAINT "SYS_C0011380" CHECK ("SEMDATAID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."SEMEDXDATA" ADD CONSTRAINT "SYS_C0011381" CHECK ("ENGINEDATAID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."SEMEDXDATA" ADD CONSTRAINT "SYS_C0011382" CHECK ("SEMEDXID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."SEMEDXDATA" ADD CONSTRAINT "SYS_C0011383" CHECK ("MOCCONTROLLER" IS NOT NULL)
@

ALTER TABLE "EMOC3"."SEMEDXDATA" ADD CONSTRAINT "SYS_C0011384" CHECK ("SAMPLEDATE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."SHOPDISPATCH" ADD CONSTRAINT "SYS_C0011386" CHECK ("SHOPDISPATCHID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."SHOPDISPATCH" ADD CONSTRAINT "SYS_C0011387" CHECK ("AIRCRAFTID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."SQUADRONS" ADD CONSTRAINT "SYS_C0011390" CHECK ("SQUADRONID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."SQUADRONS" ADD CONSTRAINT "SYS_C0011391" CHECK ("SQUADRONNAME" IS NOT NULL)
@

ALTER TABLE "EMOC3"."SQUADRONS" ADD CONSTRAINT "SYS_C0011392" CHECK ("SHORTNAME" IS NOT NULL)
@

ALTER TABLE "EMOC3"."SQUADRONS" ADD CONSTRAINT "SYS_C0011393" CHECK ("WINGID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."SQUADRONS" ADD CONSTRAINT "SYS_C0011394" CHECK ("COLORID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."SQUADRON_SORT_ORDER" ADD CONSTRAINT "SYS_C0011396" CHECK ("SQSORTORDERID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."STATIONLOCCODES" ADD CONSTRAINT "SYS_C0011398" CHECK ("STALOCCODEID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."STATIONLOCCODES" ADD CONSTRAINT "SYS_C0011399" CHECK ("STATIONLOC" IS NOT NULL)
@

ALTER TABLE "EMOC3"."STATIONLOCCODES" ADD CONSTRAINT "SYS_C0011400" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."STATUSCODE" ADD CONSTRAINT "SYS_C0011402" CHECK ("STATUSCODEID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."STATUSCODE" ADD CONSTRAINT "SYS_C0011403" CHECK ("STATUSCODE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."STATUSCODE" ADD CONSTRAINT "SYS_C0011404" CHECK ("ORDERNUMBER" IS NOT NULL)
@

ALTER TABLE "EMOC3"."STATUSCODE" ADD CONSTRAINT "SYS_C0011405" CHECK ("ICONNAME" IS NOT NULL)
@

ALTER TABLE "EMOC3"."STATUSCODE" ADD CONSTRAINT "SYS_C0011406" CHECK ("DEFAULTSTATUSCODE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."STATUSCODE" ADD CONSTRAINT "SYS_C0011407" CHECK ("LASTFLOWN" IS NOT NULL)
@

ALTER TABLE "EMOC3"."STATUSCODE" ADD CONSTRAINT "SYS_C0011408" CHECK ("FLYING" IS NOT NULL)
@

ALTER TABLE "EMOC3"."STATUSCODE" ADD CONSTRAINT "SYS_C0011409" CHECK ("TAKEOFF" IS NOT NULL)
@

ALTER TABLE "EMOC3"."STATUSCODE" ADD CONSTRAINT "SYS_C0011410" CHECK ("ISREQUIRED" IS NOT NULL)
@

ALTER TABLE "EMOC3"."STATUSCODE" ADD CONSTRAINT "SYS_C0011411" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."STATUSIMAGE" ADD CONSTRAINT "SYS_C0011414" CHECK ("IMAGE_DATA" IS NOT NULL)
@

ALTER TABLE "EMOC3"."STATUSIMAGE" ADD CONSTRAINT "SYS_C0011415" CHECK ("IMAGE_NAME" IS NOT NULL)
@

ALTER TABLE "EMOC3"."STATUSTRANSITIONRULE" ADD CONSTRAINT "SYS_C0011417" CHECK ("STATRULEID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."STATUSTRANSITIONRULE" ADD CONSTRAINT "SYS_C0011418" CHECK ("STATUSCODEID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."STATUSTRANSITIONRULE" ADD CONSTRAINT "SYS_C0011419" CHECK ("TRANSITION2ID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."STATUSTRANSITIONRULE" ADD CONSTRAINT "SYS_C0011420" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."SYMBOLS" ADD CONSTRAINT "SYS_C0011423" CHECK ("SYMBOLID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."SYMBOLS" ADD CONSTRAINT "SYS_C0011424" CHECK ("CONDCODEID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."SYMBOLS" ADD CONSTRAINT "SYS_C0011425" CHECK ("SYMBOL" IS NOT NULL)
@

ALTER TABLE "EMOC3"."SYMBOLS" ADD CONSTRAINT "SYS_C0011426" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."TBMCSINTERFACELOG" ADD CONSTRAINT "SYS_C0011428" CHECK ("INTERFACELOGID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."TBMCSINTERFACELOG" ADD CONSTRAINT "SYS_C0011429" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."USERALERT" ADD CONSTRAINT "SYS_C0011431" CHECK ("ALERTID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."USERIMAGES" ADD CONSTRAINT "SYS_C0011433" CHECK ("IMAGEID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."USERIMAGES" ADD CONSTRAINT "SYS_C0011434" CHECK ("USERID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."USERIMAGES" ADD CONSTRAINT "SYS_C0011435" CHECK ("DATEUPLOADED" IS NOT NULL)
@

ALTER TABLE "EMOC3"."USERLINKS" ADD CONSTRAINT "SYS_C0011437" CHECK ("LINKID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."USERLINKS" ADD CONSTRAINT "SYS_C0011438" CHECK ("LINKURL" IS NOT NULL)
@

ALTER TABLE "EMOC3"."USERLINKS" ADD CONSTRAINT "SYS_C0011439" CHECK ("LINKTITLE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."USERS" ADD CONSTRAINT "SYS_C0011440" CHECK ("USERID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."USERS" ADD CONSTRAINT "SYS_C0011441" CHECK ("USERNAME" IS NOT NULL)
@

ALTER TABLE "EMOC3"."USERS" ADD CONSTRAINT "SYS_C0011442" CHECK ("ISONLINE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."USERS" ADD CONSTRAINT "SYS_C0011443" CHECK ("BADATTEMPTS" IS NOT NULL)
@

ALTER TABLE "EMOC3"."UTILIZATIONCODES" ADD CONSTRAINT "SYS_C0011445" CHECK ("UTILCODEID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."UTILIZATIONCODES" ADD CONSTRAINT "SYS_C0011446" CHECK ("UTILIZATIONCODE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."UTILIZATIONCODES" ADD CONSTRAINT "SYS_C0011447" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."WEAPONSCLASS" ADD CONSTRAINT "SYS_C0011451" CHECK ("WEAPONSCLASSID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."WEAPONSCLASS" ADD CONSTRAINT "SYS_C0011452" CHECK ("WEAPONSCLASS" IS NOT NULL)
@

ALTER TABLE "EMOC3"."WEAPONSCLASS" ADD CONSTRAINT "SYS_C0011453" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."WEAPONSINFO" ADD CONSTRAINT "SYS_C0011455" CHECK ("WEAPONSID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."WEAPONSINFO" ADD CONSTRAINT "SYS_C0011456" CHECK ("COMBATSCLID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."WEAPONSINFO" ADD CONSTRAINT "SYS_C0011457" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."WEAPONSLOAD" ADD CONSTRAINT "SYS_C0011459" CHECK ("LOADID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."WEAPONSLOAD" ADD CONSTRAINT "SYS_C0011460" CHECK ("STATION" IS NOT NULL)
@

ALTER TABLE "EMOC3"."WEAPONSLOAD" ADD CONSTRAINT "SYS_C0011461" CHECK ("WEAPONSNUMBER" IS NOT NULL)
@

ALTER TABLE "EMOC3"."WEAPONTYPES" ADD CONSTRAINT "SYS_C0011463" CHECK ("WEAPONSTYPEID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."WEAPONTYPES" ADD CONSTRAINT "SYS_C0011464" CHECK ("WEAPONTYPE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."WEAPONTYPES" ADD CONSTRAINT "SYS_C0011465" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."WEBSERVERS" ADD CONSTRAINT "SYS_C0011467" CHECK ("SERVERID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."WEBSERVERS" ADD CONSTRAINT "SYS_C0011468" CHECK ("SERVERNAME" IS NOT NULL)
@

ALTER TABLE "EMOC3"."WEBSERVERS" ADD CONSTRAINT "SYS_C0011469" CHECK ("SERVERURL" IS NOT NULL)
@

ALTER TABLE "EMOC3"."WEBSERVERS" ADD CONSTRAINT "UK_SERVERNAME" UNIQUE
	("SERVERNAME") /*Code Fragment was removed >> USING INDEX "EMOC3"."UK_SERVERNAME"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."WEBSERVERS" ADD CONSTRAINT "UK_SERVERURL" UNIQUE
	("SERVERURL") /*Code Fragment was removed >> USING INDEX "EMOC3"."UK_SERVERURL"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."WHENDISCOVEREDCODES" ADD CONSTRAINT "SYS_C0011473" CHECK ("WHENDISCOVEREDID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."WHENDISCOVEREDCODES" ADD CONSTRAINT "SYS_C0011474" CHECK ("WDC" IS NOT NULL)
@

ALTER TABLE "EMOC3"."WHENDISCOVEREDCODES" ADD CONSTRAINT "SYS_C0011475" CHECK ("WDCNARRATIVE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."WHENDISCOVEREDCODES" ADD CONSTRAINT "SYS_C0011476" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."WINGS" ADD CONSTRAINT "SYS_C0011479" CHECK ("WINGID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."WINGS" ADD CONSTRAINT "SYS_C0011480" CHECK ("WINGNAME" IS NOT NULL)
@

ALTER TABLE "EMOC3"."WINGS" ADD CONSTRAINT "SYS_C0011481" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."WINGS" ADD CONSTRAINT "UK_WINGS_ELCUNITID" UNIQUE
	("ELC",
	 "UNITID") /*Code Fragment was removed >> USING INDEX "EMOC3"."UK_WINGS_ELCUNITID"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."WORKCENTERS" ADD CONSTRAINT "SYS_C0011484" CHECK ("WORKCENTERCODE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."WORKCENTERS" ADD CONSTRAINT "SYS_C0011485" CHECK ("MOCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."WRITEUPS" ADD CONSTRAINT "SYS_C0011489" CHECK ("WRITEUPID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."WRITEUPS" ADD CONSTRAINT "SYS_C0011490" CHECK ("WRITEUPTIME" IS NOT NULL)
@

ALTER TABLE "EMOC3"."WRITEUPS" ADD CONSTRAINT "SYS_C0011491" CHECK ("CORRECTED" IS NOT NULL)
@

ALTER TABLE "EMOC3"."WRITEUPS" ADD CONSTRAINT "SYS_C0011492" CHECK ("PACER" IS NOT NULL)
@

ALTER TABLE "EMOC3"."WUC" ADD CONSTRAINT "SYS_C0011494" CHECK ("WUCID" IS NOT NULL)
@

ALTER TABLE "EMOC3"."WUC" ADD CONSTRAINT "SYS_C0011495" CHECK ("WUCCODE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."WX" ADD CONSTRAINT "SYS_C0011497" CHECK ("DEFAULTWEATHERCODE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."WX" ADD CONSTRAINT "SYS_C0011498" CHECK ("WEATHERCODE" IS NOT NULL)
@

ALTER TABLE "EMOC3"."WX" ADD CONSTRAINT "SYS_C0011499" CHECK ("MOCID" IS NOT NULL)
@
