--<ScriptOptions statementTerminator="@"/>


ALTER TABLE "EMOC3"."ACFTMDSTYPES" ADD CONSTRAINT "PK_ACFTMDSTYPES" PRIMARY KEY
	("MOCID",
	 "ACFTMDSTYPECD") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_ACFTMDSTYPES"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."AIRCRAFT" ADD CONSTRAINT "PK_AIRCRAFT" PRIMARY KEY
	("AIRCRAFTID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_AIRCRAFT"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."AIRCRAFTCUSTOMDATA" ADD CONSTRAINT "PK_AIRCRAFTCUSTOMDATA" PRIMARY KEY
	("AIRCRAFTID",
	 "CUSTOMDATAID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_AIRCRAFTCUSTOMDATA"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."AIRCRAFTENGINEDATA" ADD CONSTRAINT "PK_AIRCRAFTENGINEDATA" PRIMARY KEY
	("ENGINEDATAID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_AIRCRAFTENGINEDATA"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."AIRCRAFTMDS" ADD CONSTRAINT "PK_AIRCRAFTMDS" PRIMARY KEY
	("AIRCRAFTMDSID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_AIRCRAFTMDS"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."AREAS" ADD CONSTRAINT "PK_AREAS" PRIMARY KEY
	("AREAID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_AREAS"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."ARMAMENT" ADD CONSTRAINT "PK_ARMAMENT" PRIMARY KEY
	("ARMAMENTID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_ARMAMENT"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."BASEMAPS" ADD CONSTRAINT "PK_BASEMAPS_MAPID" PRIMARY KEY
	("MAPID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_BASEMAPS_MAPID"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."CAUSECODES" ADD CONSTRAINT "PK_CAUSECODES" PRIMARY KEY
	("CAUSECODEID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_CAUSECODES"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."CAUSECODETRX" ADD CONSTRAINT "PK_CAUSECODETRX" PRIMARY KEY
	("CAUSECODETRXID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_CAUSECODETRX"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."CHECKLIST" ADD CONSTRAINT "PK_CHECKLIST" PRIMARY KEY
	("CHECKLISTID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_CHECKLIST"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."COLORRULES" ADD CONSTRAINT "PK_COLORRULES" PRIMARY KEY
	("COLORRULESID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_COLORRULES"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."COLORS" ADD CONSTRAINT "PK_COLORS" PRIMARY KEY
	("COLORID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_COLORS"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."COMBATSCLS" ADD CONSTRAINT "PK_COMBATSCLS" PRIMARY KEY
	("COMBATSCLID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_COMBATSCLS"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."CONDITIONCODES" ADD CONSTRAINT "PK_CONDITIONCODES" PRIMARY KEY
	("CONDCODEID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_CONDITIONCODES"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."CONDITIONSTATUS" ADD CONSTRAINT "PK_CONDITIONSTATUS" PRIMARY KEY
	("CONDSTATID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_CONDITIONSTATUS"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."COUNTRYCODES" ADD CONSTRAINT "PK_COUNTRYCODES_COUNTRYCODE" PRIMARY KEY
	("COUNTRYCODE") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_COUNTRYCODES_COUNTRYCODE"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."CREWCHIEFS" ADD CONSTRAINT "PK_CREWCHIEFS" PRIMARY KEY
	("CREWCHIEFID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_CREWCHIEFS"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."CUSTOMDATA" ADD CONSTRAINT "PK_CUSTOMDATA" PRIMARY KEY
	("CUSTOMDATAID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_CUSTOMDATA"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."CUSTOMDATALISTITEM" ADD CONSTRAINT "PK_CUSTOMDATALISTITEM" PRIMARY KEY
	("CUSTOMDATAITEMID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_CUSTOMDATALISTITEM"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."CUSTOMDATAMDS" ADD CONSTRAINT "PK_CUSTOMDATAMDS" PRIMARY KEY
	("CUSTOMDATAID",
	 "AIRCRAFTMDSID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_CUSTOMDATAMDS"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."DEVIATIONCODES" ADD CONSTRAINT "PK_DEVIATIONCODES" PRIMARY KEY
	("DEVIATIONCODEID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_DEVIATIONCODES"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."DEVIATIONCODETRX" ADD CONSTRAINT "PK_DEVIATIONCODETRX" PRIMARY KEY
	("DEVIATIONCODETRXID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_DEVIATIONCODETRX"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."EMOCAPPCONFIGURATION" ADD CONSTRAINT "PK_CONFIG_ID" PRIMARY KEY
	("CONFIGID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_CONFIG_ID"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."EMOCCONFIG" ADD CONSTRAINT "PK_EMOCCONFIG" PRIMARY KEY
	("EMOCCONFIGID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_EMOCCONFIG"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."EMOCHELP" ADD CONSTRAINT "PK_EMOCHELP" PRIMARY KEY
	("HELPID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_EMOCHELP"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."ENGINERUNLOG" ADD CONSTRAINT "PK_ENGINERUNLOG" PRIMARY KEY
	("ENGINELOGID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_ENGINERUNLOG"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."FIELDNAMES" ADD CONSTRAINT "PK_FIELDNAMES" PRIMARY KEY
	("FIELDNAMESID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_FIELDNAMES"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."FIRESYMBOLS" ADD CONSTRAINT "PK_FIRESYMBOLS" PRIMARY KEY
	("FIRESYMBOLID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_FIRESYMBOLS"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."FLIGHTS" ADD CONSTRAINT "PK_FLIGHTS" PRIMARY KEY
	("FLIGHTID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_FLIGHTS"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."FUEL" ADD CONSTRAINT "PK_FUEL" PRIMARY KEY
	("FUELSTATUSID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_FUEL"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."GAINLOSSSTATUSUPDATETRX" ADD CONSTRAINT "PK_GAINLOSSSTATUSUPDATETRX" PRIMARY KEY
	("GAINLOSSSTATUSUPDATETRXID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_GAINLOSSSTATUSUPDATETRX"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."GENERATIONFLOW" ADD CONSTRAINT "PK_GENERATIONFLOW" PRIMARY KEY
	("GENERATIONFLOWNAME") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_GENERATIONFLOW"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."GENERATIONFLOWITEMS" ADD CONSTRAINT "PK_GENERATIONFLOWITEMS" PRIMARY KEY
	("ITEMNUMBER",
	 "GENERATIONFLOWNAME") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_GENERATIONFLOWITEMS"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."GENERATIONFLOWPROGRESS" ADD CONSTRAINT "PK_GENERATIONFLOWPROGRESS" PRIMARY KEY
	("GENERATIONFLOWNAME",
	 "STEPNUMBER",
	 "ITEMNUMBER") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_GENERATIONFLOWPROGRESS"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."GENERATIONFLOWSTEPS" ADD CONSTRAINT "PK_GENERATIONFLOWSTEPS" PRIMARY KEY
	("STEPNUMBER",
	 "GENERATIONFLOWNAME") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_GENERATIONFLOWSTEPS"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."GEOLOCCODETRX" ADD CONSTRAINT "PK_GEOLOCCODETRX" PRIMARY KEY
	("GEOLOCCODETRXID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_GEOLOCCODETRX"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."HANGER_QUEEN_CODE" ADD CONSTRAINT "PK_HANGERQUEEN" PRIMARY KEY
	("HQCODEID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_HANGERQUEEN"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."HISTORY" ADD CONSTRAINT "PK_HISTORY" PRIMARY KEY
	("HISTORYID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_HISTORY"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."HOTSPOTS" ADD CONSTRAINT "PK_HOTSPOTS" PRIMARY KEY
	("FIELDNAME") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_HOTSPOTS"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."IMDSCDBELCUNITOPTION" ADD CONSTRAINT "PK_IMDSCDBELCUNITOPTION" PRIMARY KEY
	("IMDSCDBELCUNITOPTIONID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_IMDSCDBELCUNITOPTION"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."IMDSCDBINTERFACEOPTION" ADD CONSTRAINT "PK_IMDSCDBINTERFACEOPTION" PRIMARY KEY
	("IMDSCDBINTERFACEOPTIONID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_IMDSCDBINTERFACEOPTION"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."IMDSLOGINS" ADD CONSTRAINT "PK_IMDSLOGINS" PRIMARY KEY
	("IMDSLOGINID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_IMDSLOGINS"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."INTERFACECONTROL" ADD CONSTRAINT "PK_INTERFACECONTROL" PRIMARY KEY
	("INTERFACECONTROLID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_INTERFACECONTROL"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."INTERFACEITEMS" ADD CONSTRAINT "PK_INTERFACEITEMS" PRIMARY KEY
	("INTERFACEITEMID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_INTERFACEITEMS"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."INTERFACELOG" ADD CONSTRAINT "PK_INTERFACELOG" PRIMARY KEY
	("INTERFACELOGID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_INTERFACELOG"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."INTERFACEREJECTLIST" ADD CONSTRAINT "PK_INTERFACEREJECTLIST" PRIMARY KEY
	("REJECTID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_INTERFACEREJECTLIST"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."INVENTORYSTATUSUPDATETRX" ADD CONSTRAINT "PK_INVENTORYSTATUSUPDATE" PRIMARY KEY
	("INVENTORYSTATUSUPDATETRXID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_INVENTORYSTATUSUPDATE"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."JOAP" ADD CONSTRAINT "PK_JOAP" PRIMARY KEY
	("JOAPID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_JOAP"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."JOAPDATA" ADD CONSTRAINT "PK_JOAPDATA" PRIMARY KEY
	("JOAPDATAID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_JOAPDATA"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."LANDINGCODES" ADD CONSTRAINT "PK_LANDINGCODES" PRIMARY KEY
	("LANDINGCODEID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_LANDINGCODES"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."LOCATIONCODETRX" ADD CONSTRAINT "PK_LOACTIONCODETRX" PRIMARY KEY
	("LOCATIONCODETRXID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_LOACTIONCODETRX"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."LOCATIONS" ADD CONSTRAINT "PK_LOCATIONS" PRIMARY KEY
	("LOCATIONID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_LOCATIONS"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."MAJORCOMMANDCODETRX" ADD CONSTRAINT "PK_MAJORCOMMANDCODETRX" PRIMARY KEY
	("MAJORCOMMANDCODETRXID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_MAJORCOMMANDCODETRX"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."MESSAGES" ADD CONSTRAINT "PK_MESSAGES" PRIMARY KEY
	("MESSAGEID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_MESSAGES"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."MICAP" ADD CONSTRAINT "PK_MICAP" PRIMARY KEY
	("MICAPID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_MICAP"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."MICAPTRX" ADD CONSTRAINT "PK_MICAPTRXID" PRIMARY KEY
	("MICAPTRXID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_MICAPTRXID"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."MICROSOFTDTPROPERTIES" ADD CONSTRAINT "MICROSOFT_PK_DTPROPERTIES" PRIMARY KEY
	("ID",
	 "PROPERTY") /*Code Fragment was removed >> USING INDEX "EMOC3"."MICROSOFT_PK_DTPROPERTIES"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."MISSIONS" ADD CONSTRAINT "PK_MISSIONS" PRIMARY KEY
	("MISSIONID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_MISSIONS"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."MOC" ADD CONSTRAINT "PK_MOC" PRIMARY KEY
	("MOCID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_MOC"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."MOCADMINS" ADD CONSTRAINT "PK_MOCADMIN" PRIMARY KEY
	("MOCADMINID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_MOCADMIN"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."MOCSTATUSICONS" ADD CONSTRAINT "PK_MOCSTATUSICONS" PRIMARY KEY
	("MOCID",
	 "STATUSCODE",
	 "MISSIONDESIGNSERIES",
	 "ICON_TYPE") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_MOCSTATUSICONS"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."MOCUSERS" ADD CONSTRAINT "PK_MOCUSERS" PRIMARY KEY
	("MOCUSERID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_MOCUSERS"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."ORDNANCE" ADD CONSTRAINT "PK_ORDNANCE" PRIMARY KEY
	("ORDNANCEID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_ORDNANCE"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."ORGANIZATIONS" ADD CONSTRAINT "PK_ORGANIZATIONS" PRIMARY KEY
	("ORGANIZATIONSID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_ORGANIZATIONS"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."ORGANIZATIONTRX" ADD CONSTRAINT "PK_ORGANIZATIONLOADTRX" PRIMARY KEY
	("ORGANIZATIONLOADTRXID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_ORGANIZATIONLOADTRX"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."PERMISSIONS" ADD CONSTRAINT "PK_PERMISSIONS" PRIMARY KEY
	("PERMISSIONID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_PERMISSIONS"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."PILOT" ADD CONSTRAINT "PK_PILOT" PRIMARY KEY
	("PILOTID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_PILOT"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."POSSESSIONS" ADD CONSTRAINT "PK_POSSESSIONS" PRIMARY KEY
	("POSSESSIONID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_POSSESSIONS"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."RANGES" ADD CONSTRAINT "PK_RANGES" PRIMARY KEY
	("RANGEID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_RANGES"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."RANKS" ADD CONSTRAINT "PK_RANKS" PRIMARY KEY
	("RANKID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_RANKS"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."REMARKS" ADD CONSTRAINT "PK_REMARKS" PRIMARY KEY
	("REMARKSID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_REMARKS"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."REPORTCRITERIA" ADD CONSTRAINT "PK_REPORTCRITERIA" PRIMARY KEY
	("CRITERIAID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_REPORTCRITERIA"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."REPORTS" ADD CONSTRAINT "PK_REPORTID" PRIMARY KEY
	("REPORTID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_REPORTID"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."SCHEDULE" ADD CONSTRAINT "PK_SCHEDULE" PRIMARY KEY
	("SCHEDULEID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_SCHEDULE"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."SEMEDX" ADD CONSTRAINT "PK_SEMEDX" PRIMARY KEY
	("SEMEDXID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_SEMEDX"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."SEMEDXDATA" ADD CONSTRAINT "PK_SEMEDXDATA" PRIMARY KEY
	("SEMDATAID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_SEMEDXDATA"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."SHOPDISPATCH" ADD CONSTRAINT "PK_SHOPDISPATCH" PRIMARY KEY
	("SHOPDISPATCHID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_SHOPDISPATCH"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."SMSTESTBLOB" ADD CONSTRAINT "PK_SMSTESTBLOB_ID" PRIMARY KEY
	("ID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_SMSTESTBLOB_ID"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."SQUADRONS" ADD CONSTRAINT "PK_SQUADRONS" PRIMARY KEY
	("SQUADRONID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_SQUADRONS"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."SQUADRON_SORT_ORDER" ADD CONSTRAINT "PK_SQUADRON_SORT_ORDER" PRIMARY KEY
	("SQSORTORDERID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_SQUADRON_SORT_ORDER"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."STATIONLOCCODES" ADD CONSTRAINT "PK_STALOCCODEID" PRIMARY KEY
	("STALOCCODEID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_STALOCCODEID"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."STATUSCODE" ADD CONSTRAINT "PK_STATUSCODE" PRIMARY KEY
	("STATUSCODEID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_STATUSCODE"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."STATUSCORRECTIONTRX" ADD CONSTRAINT "PK_STATUSCORRECTION" PRIMARY KEY
	("STATUSCORRECTIONID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_STATUSCORRECTION"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."STATUSIMAGE" ADD CONSTRAINT "PK_STATUSIMAGES" PRIMARY KEY
	("STATUSIMAGEID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_STATUSIMAGES"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."STATUSTRANSITIONRULE" ADD CONSTRAINT "PK_STATUSTRANSITIONRULE" PRIMARY KEY
	("STATRULEID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_STATUSTRANSITIONRULE"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."STATUSUPDATETRX" ADD CONSTRAINT "PK_STATUSUPDATETRX" PRIMARY KEY
	("STATUSUPDATETRXID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_STATUSUPDATETRX"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."SYMBOLS" ADD CONSTRAINT "PK_SYMBOLS" PRIMARY KEY
	("SYMBOLID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_SYMBOLS"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."TBMCSINTERFACELOG" ADD CONSTRAINT "PK_TBMCSINTERFACELOG" PRIMARY KEY
	("INTERFACELOGID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_TBMCSINTERFACELOG"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."USERALERT" ADD CONSTRAINT "PK_USERALERT" PRIMARY KEY
	("ALERTID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_USERALERT"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."USERIMAGES" ADD CONSTRAINT "PK_IMAGEID" PRIMARY KEY
	("IMAGEID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_IMAGEID"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."USERS" ADD CONSTRAINT "PK_USERS" PRIMARY KEY
	("USERID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_USERS"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."UTILIZATIONCODES" ADD CONSTRAINT "PK_UTILCODEID" PRIMARY KEY
	("UTILCODEID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_UTILCODEID"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."UTILIZATIONCODETRX" ADD CONSTRAINT "PK_UTILIZATIONCODETRX" PRIMARY KEY
	("UTILIZATIONCODETRXID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_UTILIZATIONCODETRX"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."UVRCHANGETRX" ADD CONSTRAINT "PK_UVRCHANGETRX" PRIMARY KEY
	("UVRCHANGETRXID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_UVRCHANGETRX"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."WEAPONSCLASS" ADD CONSTRAINT "PK_WEAPONSCLASS" PRIMARY KEY
	("WEAPONSCLASSID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_WEAPONSCLASS"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."WEAPONSINFO" ADD CONSTRAINT "WEAPONSINFO_PK11061992374968" PRIMARY KEY
	("WEAPONSID") /*Code Fragment was removed >> USING INDEX "EMOC3"."WEAPONSINFO_PK11061992374968"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."WEAPONSLOAD" ADD CONSTRAINT "PK_WEAPONSLOAD" PRIMARY KEY
	("LOADID",
	 "STATION") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_WEAPONSLOAD"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."WEAPONTYPES" ADD CONSTRAINT "PK_WEAPONTYPES" PRIMARY KEY
	("WEAPONSTYPEID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_WEAPONTYPES"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."WEBSERVERS" ADD CONSTRAINT "PK_SERVERS_ID" PRIMARY KEY
	("SERVERID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_SERVERS_ID"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."WHENDISCOVEREDCODES" ADD CONSTRAINT "WHENDISCOVERE_PK11061906353349" PRIMARY KEY
	("WHENDISCOVEREDID") /*Code Fragment was removed >> USING INDEX "EMOC3"."WHENDISCOVERE_PK11061906353349"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."WHENDISCOVEREDCODETRX" ADD CONSTRAINT "PK_WHENDISCOVEREDCODETRX" PRIMARY KEY
	("WHENDISCOVEREDCODETRXID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_WHENDISCOVEREDCODETRX"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."WINGS" ADD CONSTRAINT "PK_WINGS" PRIMARY KEY
	("WINGID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_WINGS"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."WORKCENTERS" ADD CONSTRAINT "PK_WORKCENTERID" PRIMARY KEY
	("WORKCENTERID") /*Code Fragment was removed >> USING INDEX "EMOC3"."WORKCENTERS_PK11061901575234"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."WORKCENTERTRX" ADD CONSTRAINT "PK_WORKCENTERTRX" PRIMARY KEY
	("WORKCENTERTRXID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_WORKCENTERTRX"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."WORKUNITCODETRX" ADD CONSTRAINT "PK_WORKUNITCODETRX" PRIMARY KEY
	("WORKUNITCODETRXID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_WORKUNITCODETRX"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."WRITEUPS" ADD CONSTRAINT "PK_WRITEUPS" PRIMARY KEY
	("WRITEUPID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_WRITEUPS"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."WUC" ADD CONSTRAINT "PK_WUC" PRIMARY KEY
	("WUCID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_WUC"<< Code Fragment was removed - END*/

@

ALTER TABLE "EMOC3"."WX" ADD CONSTRAINT "PK_WX" PRIMARY KEY
	("WXCODEID") /*Code Fragment was removed >> USING INDEX "EMOC3"."PK_WX"<< Code Fragment was removed - END*/

@
