--<ScriptOptions statementTerminator="@"/>

CREATE PROCEDURE         "EMOC3"."GET_SCHEDULE_BY_SQUADRON_TOTAL" (
P_CURSOR OUT    EMOC_TYPES.EMOC_CURSOR,
SQUADRONIDIN    SQUADRONS.SQUADRONID%TYPE,
SORTIEDATEIN   SCHEDULE.SORTIEDATE%TYPE
)
/******************************************************************************
   NAME:       GET_SCHEDULE_BY_SQUADRON_TOTAL
   PURPOSE:    Returns Schedules for the specified squadron with
         text values for codes (JOAP, Fuel, etc.) filled.

   REVISIONS:
   Ver        Date        Author           Description
   ---------  ----------  ---------------  ------------------------------------
   1.0        5/14/03      A.Mitchell       1. Created this procedure.
   1.1    6/2/03    A.Mitchell  2. Changed SORTIEDATE to SCHEDDAY
   1.2    6/16/03    A.Mitchell  3. Added Schedule Deviations table support
   1.3    2/1/04    A.Mitchell  4. Added UNION used to show previous day's planes flying
   PARAMETERS:
   INPUT:
   *SQUADRONIDIN
   *SORTIEDATESTART
   OUTPUT:
   *P_CURSOR
   RETURNED VALUE:
   CALLED BY:
   CALLS:
   EXAMPLE USE:
   ASSUMPTIONS:
   LIMITATIONS:
   ALGORITHM:
   NOTES:

******************************************************************************/

AS

BEGIN

    OPEN P_CURSOR FOR
    SELECT SC.SCHEDULEID,
      SC.GO,
     SC.SCHEDULEDTAKEOFF,
     SC.SCHEDULEDLANDING,
     SC.ACTUALTAKEOFF,
     SC.ACTUALLANDING,
     SC.SPARE,
     SC.ADJTAKEOFF,
     SC.ADJLANDING,
     SC.AREAARRIVETIME,
     SC.AREALEAVETIME,
     SC.CALLSIGN,
     SQ.SQUADRONNAME,
     LC.LANDINGCODE,
     RG.RANGE,
     DC.DEVIATIONCODE,
     CC.CAUSECODE,
     WX.WEATHERCODE,
     MI.MISSION,
     AR.AREA,
     SC.AIRCRAFTID,
     PT.PILOTNAME,
     SC.SORTIENUM,
     SC.SORTIEMOD,
     SC.SORTIEDATE,
     AC.SHORTTAILNUMBER,
     AC.TAILNUMBER,
     SC.SQUADRONID,
     AC.LOCATIONCODE,
     CO.COLORVALUE,        --ROW COLOR FOR CONDITIONSTATUS
     MDS.AIRCRAFTMDS,
     ST.ICONNAME,
     ST.STATUSCODE,
     CO2.COLORVALUE ROWCOLOR, --ROW COLOR FOR DEVIATIONS
     FU.FUELSTATUS,
     SC.CONFIGCODE,
     SC.SORTIE_JOAP,
     SC.SORTIE_SEMEDX,
     SC.SCHEDDAY,
     REM1.REMARKS MAINTENANCEREMARKS,
     REM2.REMARKS,
     SC.SCHEDULEREMARKS,
     SC.MAINTREMARKS,
     WG.WINGID,
     WG.UNITID,
     NVL(SC.PUBLISHED_FLAG, 0) PUBLISHED_FLAG,
     AC.LASTFLOWNTIME,
     CO2.FONTCOLOR,
     AC.CHAFF,
     AC.FLARE,
     AC.TMEFLOWNSINCEPHASEDATE,
     SC.BLOCKNUMBER,
     SC.TYPE_EVENT,
     SC.SCHEDULESOURCE,
     CO.FONTCOLOR STATUSFONTCOLOR,
     CS.FLYABLE,
     SC.SWAPPEDLINE,
     AC.MISEQUIPID
    FROM SCHEDULE SC
     LEFT JOIN AIRCRAFT AC ON SC.AIRCRAFTID = AC.AIRCRAFTID
     LEFT JOIN SQUADRONS SQ ON SC.SQUADRONID = SQ.SQUADRONID
     LEFT JOIN LANDINGCODES LC ON SC.LANDINGCODEID = LC.LANDINGCODEID
     LEFT JOIN RANGES RG ON SC.RANGEID = RG.RANGEID
     LEFT JOIN DEVIATIONCODES DC ON SC.DEVIATIONCODEID = DC.DEVIATIONCODEID
     LEFT JOIN CAUSECODES CC ON SC.CAUSECODEID = CC.CAUSECODEID
     LEFT JOIN WX ON SC.WXCODEID = WX.WXCODEID
     LEFT JOIN MISSIONS MI ON SC.MISSIONID = MI.MISSIONID
     LEFT JOIN AREAS AR ON SC.AREAID = AR.AREAID
     LEFT JOIN PILOT PT ON SC.PILOTID = PT.PILOTID
     LEFT JOIN CONDITIONCODES CD ON AC.CONDITIONCODEID = CD.CONDCODEID
     LEFT JOIN CONDITIONSTATUS CS ON CD.CONDSTATID = CS.CONDSTATID
     LEFT JOIN COLORS CO ON CS.COLORID = CO.COLORID
     LEFT JOIN AIRCRAFTMDS MDS ON AC.AIRCRAFTMDSID = MDS.AIRCRAFTMDSID
     LEFT JOIN STATUSCODE ST ON AC.STATUSCODEID = ST.STATUSCODEID
     LEFT JOIN COLORS CO2 ON DC.COLORID = CO2.COLORID
     LEFT JOIN FUEL FU ON AC.FUELSTATUSID = FU.FUELSTATUSID
     LEFT JOIN REMARKS REM1 ON REM1.REMARKSID = MAINTREMARKS
     LEFT JOIN REMARKS REM2 ON REM2.REMARKSID = SCHEDULEREMARKS
     JOIN WINGS WG ON SQ.WINGID = WG.WINGID
    WHERE SC.SQUADRONID = SQUADRONIDIN
    AND SC.SORTIEDATE = SORTIEDATEIN
	AND SC.SPARE = 0
   UNION ALL
   SELECT SC.SCHEDULEID,
      SC.GO,
     SC.SCHEDULEDTAKEOFF,
     SC.SCHEDULEDLANDING,
     SC.ACTUALTAKEOFF,
     SC.ACTUALLANDING,
     SC.SPARE,
     SC.ADJTAKEOFF,
     SC.ADJLANDING,
     SC.AREAARRIVETIME,
     SC.AREALEAVETIME,
     SC.CALLSIGN,
     SQ.SQUADRONNAME,
     LC.LANDINGCODE,
     RG.RANGE,
     DC.DEVIATIONCODE,
     CC.CAUSECODE,
     WX.WEATHERCODE,
     MI.MISSION,
     AR.AREA,
     SC.AIRCRAFTID,
     PT.PILOTNAME,
     SC.SORTIENUM,
     SC.SORTIEMOD,
     SC.SORTIEDATE,
     AC.SHORTTAILNUMBER,
     AC.TAILNUMBER,
     SC.SQUADRONID,
     AC.LOCATIONCODE,
     CO.COLORVALUE,        --ROW COLOR FOR CONDITIONSTATUS
     MDS.AIRCRAFTMDS,
     ST.ICONNAME,
     ST.STATUSCODE,
     CO2.COLORVALUE ROWCOLOR, --ROW COLOR FOR DEVIATIONS
     FU.FUELSTATUS,
     SC.CONFIGCODE,
     SC.SORTIE_JOAP,
     SC.SORTIE_SEMEDX,
     SC.SCHEDDAY,
     REM1.REMARKS MAINTENANCEREMARKS,
     REM2.REMARKS,
     SC.SCHEDULEREMARKS,
     SC.MAINTREMARKS,
     WG.WINGID,
     WG.UNITID,
     NVL(SC.PUBLISHED_FLAG, 0) PUBLISHED_FLAG,
     AC.LASTFLOWNTIME,
     CO2.FONTCOLOR,
     AC.CHAFF,
     AC.FLARE,
     AC.TMEFLOWNSINCEPHASEDATE,
     SC.BLOCKNUMBER,
     SC.TYPE_EVENT,
     SC.SCHEDULESOURCE,
     CO.FONTCOLOR STATUSFONTCOLOR,
     CS.FLYABLE,
     SC.SWAPPEDLINE,
     AC.MISEQUIPID
    FROM SCHEDULE SC
     LEFT JOIN AIRCRAFT AC ON SC.AIRCRAFTID = AC.AIRCRAFTID
     LEFT JOIN SQUADRONS SQ ON SC.SQUADRONID = SQ.SQUADRONID
     LEFT JOIN LANDINGCODES LC ON SC.LANDINGCODEID = LC.LANDINGCODEID
     LEFT JOIN RANGES RG ON SC.RANGEID = RG.RANGEID
     LEFT JOIN DEVIATIONCODES DC ON SC.DEVIATIONCODEID = DC.DEVIATIONCODEID
     LEFT JOIN CAUSECODES CC ON SC.CAUSECODEID = CC.CAUSECODEID
     LEFT JOIN WX ON SC.WXCODEID = WX.WXCODEID
     LEFT JOIN MISSIONS MI ON SC.MISSIONID = MI.MISSIONID
     LEFT JOIN AREAS AR ON SC.AREAID = AR.AREAID
     LEFT JOIN PILOT PT ON SC.PILOTID = PT.PILOTID
     LEFT JOIN CONDITIONCODES CD ON AC.CONDITIONCODEID = CD.CONDCODEID
     LEFT JOIN CONDITIONSTATUS CS ON CD.CONDSTATID = CS.CONDSTATID
     LEFT JOIN COLORS CO ON CS.COLORID = CO.COLORID
     LEFT JOIN AIRCRAFTMDS MDS ON AC.AIRCRAFTMDSID = MDS.AIRCRAFTMDSID
     LEFT JOIN STATUSCODE ST ON AC.STATUSCODEID = ST.STATUSCODEID
     LEFT JOIN COLORS CO2 ON DC.COLORID = CO2.COLORID
     LEFT JOIN FUEL FU ON AC.FUELSTATUSID = FU.FUELSTATUSID
     LEFT JOIN REMARKS REM1 ON REM1.REMARKSID = MAINTREMARKS
     LEFT JOIN REMARKS REM2 ON REM2.REMARKSID = SCHEDULEREMARKS
     JOIN WINGS WG ON SQ.WINGID = WG.WINGID,
    (SELECT DISTINCT SS.SCHEDULEID, SS.STATUSCODEID
       FROM SCHEDULESTATUS SS
       JOIN SCHEDULE S ON S.SCHEDULEID = SS.SCHEDULEID
       JOIN STATUSCODE SC ON SS.STATUSCODEID = SC.STATUSCODEID
       WHERE SS.STATUSTYPE = 0
       AND S.SORTIEDATE < SORTIEDATEIN
       AND S.SQUADRONID = SQUADRONIDIN
       AND SS.STATUSTIME IN --Correlated Subquery
        (SELECT MAX(STATUSTIME) FROM SCHEDULESTATUS WHERE

SCHEDULEID = S.SCHEDULEID)
    )  LAST
    WHERE (LAST.STATUSCODEID = ST.STATUSCODEID AND STATUSCODE = 'Airborne')
    AND LAST.SCHEDULEID = SC.SCHEDULEID
    AND SC.SQUADRONID = SQUADRONIDIN
    AND SC.SORTIEDATE < SORTIEDATEIN
	AND SC.SPARE = 0
    AND ACTUALLANDING IS NULL
    ORDER BY SORTIEDATE, SORTIENUM, SCHEDULEID;

   EXCEPTION
     WHEN NO_DATA_FOUND THEN
       NULL;
     WHEN OTHERS THEN
       NULL;
END GET_SCHEDULE_BY_SQUADRON_TOTAL;
 
 
 
 
 
 
 
 
@
