--<ScriptOptions statementTerminator="@"/>


CREATE PROCEDURE         "EMOC3"."ARCH_MDSEQUIPMENTTRX" 
AS
   /******************************************************************************
   NAME:       ARCH_MDSEQUIPMENTTRX
   PURPOSE:

   REVISIONS:
   Ver        Date        Author           Description
   ---------  ----------  ---------------  ------------------------------------
   1.0        1/10/2007  GMR            1. Created this procedure.

   NOTES:

   Automatically available Auto Replace Keywords:
      Object Name:     ARCH_MDSEQUIPMENTTRX
      Sysdate:         12/15/2006
      Date and Time:   12/15/2006, 10:16:05 AM, and 12/15/2006 10:16:05 AM
      Username:         emoc3)
      Table Name:       MDSEQUIPMENTTRX)

******************************************************************************/
BEGIN

     INSERT INTO EMOCAUX.MDSEQUIPMENTTRX
SELECT 
MDSEQUIPTRXID, HOMEENTERPRISELOCATIONCODE, CURRENTENTERPRISELOCATIONCODE, 
   UNITID, EQUIPMENTID, SERIALNUMBER, 
   STANDARDREPORTINGDESIGNATOR, AFI21103SELECTIONINDICATOR, POSSESSIONID, 
   ASSIGNMENTSTATUSCODE, ASSIGNMENTCOMMANDABBREVIATION, AIRCRAFTCONFIGURATIONID, 
   PROGRAMELEMENTCODE, MAINTENANCETYPEINTERVAL, OPERATINGTIME, 
   PREVIOUSOPERATINGTIME, TOTALSORTIES, TOTALLANDINGS, 
   FULLSTOPLANDINGS, CREATEAUTOHISTORYEH, ITEMMANUFACTURER, 
   EQUIPMENTACCEPTANCEDATE, TYPEOFREPAIR, REPAIRFREQUENCY, 
   REPAIRTYPEINTERVAL, LASTOVERHAULDATE, LASTOVERHAULTIME, 
   PRIMEREMOTETERMINALID, SECONDARYREMOTETERMINALID, LOCALOPTION, 
   OWNINGWORKCENTER, SUPPORTGENERALREPORTABLE, SUPPLYFACTOR, 
   TRANSACTIONORDINALDATE, HOSTUNITDATEANDTIME, RECORDDATETIME, 
   APPLICATIONNOTE, DATEPROCESSED, TRANSACTIONTYPE, 
   EQUIPMENTDESIGNATOR, PRODUCTIONBLOCKNUMBER,  SYSDATE AS archivedate
FROM EMOC3.MDSEQUIPMENTTRX
WHERE recorddatetime < SYSDATE - 7;

DELETE FROM EMOC3.MDSEQUIPMENTTRX
WHERE recorddatetime < SYSDATE - 7;

EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      NULL;
   WHEN OTHERS
   THEN
      -- Consider logging the error and then re-raise
      RAISE;
END ARCH_MDSEQUIPMENTTRX;
 
 
 
 
 
 
 
 
@
