--<ScriptOptions statementTerminator="@"/>


CREATE PROCEDURE         "EMOC3"."SPUPDATEINTERFACELOGCAMS" (
AIRCRAFTIDIN INTERFACELOG.AIRCRAFTID%TYPE,
INTERFACELOGIDIN INTERFACELOG.INTERFACELOGID%TYPE,
TIMEOFINSERTIN INTERFACELOG.TIMEOFINSERT%TYPE,
TRANSACTIONTYPEIN INTERFACELOG.TRANSACTIONTYPE%TYPE,
XMLININ	INTERFACELOG.XMLIN%TYPE,
INTERFACECONTROLIDIN INTERFACELOG.INTERFACECONTROLID%TYPE,
USERIDIN INTERFACELOG.USERID%TYPE

)
AS

BEGIN

INSERT INTO INTERFACELOG (INTERFACELOGID, AIRCRAFTID, TIMEOFINSERT, TRANSACTIONTYPE, XMLIN, INTERFACECONTROLID, USERID )

VALUES (INTERFACELOGIDIN, AIRCRAFTIDIN, TIMEOFINSERTIN, TRANSACTIONTYPEIN, XMLININ, INTERFACECONTROLIDIN, USERIDIN);

COMMIT;

END SPUPDATEINTERFACELOGCAMS;
 
 
 
 
 
 
 
 
@
