--<ScriptOptions statementTerminator="@"/>


CREATE PROCEDURE         "EMOC3"."SPUPDATEAIRCRAFTHISTORY" (

AIRCRAFTIDIN HISTORY.AIRCRAFTID%TYPE,
ELEMENTIN HISTORY.ELEMENT%TYPE,
ELEMENTVALUEIN HISTORY.ELEMENTVALUE%TYPE,
EVENTDATEIN VARCHAR,
TRANSACTIONIDIN	HISTORY.TRANSACTIONID%TYPE,
USERIDIN HISTORY.USERID%TYPE

)
AS

ROW_ID INTEGER;
BEGIN


SELECT NVL(MAX(HISTORY.HISTORYID), 0)
INTO ROW_ID
FROM HISTORY;


INSERT INTO HISTORY (HISTORYID, ELEMENT, ELEMENTVALUE, EVENTDATE, TRANSACTIONID, USERID, AIRCRAFTID)

VALUES (ROW_ID + 1, ELEMENTIN, ELEMENTVALUEIN, TO_DATE(EVENTDATEIN,'MM/DD/YYYY HH24:MI:SS'), TRANSACTIONIDIN, USERIDIN, AIRCRAFTIDIN);





END SPUPDATEAIRCRAFTHISTORY;

 
 
 
 
 
 
 
 
@
