--<ScriptOptions statementTerminator="@"/>


CREATE PROCEDURE         "EMOC3"."DT_DROPUSEROBJECTBYID" ( PARAM_ID IN NUMBER ) AS BEGIN DELETE FROM MICROSOFTDTPROPERTIES WHERE OBJECTID = PARAM_ID; END DT_DROPUSEROBJECTBYID; 
 
 
 
 
 
 
 
 
@
