--<ScriptOptions statementTerminator="@"/>


CREATE PROCEDURE         "EMOC3"."SPGETSTATIONSORDNANCES" 
(
P_CURSOR OUT EMOC_TYPES.EMOC_CURSOR,
AIRCRAFTIDIN AIRCRAFT.AIRCRAFTID%TYPE,
STATIONIN ARMAMENT.STATION%TYPE)
AS
BEGIN
-- RETURN THE CURSOR FOR THE RECORDSET
OPEN P_CURSOR FOR
SELECT armament.STATION,
	   armament.ORDNANCEID,
	   ordnance.ORDNANCE

FROM aircraft, armament, ordnance
WHERE ( (aircraft.AIRCRAFTID = AIRCRAFTIDIN)
	  	AND (ARMAMENT.STATION = STATIONIN)
 	   	AND	(aircraft.AIRCRAFTMDSID = armament.AIRCRAFTMDSID)
		AND (armament.ORDNANCEID = ordnance.ORDNANCEID))
ORDER BY armament.station, ordnance.ordnance;

END SPGETSTATIONSORDNANCES;

 
 
 
 
 
 
 
 
@
