--<ScriptOptions statementTerminator="@"/>


CREATE PROCEDURE         "EMOC3"."GET_DEVIATIONS_BY_LINE" (
P_CURSOR OUT    EMOC_TYPES.EMOC_CURSOR,
SCHEDULEIDIN    SCHEDULE.SCHEDULEID%TYPE
)
/******************************************************************************
   NAME:       GET_DEVIATIONSBY_LINE
   PURPOSE:    Returns DEVIATIONS for the specified ID

   REVISIONS:
   Ver        Date        Author           Description
   ---------  ----------  ---------------  ------------------------------------
   1.0        7/3/03      A.Mitchell       1. Created this procedure.

   PARAMETERS:
   INPUT:
   *SCHEDULEIDIN
   OUTPUT:
   *P_CURSOR
   RETURNED VALUE:
   CALLED BY:
   CALLS:
   EXAMPLE USE:
   ASSUMPTIONS:
   LIMITATIONS:
   ALGORITHM:
   NOTES:

******************************************************************************/

AS
BEGIN
  OPEN P_CURSOR FOR
  SELECT
    SD.STOPDATETIME,
   SD.STARTDATETIME,
   SD.SORTIENUM,
      SD.SORTIEMOD,
   SD.SORTIEDATE,
   SD.SCHEDULEID,
      SD.SCHEDULEDEVIATIONID,
   SD.NEWCAUSECODE NEWCAUSECODEID,
   SD.MAINTENANCEEVENTID,
      RM.REMARKS,
   SD.DEVIATIONSREMARKS,
   SD.DEVIATIONCODEID,
     SD.CHARGEABLE,
   SD.CAUSECODEID,
   SD.ACTIONOPTIONS,
   DV.DEVIATIONCODE,
   CC.CAUSECODE,
   CC2.CAUSECODE NEWCAUSECODE,
   CO.FONTCOLOR,
   SC.AIRCRAFTID
 FROM SCHEDULEDEVIATIONS SD
 LEFT JOIN DEVIATIONCODES DV ON SD.DEVIATIONCODEID = DV.DEVIATIONCODEID
 LEFT JOIN CAUSECODES CC ON SD.CAUSECODEID = CC.CAUSECODEID
 LEFT JOIN CAUSECODES CC2 ON SD.NEWCAUSECODE = CC2.CAUSECODEID
 LEFT JOIN REMARKS RM ON RM.REMARKSID = SD.DEVIATIONSREMARKS
 LEFT JOIN COLORS CO ON CO.COLORID = DV.COLORID
 LEFT JOIN SCHEDULE SC ON SC.SCHEDULEID = SD.SCHEDULEID
 WHERE SD.SCHEDULEID = SCHEDULEIDIN
 ORDER BY SD.SCHEDULEDEVIATIONID;

    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        Null;
      WHEN OTHERS THEN
        Null;
END GET_DEVIATIONS_BY_LINE;
 
 
 
 
 
 
 
 
@
