--<ScriptOptions statementTerminator="@"/>


CREATE PROCEDURE         "EMOC3"."GET_FUELS" (
P_CURSOR OUT EMOC_TYPES.EMOC_CURSOR
)
AS
BEGIN
-- RETURN THE CURSOR FOR THE RECORDSET
OPEN P_CURSOR FOR
SELECT FUELSTATUSID,
  FUELSTATUS,
  FUELDESCRIPTION,
  LANDING,
  FUELSTATUSLABEL,
  ALLOWSORTIEUPDATE,
	NVL(DEFAULTFUEL,0) as DEFAULTFUEL,
	COLORID,
	(SELECT COLORNAME FROM COLORS WHERE COLORS.COLORID = FUEL.COLORID) AS COLORNAME,
	(SELECT COLORVALUE FROM COLORS WHERE COLORS.COLORID = FUEL.COLORID) AS COLORVALUE
  FROM FUEL
ORDER BY FUELSTATUS ASC;

END GET_FUELS;

 
 
 
 
 
 
 
 
@
