--<ScriptOptions statementTerminator="@"/>


CREATE PROCEDURE         "EMOC3"."SPUPDATEMISSIONSTATUS" (
AIRCRAFTIDIN AIRCRAFT.AIRCRAFTID%TYPE,
LOCATIONIDIN AIRCRAFT.LOCATIONID%TYPE,
STALOCCODEIDIN AIRCRAFT.STALOCCODEID%TYPE,
FUELSTATUSIDIN AIRCRAFT.FUELSTATUSID%TYPE,
FUELREQUESTEDTIMEIN VARCHAR,
FUELDELIVERYTIMEIN VARCHAR,
FUELLOADIN AIRCRAFT.FUELLOAD%TYPE,
FUELSTATUSLASTUPDATEDIN VARCHAR,
STATUSCODEIDIN AIRCRAFT.STATUSCODEID%TYPE,
STATUSCODELASTUPDATEDIN VARCHAR,
STATUSCODETIMEIN VARCHAR,
FUELSTATUSTIMEIN VARCHAR,
LOCATIONLASTUPDATEDIN VARCHAR,
LASTFLYDATEIN VARCHAR,
LOCATIONIN VARCHAR

)
AS
BEGIN

UPDATE AIRCRAFT
SET
LOCATIONID = LOCATIONIDIN,
STALOCCODEID = STALOCCODEIDIN,
FUELSTATUSID = FUELSTATUSIDIN,
FUELREQUESTEDTIME = TO_DATE(FUELREQUESTEDTIMEIN, 'MM/DD/YYYY HH24:MI:SS'),
FUELDELIVERYTIME = TO_DATE(FUELDELIVERYTIMEIN, 'MM/DD/YYYY HH24:MI:SS'),
FUELLOAD = FUELLOADIN,
FUELSTATUSLASTUPDATED = TO_DATE(FUELSTATUSLASTUPDATEDIN, 'MM/DD/YYYY HH24:MI:SS'),
STATUSCODEID = STATUSCODEIDIN,
STATUSCODELASTUPDATED = TO_DATE(STATUSCODELASTUPDATEDIN, 'MM/DD/YYYY HH24:MI:SS'),
STATUSCODETIME = TO_DATE(STATUSCODETIMEIN, 'MM/DD/YYYY HH24:MI:SS'),
FUELSTATUSTIME = TO_DATE(FUELSTATUSTIMEIN, 'MM/DD/YYYY HH24:MI:SS'),
LOCATIONLASTUPDATED = TO_DATE(LOCATIONLASTUPDATEDIN, 'MM/DD/YYYY HH24:MI:SS'),
LASTFLOWNTIME = TO_DATE(LASTFLYDATEIN, 'MM/DD/YYYY HH24:MI:SS'),
LOCATIONCODE = LOCATIONIN


WHERE AIRCRAFTID=AIRCRAFTIDIN;

END Spupdatemissionstatus;
 
 
 
 
 
 
 
 
@
