--<ScriptOptions statementTerminator="@"/>


CREATE PROCEDURE         "EMOC3"."SPGETMEVENT" (
P_CURSOR OUT EMOC_TYPES.EMOC_CURSOR,
EVENTIDIN MAINTENANCEEVENTS.EVENTID%TYPE)

AS
BEGIN
-- RETURN THE CURSOR FOR THE RECORDSET
OPEN P_CURSOR FOR

SELECT MAINTENANCEEVENTID, UNIT, EVENTID, PWC, EQUIPID, CP, WUCLCN, WD, PRIORITY, SYMBOL, TSSCH,
	   JOBDUR, DISCREPANCY, WCENARRATIVE, EMPID, ENTRY781, DEFER, WCESYMBOL, JOBFOLLOW, PARTSREQUIRED

FROM MAINTENANCEEVENTS
WHERE EVENTID = EVENTIDIN;


END SPGETMEVENT;

 
 
 
 
 
 
 
 
@
