--<ScriptOptions statementTerminator="@"/>


CREATE PROCEDURE         "EMOC3"."SPUPDATESCHEDULESTATUS" (

SCHEDULEIDIN SCHEDULESTATUS.SCHEDULEID%TYPE,
STATUSCODEIDIN SCHEDULESTATUS.STATUSCODEID%TYPE,
STATUSTIMEIN VARCHAR,
STATUSTYPEIN SCHEDULESTATUS.STATUSTYPE%TYPE

)
AS

BEGIN

IF STATUSTYPEIN = '0' THEN
   UPDATE SCHEDULESTATUS
   SET
   STATUSTIME = TO_DATE(STATUSTIMEIN,'MM/DD/YYYY HH24:MI:SS')
   WHERE SCHEDULEID = SCHEDULEIDIN
   AND STATUSCODEID = STATUSCODEIDIN
   AND STATUSTYPE = STATUSTYPEIN
   AND STATUSTIME = (SELECT MAX(STATUSTIME) FROM SCHEDULESTATUS
			   WHERE SCHEDULEID = SCHEDULEIDIN
			   AND STATUSCODEID = STATUSCODEIDIN
			   AND STATUSTYPE = STATUSTYPEIN);
ELSE --IF STATUSTYPEIN = '1' THEN
   UPDATE SCHEDULESTATUS
   SET
   STATUSTIME = TO_DATE(STATUSTIMEIN,'MM/DD/YYYY HH24:MI:SS')
   WHERE SCHEDULEID = SCHEDULEIDIN
   AND FUELSTATUSID = STATUSCODEIDIN
   AND STATUSTYPE = STATUSTYPEIN
   AND STATUSTIME = (SELECT MAX(STATUSTIME) FROM SCHEDULESTATUS
			   WHERE SCHEDULEID = SCHEDULEIDIN
			   AND FUELSTATUSID = STATUSCODEIDIN
			   AND STATUSTYPE = STATUSTYPEIN);
END IF;


END SPUPDATESCHEDULESTATUS;
 
 
 
 
 
 
 
 
@
