--<ScriptOptions statementTerminator="@"/>


CREATE PROCEDURE         "EMOC3"."SPGETTBMCSAIRCRAFTBYID" (
P_CURSOR OUT Emoc_Types.EMOC_CURSOR,
AIRCRAFTIDIN AIRCRAFT.AIRCRAFTID%TYPE)
AS
BEGIN
-- RETURN THE CURSOR FOR THE RECORDSET
OPEN P_CURSOR FOR

SELECT
AIRCRAFT.AIRCRAFTID,
AIRCRAFT.TAILNUMBER,
AIRCRAFTMDS.ACFTMDSTYPECD,
AIRCRAFTMDS.BLOCKNUMBER,
AIRCRAFTMDS.AIRCRAFTMDS,
AIRCRAFT.AIRCRAFTYEAR,
(AIRCRAFT.AIRCRAFTYEAR || AIRCRAFT.TAILNUMBER) AS YEARANDTAILNUMBER,
AIRCRAFT.COUNTRYCODE,
AIRCRAFT.HOTGUNS,
COMBATSCLS.COMBATSCL,
CONDITIONCODES.CONDITIONCODE,
CREWCHIEFS.CREWCHIEF,
RANKS.RANKCODE AS CREWCHIEFRANK,
AIRCRAFT.ETIC,
AIRCRAFT.FUELLOAD,
FUEL.FUELSTATUS,
FUEL.FUELDESCRIPTION,
TO_CHAR(AIRCRAFT.LASTFLOWNTIME, 'MM/DD/YYYY HH24:MI:SS') LASTFLOWNTIME,
LOCATIONS.LOCATIONCODE,
LOCATIONS.LOCATIONNAME,
POSSESSIONS.POSSESSIONCODE,
AIRCRAFT.PRIORITY,
REMARKS.REMARKS,
(SELECT WUC.WUCCODE FROM WUC WHERE AIRCRAFT.AIRCRAFTWUCID = WUC.WUCID) AS AIRCRAFTWUC,
SQUADRONS.SQUADRONNAME,
WINGS.WINGNAME,
STATIONLOCCODES.STATIONLOC

FROM AIRCRAFT, AIRCRAFTMDS, COMBATSCLS, CONDITIONCODES, CREWCHIEFS,
RANKS,  FUEL, LOCATIONS, POSSESSIONS, REMARKS, STATUSCODE, SQUADRONS,
WINGS, STATIONLOCCODES

WHERE AIRCRAFT.aircraftmdsid = AIRCRAFTMDS.AIRCRAFTMDSID(+)
AND AIRCRAFT.COMBATSCLID = COMBATSCLS.COMBATSCLID(+)
AND AIRCRAFT.CONDITIONCODEID = CONDITIONCODES.CONDCODEID(+)
AND AIRCRAFT.CREWCHIEFID = CREWCHIEFS.CREWCHIEFID(+)
AND CREWCHIEFS.RANKID = RANKS.RANKID(+)
AND AIRCRAFT.FUELSTATUSID = FUEL.FUELSTATUSID(+)
AND AIRCRAFT.LOCATIONID = LOCATIONS.LOCATIONID(+)
AND AIRCRAFT.POSSESSIONID = POSSESSIONS.POSSESSIONID(+)
AND AIRCRAFT.REMARKSID = REMARKS.REMARKSID(+)
AND AIRCRAFT.SQUADRONID = SQUADRONS.SQUADRONID(+)
AND SQUADRONS.WINGID = WINGS.WINGID(+)
AND AIRCRAFT.STATUSCODEID = STATUSCODE.STATUSCODEID(+)
AND AIRCRAFT.STALOCCODEID = STATIONLOCCODES.STALOCCODEID(+)
AND AIRCRAFT.AIRCRAFTID = AIRCRAFTIDIN;

END SPGETTBMCSAIRCRAFTBYID;
 
 
 
 
 
 
 
 
@
