--<ScriptOptions statementTerminator="@"/>


CREATE PROCEDURE         "EMOC3"."SPINSERTEVENTLOG" (

DATETIMEENTEREDIN VARCHAR,
USERIDIN NUMBER,
EVENTTYPEIN EVENTLOG.EVENTTYPE%TYPE,
EVENTNARRATIVEIN EVENTLOG.EVENTNARRATIVE%TYPE,
TAILNUMBERIN EVENTLOG.SHORTTAILNUMBER%TYPE

)
AS
ROW_ID INTEGER;

BEGIN

SELECT NVL(MAX(EVENTLOG.LOGID), 0)
INTO ROW_ID
FROM EVENTLOG;

INSERT INTO EVENTLOG (LOGID, DATETIMEENTERED, USERID, EVENTTYPE, EVENTNARRATIVE, SHORTTAILNUMBER)

VALUES (ROW_ID + 1, TO_DATE(DATETIMEENTEREDIN,'MM/DD/YYYY HH24:MI:SS'), USERIDIN, EVENTTYPEIN, EVENTNARRATIVEIN, TAILNUMBERIN);


END SPINSERTEVENTLOG;

 
 
 
 
 
 
 
 
@
