--<ScriptOptions statementTerminator="@"/>


CREATE PROCEDURE         "EMOC3"."ARCH_ORGANIZATIONTRX" 
AS
   /******************************************************************************
   NAME:       ARCH_ORGANIZATIONTRX
   PURPOSE:

   REVISIONS:
   Ver        Date        Author           Description
   ---------  ----------  ---------------  ------------------------------------
   1.0        1/10/2007  GMR            1. Created this procedure.

   NOTES:

   Automatically available Auto Replace Keywords:
      Object Name:     ARCH_ORGANIZATIONTRX
      Sysdate:         12/15/2006
      Date and Time:   12/15/2006, 10:16:05 AM, and 12/15/2006 10:16:05 AM
      Username:         emoc3)
      Table Name:       ORGANIZATIONTRX)

******************************************************************************/
BEGIN

     INSERT INTO EMOCAUX.ORGANIZATIONTRX
SELECT 
ORGANIZATIONLOADTRXID, CURRENTENTERPRISELOCATIONCODE, UNITID, 
   ORGANIZATIONID, ORGANIZATIONNUMBER, ORGANIZATIONKIND, 
   ORGANIZATIONTYPE, NOMENCLATURE, INSTALLTIONCODE, 
   AFI21103ORGANIZATIONNUMBER, AFI21103ORGANIZATIONKIND, AFI21103ORGANIZATIONTYPE, 
   DETACHMENTNUMBER, OVERSEASINDICATOR, CELASTREPORTINGDATE, 
   HOSTUNITDATEANDTIME, TRANSACTIONORDINALDATE, RECORDDATETIME, 
   APPLICATIONNOTE, DATEPROCESSED, HOMEENTERPRISELOCATIONCODE, 
   TRANSACTIONTYPE, NEWORGANIZATIONID, NEWORGANIZATIONNUMBER, 
   NEWORGANIZATIONKIND, NEWORGANIZATIONTYPE,  SYSDATE AS archivedate
FROM EMOC3.ORGANIZATIONTRX
WHERE DATEPROCESSED < SYSDATE - 7;

DELETE FROM EMOC3.ORGANIZATIONTRX
WHERE DATEPROCESSED < SYSDATE - 7;

EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      NULL;
   WHEN OTHERS
   THEN
      -- Consider logging the error and then re-raise
      RAISE;
END ARCH_ORGANIZATIONTRX;
 
 
 
 
 
 
 
 
@
