--<ScriptOptions statementTerminator="@"/>


CREATE PROCEDURE         "EMOC3"."SPGETAIRCRAFTFIRESYMBOL" (
P_CURSOR OUT EMOC_TYPES.EMOC_CURSOR,
AIRCRAFTIDIN AIRCRAFT.AIRCRAFTID%TYPE
)
AS
BEGIN
OPEN P_CURSOR FOR
SELECT WEAPONSLOAD.AIRCRAFTID, WEAPONSLOAD.FIRESYMBOLID, FIRESYMBOLS.FIRESYMBOL, FIRESYMBOLS.RANKING
FROM WEAPONSLOAD, FIRESYMBOLS
WHERE AIRCRAFTID = AIRCRAFTIDIN
AND WEAPONSLOAD.FIRESYMBOLID = FIRESYMBOLS.FIRESYMBOLID(+)
ORDER BY RANKING DESC;

END SPGETAIRCRAFTFIRESYMBOL;

 
 
 
 
 
 
 
 
@
