--<ScriptOptions statementTerminator="@"/>


CREATE PROCEDURE         "EMOC3"."ARCH_AIRCRAFTEXTRACTTRX" 
AS
   /******************************************************************************
   NAME:       ARCH_AIRCRAFTEXTRACTTRX
   PURPOSE:

   REVISIONS:
   Ver        Date        Author           Description
   ---------  ----------  ---------------  ------------------------------------
   1.0        1/10/2007  GMR            1. Created this procedure.

   NOTES:

   Automatically available Auto Replace Keywords:
      Object Name:     ARCH_AIRCRAFTEXTRACTTRX
      Sysdate:         12/15/2006
      Date and Time:   12/15/2006, 10:16:05 AM, and 12/15/2006 10:16:05 AM
      Username:         emoc3)
      Table Name:       AIRCRAFTEXTRACTTRX)

******************************************************************************/
BEGIN

     INSERT INTO EMOCAUX.AIRCRAFTEXTRACTTRX
  SELECT 
   AIRCRAFTEXTRACTTRXID, FROMENTERPRISELOCATIONCODE, FROMUNITID, 
   EQUIPMENTID, MISSIONDESIGNSERIES, MISSIONDESIGNSERIESBLOCK, 
   AIRCRAFTSERIALNUMBER, MAINTENANCESTATUSCODE, CONDITIONSTATUSCODE, 
   STARTDATE, STARTTIME, WORKUNITCODE, 
   JOBCONTROLNUMBER, ESTIMATEDTIMEINCOMMISSION, STATUSNARRATIVE, 
   LOCATIONCODE, EQUIPMENTORGANIZATIONFLIGHTID, MAINTENANCEREPAIRPRIORITY, 
   ARMED, MULTIPLECONFIGURATIONID, LOCALOPTION, 
   ASSIGNMENTSTATUSCODE, POSSESSIONID, GEOLOCCODE, 
   OWNINGMAJCOM, LASTFLYDATE, DEDICATEDCREWCHIEF, 
   DATEPROCESSED, OWNINGWORKCENTER, SYSDATE AS archivedate
FROM EMOC3.AIRCRAFTEXTRACTTRX
WHERE DATEPROCESSED < SYSDATE - 7;

DELETE FROM EMOC3.AIRCRAFTEXTRACTTRX
WHERE DATEPROCESSED < SYSDATE - 7;

EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      NULL;
   WHEN OTHERS
   THEN
      -- Consider logging the error and then re-raise
      RAISE;
END ARCH_AIRCRAFTEXTRACTTRX;
 
 
 
 
 
 
 
 
@
