--<ScriptOptions statementTerminator="@"/>


CREATE PROCEDURE         "EMOC3"."GET_ASSIGNMENTS" (
P_CURSOR OUT EMOC_TYPES.EMOC_CURSOR
)
AS
BEGIN
-- RETURN THE CURSOR FOR THE RECORDSET
OPEN P_CURSOR FOR
SELECT ASSIGNMENTCODEID,
       ASSIGNMENTCODE,
       ASSIGNMENTDESCRIPTION,
       NVL(DEFAULTASSIGNMENT,0) AS DEFAULTASSIGNMENT
FROM ASSIGNMENTCODES
ORDER BY ASSIGNMENTCODE;

END GET_ASSIGNMENTS;

 
 
 
 
 
 
 
 
@
