--<ScriptOptions statementTerminator="@"/>


CREATE PROCEDURE         "EMOC3"."SPINSERTJOAPDATA" (

ENGINENUMBERIN AIRCRAFTENGINEDATA.ENGINENUMBER%TYPE,
AIRCRAFTIDIN AIRCRAFTENGINEDATA.AIRCRAFTID%TYPE,
JOAPIDIN JOAPDATA.JOAPID%TYPE,
SAMPLEDATEIN JOAPDATA.SAMPLEDATE%TYPE,
SCHEDULEIDIN JOAPDATA.SCHEDULEID%TYPE

)
AS

ROW_ID INTEGER;
ENGDATAID INTEGER;
BEGIN

SELECT AIRCRAFTENGINEDATA.ENGINEDATAID
INTO ENGDATAID
FROM AIRCRAFTENGINEDATA
WHERE ( (AIRCRAFTID = AIRCRAFTIDIN)
	  AND (ENGINENUMBER = ENGINENUMBERIN)  );

IF (ENGDATAID IS NULL) THEN
   SELECT MAX(AIRCRAFTENGINEDATA.ENGINEDATAID)
   INTO ROW_ID
   FROM AIRCRAFTENGINEDATA;

   INSERT INTO AIRCRAFTENGINEDATA (ENGINEDATAID, AIRCRAFTID, ENGINENUMBER)
   VALUES (ROW_ID + 1, AIRCRAFTIDIN, ENGINENUMBERIN);

   ENGDATAID := ROW_ID + 1;
END IF;

SELECT MAX(JOAPDATA.JOAPDATAID)
INTO ROW_ID
FROM JOAPDATA;

INSERT INTO JOAPDATA (JOAPDATAID, ENGINEDATAID, JOAPID, SAMPLEDATE, SCHEDULEID)

VALUES (ROW_ID + 1, ENGDATAID, JOAPIDIN, SAMPLEDATEIN, SCHEDULEIDIN);


END SPINSERTJOAPDATA;
 
 
 
 
 
 
 
 
@
