--<ScriptOptions statementTerminator="@"/>


CREATE PROCEDURE         "EMOC3"."SPGETAIRCRAFTMISSIONS" 
(
P_CURSOR OUT EMOC_TYPES.EMOC_CURSOR,
AIRCRAFTIDIN AIRCRAFT.AIRCRAFTID%TYPE)
AS
BEGIN
-- RETURN THE CURSOR FOR THE RECORDSET
OPEN P_CURSOR FOR


SELECT TO_CHAR(schedule.ACTUALTAKEOFF, 'MM/DD/YYYY HH24:MI:SS') "ACTUALTAKEOFF",
	   TO_CHAR(schedule.ACTUALLANDING, 'MM/DD/YYYY HH24:MI:SS') "ACTUALLANDING",
 	   TO_CHAR(schedule.SCHEDULEDTAKEOFF, 'MM/DD/YYYY HH24:MI:SS') "SCHEDULEDTAKEOFF",
	   TO_CHAR(schedule.SCHEDULEDLANDING, 'MM/DD/YYYY HH24:MI:SS') "SCHEDULEDLANDING",
	   TO_CHAR(schedule.SCHEDDAY, 'MM/DD/YYYY') "SCHEDDAY",
	   schedule.SCHEDULEID,
	   schedule.SORTIENUM

FROM SCHEDULE

WHERE (   (SCHEDULE.AIRCRAFTID = AIRCRAFTIDIN)
	  AND (schedule.ACTUALLANDING = NULL)	  )

ORDER BY SCHEDULEDTAKEOFF;
END SPGETAIRCRAFTMISSIONS;

 
 
 
 
 
 
 
 
@
