--<ScriptOptions statementTerminator="@"/>


CREATE PROCEDURE         "EMOC3"."GET_CREWCHIEFS" (
P_CURSOR OUT EMOC_TYPES.EMOC_CURSOR
)
AS
BEGIN
-- RETURN THE CURSOR FOR THE RECORDSET
OPEN P_CURSOR FOR
SELECT CREWCHIEFID,
 CREWCHIEF,
 NVL(DEFAULTCREWCHIEF,0) AS DEFAULTCREWCHIEF,
 PICTURE,
 RANKID,
 (SELECT RANKS.RANKCODE FROM RANKS WHERE RANKS.RANKID=CREWCHIEFS.RANKID) AS RANKCODE
FROM CREWCHIEFS
ORDER BY CREWCHIEF;

END GET_CREWCHIEFS;

 
 
 
 
 
 
 
 
@
