--<ScriptOptions statementTerminator="@"/>


CREATE PROCEDURE         "EMOC3"."GET_SCHEDULE_DEVIATION_BY_ID" (
P_CURSOR OUT 	  			EMOC_TYPES.EMOC_CURSOR,
SCHEDULEDEVIATIONIDIN		SCHEDULEDEVIATIONS.SCHEDULEDEVIATIONID%TYPE
)
/******************************************************************************
   NAME:       GET_SCHEDULE_DEVIATION_BY_ID
   PURPOSE:    Returns DEVIATION for the specified ID

   REVISIONS:
   Ver        Date        Author           Description
   ---------  ----------  ---------------  ------------------------------------
   1.0        7/3/03      A.Mitchell       1. Created this procedure.

   PARAMETERS:
   INPUT:
   *SCHEDULEDEVIATIONIDIN
   OUTPUT:
   *P_CURSOR
   RETURNED VALUE:
   CALLED BY:
   CALLS:
   EXAMPLE USE:
   ASSUMPTIONS:
   LIMITATIONS:
   ALGORITHM:
   NOTES:

******************************************************************************/

AS
BEGIN
	 OPEN P_CURSOR FOR
	 SELECT
	 		SD.STOPDATETIME,
			SD.STARTDATETIME,
			SD.SORTIENUM,
   			SD.SORTIEMOD,
			SD.SORTIEDATE,
			SD.SCHEDULEID,
   			SD.SCHEDULEDEVIATIONID,
			SD.NEWCAUSECODE NEWCAUSECODEID,
			SD.MAINTENANCEEVENTID,
   			RM.REMARKS,
			SD.DEVIATIONCODEID,
  			SD.CHARGEABLE,
			SD.CAUSECODEID,
			SD.ACTIONOPTIONS,
			DV.DEVIATIONCODE,
			CC.CAUSECODE,
			CC2.CAUSECODE NEWCAUSECODE,
			AC.SHORTTAILNUMBER,
			SC.BLOCKNUMBER,
			RM.REMARKS DEVIATIONSREMARKS,
			RM.REMARKSID,
			WG.WINGID,
			WG.UNITID,
			SC.SQUADRONID,
			SD.INTERFACELOGID,
			AC.MISEQUIPID
	FROM SCHEDULEDEVIATIONS SD
	LEFT JOIN DEVIATIONCODES DV ON SD.DEVIATIONCODEID = DV.DEVIATIONCODEID
	LEFT JOIN CAUSECODES CC ON SD.CAUSECODEID = CC.CAUSECODEID
	LEFT JOIN CAUSECODES CC2 ON SD.NEWCAUSECODE = CC2.CAUSECODEID
	JOIN SCHEDULE SC ON SC.SCHEDULEID = SD.SCHEDULEID
	JOIN AIRCRAFT AC ON AC.AIRCRAFTID = SC.AIRCRAFTID
	JOIN SQUADRONS SQ ON SC.SQUADRONID = SQ.SQUADRONID
	LEFT JOIN REMARKS RM ON RM.REMARKSID = SD.DEVIATIONSREMARKS
	JOIN WINGS WG ON SQ.WINGID = WG.WINGID
	WHERE SD.SCHEDULEDEVIATIONID = SCHEDULEDEVIATIONIDIN
	ORDER BY SD.SCHEDULEDEVIATIONID;

	   EXCEPTION
	     WHEN NO_DATA_FOUND THEN
	       NULL;
	     WHEN OTHERS THEN
	       NULL;
END GET_SCHEDULE_DEVIATION_BY_ID;
 
 
 
 
 
 
 
 
@
