--<ScriptOptions statementTerminator="@"/>


CREATE PROCEDURE         "EMOC3"."GET_JOAPS" (
P_CURSOR OUT EMOC_TYPES.EMOC_CURSOR
)
AS
BEGIN
-- RETURN THE CURSOR FOR THE RECORDSET
OPEN P_CURSOR FOR
SELECT JOAPID,
 JOAPCODE,
 JOAPDESCRIPTION,
 LANDING,
 REDCAPSTATUS,
 NVL(DEFAULTJOAP, 0) AS DEFAULTJOAP,
 JOAP.COLORRULESID,
 COLORRULES.COLORID,
 COLORS.COLORNAME,
 COLORS.COLORVALUE
FROM JOAP, COLORRULES, COLORS
WHERE JOAP.COLORRULESID = COLORRULES.COLORRULESID
	  AND COLORRULES.COLORID = COLORS.COLORID
ORDER BY JOAPCODE;

END GET_JOAPS;

 
 
 
 
 
 
 
 
@
