--<ScriptOptions statementTerminator="@"/>


/*DCW-ERROR GRAMMAR:"An unrecognizable item was found

------------
Error Header
	Source Name: /E:/mitre/project/aflcmc/EMOC/Migration/EMOC3_Script.sql
	Total Line Number: 35625
	Relative Current Chunk Line Number: 35625
	Column Number: 0
------------
 
-------------
Error Message
	Message: no viable alternative at character '    );\n  END IF;\nEND Load_Schedule_Line_From_Cams;\n\n[CREATE]'
------------

The following statement (from line 35525 to 35623) and was skipped" BEGIN*/
 CREATE PROCEDURE         "EMOC3"."LOAD_SCHEDULE_LINE_FROM_CAMS"
  (
    SORTIENUMIN SCHEDULE.SORTIENUM%TYPE,
    EQUIPIDIN AIRCRAFT.MISEQUIPID%TYPE,
    SCHEDULEDTAKEOFFIN SCHEDULE.SCHEDULEDTAKEOFF%TYPE,
    SCHEDULEDLANDINGIN SCHEDULE.SCHEDULEDLANDING%TYPE,
    DEVIATIONCODEIN DEVIATIONCODES.DEVIATIONCODE%TYPE,
    CAUSECODEIN CAUSECODES.CAUSECODE%TYPE,
    SQUADRONIDIN SCHEDULE.SQUADRONID%TYPE,
    SORTIEDATEIN SCHEDULE.SORTIEDATE%TYPE,
    SCHEDDAYIN SCHEDULE.SCHEDDAY%TYPE,
    INTERFACELOGIDIN SCHEDULE.INTERFACELOGID%TYPE )
AS
  NEWSCHEDULEID NUMBER;
  DEVCODEID     NUMBER;
  CAUSEID       NUMBER;
  ACFTID        NUMBER;
  SCHEDCNT      NUMBER;
  MOCIDVAR      NUMBER;
BEGIN
  --GET AIRCRAFT
  SELECT AIRCRAFTID
  INTO ACFTID
  FROM AIRCRAFT
  WHERE MISEQUIPID = EQUIPIDIN
  AND SQUADRONID   = SQUADRONIDIN;
  --Get MOC ID
  SELECT MOCID
  INTO MOCIDVAR
  FROM AIRCRAFT
  WHERE AIRCRAFTID = ACFTID;
  --GET DEVIATION
  GET_DEVID_BY_MOCDEVCODE(MOCIDVAR,DEVIATIONCODEIN,DEVCODEID);
  IF DEVCODEID IS NULL THEN
    GET_DEVDEFAULT_BY_MOC(MOCIDVAR,DEVCODEID);
  END IF;
  --GET CAUSE
  GET_CAUSEID_BY_MOCCAUSECODE(MOCIDVAR,CAUSECODEIN,CAUSEID);
  IF CAUSEID IS NULL THEN
    GET_CAUSEDEFAULT_BY_MOC(MOCIDVAR,CAUSEID);
  END IF;
  SELECT COUNT(*)
  INTO SCHEDCNT
  FROM SCHEDULE
  WHERE SORTIEDATE = SORTIEDATEIN
  AND SORTIENUM    = SORTIENUMIN
  AND AIRCRAFTID   = ACFTID
  AND SQUADRONID   = SQUADRONIDIN;
  IF SCHEDCNT      > 0 THEN
    UPDATE SCHEDULE
    SET SCHEDULEDTAKEOFF = SCHEDULEDTAKEOFFIN,
      SCHEDULEDLANDING   = SCHEDULEDLANDINGIN,
      DEVIATIONCODEID    = DEVCODEID,
      CAUSECODEID        = CAUSEID,
      INTERFACELOGID     = INTERFACELOGIDIN
    WHERE SORTIEDATE     = SORTIEDATEIN
    AND SORTIENUM        = SORTIENUMIN
    AND AIRCRAFTID       = ACFTID
    AND SQUADRONID       = SQUADRONIDIN;
  ELSE
    --INCREMENT
    SELECT SEQ_SCHEDULE.NEXTVAL INTO NEWSCHEDULEID FROM DUAL;
    INSERT
    INTO SCHEDULE
      (
        SCHEDULEID ,
        SCHEDULEDTAKEOFF ,
        SCHEDULEDLANDING ,
        AIRCRAFTID ,
        SORTIENUM ,
        DEVIATIONCODEID ,
        CAUSECODEID ,
        SORTIEDATE ,
        SQUADRONID ,
        SPARE ,
        SCHEDULESOURCE ,
        SCHEDDAY ,
        INTERFACELOGID ,
        PUBLISHED_FLAG
      )
      VALUES
      (
        NEWSCHEDULEID ,
        SCHEDULEDTAKEOFFIN ,
        SCHEDULEDLANDINGIN ,
        ACFTID ,
        SORTIENUMIN ,
        DEVCODEID ,
        CAUSEID ,
        SORTIEDATEIN ,
        SQUADRONIDIN ,
        0 ,
        '174' ,
        SCHEDDAYIN ,
        INTERFACELOGIDIN ,
        1
      );
  END IF;
END Load_Schedule_Line_From_Cams@
