--<ScriptOptions statementTerminator="@"/>


CREATE PROCEDURE         "EMOC3"."GET_DEVIATIONSBRIEF" (
P_CURSOR      OUT EMOC_TYPES.EMOC_CURSOR,
SORTIEDATEIN    SCHEDULE.SORTIEDATE%TYPE,
MOCIDIN   SQUADRONS.MOCID%TYPE
)
AS
BEGIN
-- RETURN THE CURSOR FOR THE RECORDSET
OPEN P_CURSOR FOR
SELECT SD.SCHEDULEDEVIATIONID AS devid,
    SQ.SHORTNAME AS squadron,
 SQ.SQUADRONID AS squadronid,
    PO.POSSESSIONCODE AS possession,
    DC.DEVIATIONCODE AS deviationcode,
    CC.CAUSECODE AS causecode,
    AC.SHORTTAILNUMBER AS tailnumber,
    SCH.SORTIENUM AS linenumber,
    RM.REMARKS AS remarks,
    DECODE(TO_CHAR(SCH.SPARE), '1', 'Y', 'N') AS spare,
    NULL AS rr,
    NULL AS corrective
FROM SCHEDULEDEVIATIONS SD
LEFT JOIN SCHEDULE SCH ON SD.SCHEDULEID = SCH.SCHEDULEID
LEFT JOIN AIRCRAFT AC ON SCH.AIRCRAFTID = AC.AIRCRAFTID
LEFT JOIN SQUADRONS SQ ON SCH.SQUADRONID = SQ.SQUADRONID
LEFT JOIN POSSESSIONS PO ON AC.POSSESSIONID = PO.POSSESSIONID
LEFT JOIN DEVIATIONCODES DC ON SD.DEVIATIONCODEID = DC.DEVIATIONCODEID
LEFT JOIN CAUSECODES CC ON SD.CAUSECODEID = CC.CAUSECODEID
LEFT JOIN REMARKS RM ON SD.DEVIATIONSREMARKS = RM.REMARKSID
WHERE SD.SORTIEDATE = SORTIEDATEIN
AND SQ.MOCID = MOCIDIN;
--WHERE SD.SORTIEDATE = '2005110';

END GET_DEVIATIONSBRIEF;
 
 
 
 
 
 
 
 
@
