--<ScriptOptions statementTerminator="@"/>


CREATE PROCEDURE         "EMOC3"."SPGETWEAPONSSTATUS" 
(
P_CURSOR OUT Emoc_Types.EMOC_CURSOR,
AIRCRAFTIDIN AIRCRAFT.AIRCRAFTID%TYPE)
AS
BEGIN
-- RETURN THE CURSOR FOR THE RECORDSET
OPEN P_CURSOR FOR

SELECT SQUADRONNAME,
TAILNUMBER,
TO_CHAR(LASTFLOWNTIME,'MM/DD/YYYY HH24:MI:SS') "LASTFLOWNTIME",
COMBATSCLS.COMBATSCL,
AIRCRAFT.COMBATSCLID,
CHAFF,
FLARE,
HOTGUNS,
AIRCRAFT.ARM_DEARM,
TO_CHAR(AIRCRAFT.WEAPONSSTATUSLASTUPDATED,'MM/DD/YYYY HH24:MI:SS') "WEAPONSSTATUSLASTUPDATED"

FROM AIRCRAFT, SQUADRONS, COMBATSCLS

WHERE ((AIRCRAFT.AIRCRAFTID = AIRCRAFTIDIN)
	  AND (AIRCRAFT.SQUADRONID = SQUADRONS.SQUADRONID(+))
	  AND (AIRCRAFT.COMBATSCLID = COMBATSCLS.COMBATSCLID(+))   );

END Spgetweaponsstatus;

 
 
 
 
 
 
 
 
@
