--<ScriptOptions statementTerminator="@"/>


CREATE PROCEDURE         "EMOC3"."GET_CONDITIONCODES" (
P_CURSOR OUT EMOC_TYPES.EMOC_CURSOR
)
AS
BEGIN
-- RETURN THE CURSOR FOR THE RECORDSET
OPEN P_CURSOR FOR
SELECT   CONDITIONCODES.CONDCODEID,
		 CONDITIONCODES.CONDITIONCODE,
		 CONDITIONCODES.CONDITIONDESCRIPTION,
		 NVL(CONDITIONCODES.DEFAULTCONDITIONCODE, 0) as DEFAULTCONDITIONCODE ,
		 CONDITIONCODES.CONDSTATID,
		 CONDITIONSTATUS.CONDITIONSTATUS
FROM CONDITIONCODES,CONDITIONSTATUS
WHERE CONDITIONCODES.CONDSTATID = CONDITIONSTATUS.CONDSTATID
ORDER BY CONDITIONCODES.CONDITIONCODE ASC;

END GET_CONDITIONCODES;

 
 
 
 
 
 
 
 
@
