--<ScriptOptions statementTerminator="@"/>


CREATE PROCEDURE         "EMOC3"."SPINSERTENGINERUN" (

ABSTARTIN ENGINERUNLOG.ABSTART%TYPE,
ABSTOPIN ENGINERUNLOG.ABSTOP%TYPE,
EMPLOYEENUMBERIN ENGINERUNLOG.EMPLOYEENUMBER%TYPE,
ENGINEDATAIDIN ENGINERUNLOG.ENGINEDATAID%TYPE,
IDLESTARTIN ENGINERUNLOG.IDLESTART%TYPE,
IDLESTOPIN ENGINERUNLOG.IDLESTOP%TYPE,
LASTUPDATEIN VARCHAR,
LASTUPDATEBYIN ENGINERUNLOG.LASTUPDATEBY%TYPE,
MILSTARTIN ENGINERUNLOG.MILSTART%TYPE,
MILSTOPIN ENGINERUNLOG.MILSTOP%TYPE,
MISUPDATEDIN ENGINERUNLOG.MISUPDATED%TYPE,
MOCCONTROLLERIN ENGINERUNLOG.MOCCONTROLLER%TYPE,
QUALCHECKEDIN ENGINERUNLOG.QUALCHECKED%TYPE,
REASONIN ENGINERUNLOG.REASON%TYPE,
RUNDATEIN VARCHAR,
RUNPERSONIN ENGINERUNLOG.RUNPERSON%TYPE,
SPAPPROVALIN ENGINERUNLOG.SPAPPROVAL%TYPE,
STANDBYFIRETRUCKIN ENGINERUNLOG.STANDBYFIRETRUCK%TYPE,
TOWERRUNCLEARANCEIN ENGINERUNLOG.TOWERRUNCLEARANCE%TYPE,
AIRCRAFTIDIN ENGINERUNLOG.AIRCRAFTID%TYPE

)
AS
ROW_ID INTEGER;

BEGIN

SELECT NVL(MAX(ENGINERUNLOG.ENGINELOGID), 0)
INTO ROW_ID
FROM ENGINERUNLOG;

INSERT INTO ENGINERUNLOG (ENGINELOGID, ABSTART, ABSTOP, EMPLOYEENUMBER, ENGINEDATAID, IDLESTART, IDLESTOP, LASTUPDATE,
	   		LASTUPDATEBY, MILSTART, MILSTOP, MISUPDATED, MOCCONTROLLER, QUALCHECKED, REASON, RUNDATE,
			RUNPERSON, SPAPPROVAL, STANDBYFIRETRUCK, TOWERRUNCLEARANCE, AIRCRAFTID)

VALUES (ROW_ID + 1, ABSTARTIN, ABSTOPIN, EMPLOYEENUMBERIN, ENGINEDATAIDIN, IDLESTARTIN, IDLESTOPIN, TO_DATE(LASTUPDATEIN, 'MM/DD/YYYY HH24:MI:SS'),
	   LASTUPDATEBYIN, MILSTARTIN, MILSTOPIN, MISUPDATEDIN, MOCCONTROLLERIN, QUALCHECKEDIN, REASONIN, TO_DATE(RUNDATEIN, 'MM/DD/YYYY HH24:MI:SS'), RUNPERSONIN,
	   SPAPPROVALIN, STANDBYFIRETRUCKIN, TOWERRUNCLEARANCEIN, AIRCRAFTIDIN);


END SPINSERTENGINERUN;

 
 
 
 
 
 
 
 
@
