--<ScriptOptions statementTerminator="@"/>


CREATE PROCEDURE         "EMOC3"."SPINSERTSHOPDISPATCH" (

AIRCRAFTIDIN SHOPDISPATCH.AIRCRAFTID%TYPE,
COMPLETIONDATEIN VARCHAR,
DISCREPANCYIN SHOPDISPATCH.DISCREPANCY%TYPE,
ETICSHOWTIMEIN VARCHAR,
PERSONCONTACTEDIN SHOPDISPATCH.PERSONCONTACTED%TYPE,
PERSONDISPATCHEDIN SHOPDISPATCH.PERSONDISPATCHED%TYPE,
REQUESTDATEIN VARCHAR,
REQUESTERIN SHOPDISPATCH.REQUESTER%TYPE,
SQDISPATCHEDTOIDIN SHOPDISPATCH.SQDISPATCHEDTOID%TYPE,
WORKCENTERIDIN SHOPDISPATCH.WORKCENTERID%TYPE

)
AS

ROW_ID INTEGER;
BEGIN


SELECT NVL(MAX(SHOPDISPATCH.SHOPDISPATCHID), 0)
INTO ROW_ID
FROM SHOPDISPATCH;


INSERT INTO SHOPDISPATCH(SHOPDISPATCHID, AIRCRAFTID, COMPLETIONDATE, DISCREPANCY, ETICSHOWTIME, PERSONCONTACTED,
	   PERSONDISPATCHED, REQUESTDATE, REQUESTER, SQDISPATCHEDTOID, WORKCENTERID)

VALUES (ROW_ID + 1, AIRCRAFTIDIN, TO_DATE(COMPLETIONDATEIN,'MM/DD/YYYY HH24:MI:SS'), DISCREPANCYIN, TO_DATE(ETICSHOWTIMEIN,'MM/DD/YYYY HH24:MI:SS'), PERSONCONTACTEDIN,
	   PERSONDISPATCHEDIN, TO_DATE(REQUESTDATEIN, 'MM/DD/YYYY HH24:MI:SS'), REQUESTERIN, SQDISPATCHEDTOIDIN, WORKCENTERIDIN);


END SPINSERTSHOPDISPATCH;

 
 
 
 
 
 
 
 
@
