--<ScriptOptions statementTerminator="@"/>


CREATE PROCEDURE         "EMOC3"."SPUPDATESQUADSORTORDER" (

USERIDIN SQUADRON_SORT_ORDER.USERID%TYPE,
SQUADRONIDIN SQUADRON_SORT_ORDER.SQUADRONID%TYPE,
SORTORDERIN SQUADRON_SORT_ORDER.SORTORDER%TYPE

)
AS
COUNTER INTEGER;
ROW_ID INTEGER;
BEGIN

SELECT COUNT(*) INTO COUNTER
FROM SQUADRON_SORT_ORDER
WHERE (		 (USERID = USERIDIN)
AND (SQUADRONID = SQUADRONIDIN )		);

SELECT NVL(MAX(SQUADRON_SORT_ORDER.SQSORTORDERID), 0)
--SELECT MAX(SQUADRON_SORT_ORDER.SQSORTORDERID)
INTO ROW_ID
FROM SQUADRON_SORT_ORDER;


IF (COUNTER = 0) THEN
INSERT INTO SQUADRON_SORT_ORDER (SQSORTORDERID, USERID, SQUADRONID, SORTORDER)

VALUES (ROW_ID + 1, USERIDIN, SQUADRONIDIN, SORTORDERIN);

ELSE
UPDATE SQUADRON_SORT_ORDER
SET

SQUADRON_SORT_ORDER.SORTORDER = SORTORDERIN

WHERE ((USERID = USERIDIN)
AND (SQUADRONID = SQUADRONIDIN ) );


END IF;

END SPUPDATESQUADSORTORDER;

 
 
 
 
 
 
 
 
@
