--<ScriptOptions statementTerminator="@"/>


CREATE PROCEDURE         "EMOC3"."SPGETPACINGWRITEUP" 
(
P_CURSOR OUT Emoc_Types.EMOC_CURSOR,
AIRCRAFTIDIN WRITEUPS.AIRCRAFTID%TYPE)
AS
BEGIN
-- RETURN THE CURSOR FOR THE RECORDSET
OPEN P_CURSOR FOR
SELECT WRITEUPS.WRITEUPID,
	   WRITEUPS.DISCREPANCY,
	   WRITEUPS.JCN,
	   TO_CHAR(WRITEUPS.WRITEUPTIME, 'MM/DD/YYYY HH24:MI:SS') "WRITEUPTIME",
	   WRITEUPS.PACER,
	   WUC.WUCCODE,
	   WRITEUPS.ETIC

FROM WRITEUPS, WUC

WHERE ( (WRITEUPS.AIRCRAFTID = AIRCRAFTIDIN)
	  	AND (WRITEUPS.CORRECTED = 0)
		AND (WRITEUPS.PACER = 1)
		AND (WRITEUPS.WUCID = WUC.WUCID(+)));


END SPGETPACINGWRITEUP;

 
 
 
 
 
 
 
 
@
