--<ScriptOptions statementTerminator="@"/>


CREATE PROCEDURE         "EMOC3"."SPUPDATELASTCHIP" (

CHIPDATAIDIN SEMEDXDATA.SEMDATAID%TYPE,
ENGINEDATAIDIN SEMEDXDATA.ENGINEDATAID%TYPE,
SCHEDULEIDIN SEMEDXDATA.SCHEDULEID%TYPE,
MOCCONTROLLERIN SEMEDXDATA.MOCCONTROLLER%TYPE,
SAMPLEDATEIN VARCHAR,
CHIPIDIN SEMEDXDATA.SEMEDXID%TYPE,
REASONIN SEMEDXDATA.REASON%TYPE,
HOURSREQUIREDIN SEMEDXDATA.HOURSREQUIRED%TYPE,
HOURSREMAININGIN SEMEDXDATA.HOURSREMAINING%TYPE,
NOTIFIEDBYIN SEMEDXDATA.NOTIFIEDBY%TYPE,
EXPEDITERNOTIFIEDIN SEMEDXDATA.EXPEDITERNOTIFIED%TYPE,
CHIPLASTUPDATEDIN VARCHAR

)
AS
BEGIN
UPDATE SEMEDXDATA
SET

SEMEDXDATA.MOCCONTROLLER = MOCCONTROLLERIN,
SEMEDXDATA.SAMPLEDATE = TO_DATE(SAMPLEDATEIN,'MM/DD/YYYY HH24:MI:SS'),
SEMEDXDATA.SEMEDXID = CHIPIDIN,
SEMEDXDATA.REASON = REASONIN,
SEMEDXDATA.HOURSREQUIRED = HOURSREQUIREDIN,
SEMEDXDATA.HOURSREMAINING = HOURSREMAININGIN,
SEMEDXDATA.NOTIFIEDBY = NOTIFIEDBYIN,
SEMEDXDATA.EXPEDITERNOTIFIED = EXPEDITERNOTIFIEDIN,
SEMEDXDATA.SEMEDXLASTUPDATED = TO_DATE(CHIPLASTUPDATEDIN, 'MM/DD/YYYY HH24:MI:SS')

WHERE ((SEMDATAID = CHIPDATAIDIN));



END SPUPDATELASTCHIP;

 
 
 
 
 
 
 
 
@
