--<ScriptOptions statementTerminator="@"/>


CREATE PROCEDURE         "EMOC3"."GET_AIRCRAFT_BY_LOCATION" (
LOCATIONIDIN   LOCATIONS.LOCATIONID%TYPE,
P_CURSOR  OUT EMOC_TYPES.EMOC_CURSOR
)
AS
BEGIN

	 OPEN P_CURSOR FOR
	 SELECT AIRCRAFT.AIRCRAFTID,
	 		AIRCRAFT.TAILNUMBER
	 FROM   AIRCRAFT
	 WHERE 	AIRCRAFT.LOCATIONID = LOCATIONIDIN
	 ORDER BY TAILNUMBER;

END GET_AIRCRAFT_BY_LOCATION;
 
 
 
 
 
 
 
 
@
