--<ScriptOptions statementTerminator="@"/>


CREATE PROCEDURE         "EMOC3"."GET_DEVIATIONCODES" (
P_CURSOR OUT EMOC_TYPES.EMOC_CURSOR
)
AS
BEGIN
-- RETURN THE CURSOR FOR THE RECORDSET
OPEN P_CURSOR FOR
SELECT   DEVIATIONCODES.DEVIATIONCODEID,
		 DEVIATIONCODES.DEVIATIONCODE,
		 DEVIATIONCODES.DEVIATIONDESCRIPTION,
		 NVL(DEVIATIONCODES.DEFAULTDEVIATIONCODE, 0) as DEFAULTDEVIATIONCODE,
		 DEVIATIONCODES.COLORID,
		 COLORS.COLORNAME,
		 COLORS.COLORVALUE
FROM DEVIATIONCODES,COLORS
WHERE DEVIATIONCODES.COLORID = COLORS.COLORID
ORDER BY DEVIATIONCODES.DEVIATIONCODE ASC;

END GET_DEVIATIONCODES;

 
 
 
 
 
 
 
 
@
