--<ScriptOptions statementTerminator="@"/>


CREATE PROCEDURE         "EMOC3"."SPUPDATEINTERFACELOG" (
AIRCRAFTIDIN INTERFACELOG.AIRCRAFTID%TYPE,
TIMEOFINSERTIN INTERFACELOG.TIMEOFINSERT%TYPE,
TBMCSMSGSUBJECTIN varchar2,
TBMCSMSGTYPEIN varchar2,
TBMCSONLYIN varchar2,
TBMCSSUMMARYSENTIN DATE,
TBMCSXMLIN varchar2,
INTERFACECONTROLIDIN INTERFACELOG.INTERFACECONTROLID%TYPE

)
AS
ROW_ID INTEGER;
BEGIN


SELECT NVL(MAX(INTERFACELOG.INTERFACELOGID), 0)
INTO ROW_ID
FROM INTERFACELOG;

INSERT INTO INTERFACELOG (INTERFACELOGID, AIRCRAFTID, TIMEOFINSERT,
           INTERFACECONTROLID )

VALUES (ROW_ID + 1, AIRCRAFTIDIN, TIMEOFINSERTIN,
               INTERFACECONTROLIDIN);


END SPUPDATEINTERFACELOG;
 
 
 
 
 
 
 
 
@
