--<ScriptOptions statementTerminator="@"/>


CREATE PROCEDURE         "EMOC3"."SPINSERTCHIP" (

CHIPDATAIDIN SEMEDXDATA.SEMDATAID%TYPE,
ENGINEDATAIDIN SEMEDXDATA.ENGINEDATAID%TYPE,
SCHEDULEIDIN SEMEDXDATA.SCHEDULEID%TYPE,
MOCCONTROLLERIN SEMEDXDATA.MOCCONTROLLER%TYPE,
SAMPLEDATEIN VARCHAR,
CHIPIDIN SEMEDXDATA.SEMEDXID%TYPE,
REASONIN SEMEDXDATA.REASON%TYPE,
HOURSREQUIREDIN SEMEDXDATA.HOURSREQUIRED%TYPE,
HOURSREMAININGIN SEMEDXDATA.HOURSREMAINING%TYPE,
NOTIFIEDBYIN SEMEDXDATA.NOTIFIEDBY%TYPE,
EXPEDITERNOTIFIEDIN SEMEDXDATA.EXPEDITERNOTIFIED%TYPE,
CHIPLASTUPDATEDIN VARCHAR

)
AS
ROW_ID INTEGER;

BEGIN

SELECT NVL(MAX(SEMEDXDATA.SEMDATAID), 0)
INTO ROW_ID
FROM SEMEDXDATA;

INSERT INTO SEMEDXDATA (SEMDATAID, SEMEDXID, ENGINEDATAID, MOCCONTROLLER, SAMPLEDATE, REASON, HOURSREQUIRED,
	   				 HOURSREMAINING, NOTIFIEDBY, EXPEDITERNOTIFIED, SEMEDXLASTUPDATED, SCHEDULEID)

VALUES (ROW_ID + 1, CHIPIDIN, ENGINEDATAIDIN, MOCCONTROLLERIN, TO_DATE(SAMPLEDATEIN, 'MM/DD/YYYY HH24:MI:SS'), REASONIN, HOURSREQUIREDIN,
	   		   	 	HOURSREMAININGIN, NOTIFIEDBYIN, EXPEDITERNOTIFIEDIN, TO_DATE(CHIPLASTUPDATEDIN, 'MM/DD/YYYY HH24:MI:SS'), SCHEDULEIDIN);


END SPINSERTCHIP;

 
 
 
 
 
 
 
 
@
