--<ScriptOptions statementTerminator="@"/>


CREATE TRIGGER "EMOC3"."CHECKLIST_TRI1" 
	BEFORE INSERT ON "EMOC3"."CHECKLIST"
	REFERENCING NEW AS NEW OLD AS OLD
	FOR EACH ROW
BEGIN
	SELECT SEQ_CHECKLIST.NEXTVAL INTO :NEW.CHECKLISTID FROM dual;
END;

@
