--<ScriptOptions statementTerminator="@"/>


CREATE FUNCTION         "EMOC3"."FUNCCOUNTENGINERELATEDDATA" (p_aircraftid IN INTEGER) 
RETURN NUMBER
IS 
var_temp_count NUMBER; 
COUNTER1 INTEGER;
COUNTER2 INTEGER;
COUNTER3 INTEGER;
BEGIN 

SELECT COUNT(*) INTO COUNTER1
FROM JOAPDATA,AIRCRAFTENGINEDATA
WHERE JOAPDATA.ENGINEDATAID = AIRCRAFTENGINEDATA.ENGINEDATAID
AND AIRCRAFTENGINEDATA.AIRCRAFTID = p_aircraftid;

SELECT COUNT(*) INTO COUNTER2
FROM SEMEDXDATA,AIRCRAFTENGINEDATA
WHERE SEMEDXDATA.ENGINEDATAID = AIRCRAFTENGINEDATA.ENGINEDATAID
AND AIRCRAFTENGINEDATA.AIRCRAFTID = p_aircraftid;

SELECT COUNT(*) INTO COUNTER3
FROM WEAPONSLOAD
WHERE AIRCRAFTID = p_aircraftid;

IF (COUNTER1 + COUNTER2 + COUNTER3) = 0 THEN
   var_temp_count := 0;
END IF;
IF (COUNTER1 + COUNTER2 + COUNTER3) > 0 THEN 
   var_temp_count := 1;
END IF;

return var_temp_count;
END;



 
 
 
 
 
 
 
 
@
